// The DPF editor — a thin DISTRHO::UI on the generic LVGL top-level widget.
//
// It attaches its LVGL display layer to the plugin's plugin-lifetime TjsHostRuntime (via the in-process
// SharedDSP handoff + LvglJsEngine::useExternalHost), evals the React UI bundle once onto that
// same context, and mounts it. The backend is already reachable there through Symbol.for("plugin")
// .__rpcSend (bound by bootControlPlane), so — unlike the legacy PluginUI — there is no PluginJsBridge,
// no params/gamepad/file-browser plumbing here: the UI drives the real Engine over RPC exactly as the
// headless harness does.
//
// The GL flush, the keypad/pointer indevs, the 60 fps lv_timer_handler, and DPF→LVGL input translation
// all come free from the base widget (dpf-widgets/generic/LVGL). This class only: pumps the JS host +
// emits "frame" per idle, mirrors keyboard/mouse to the JS event bus (the App's Esc handler / policy),
// swallows the wheel into a hit-tested scroll, and dumps a screenshot on the env hook.

#include "DistrhoUI.hpp"
#include "Application.hpp" // getWindow().getApp().isStandalone()
#include "ResizeHandle.hpp" // the user-resize grip fallback

#include "dpfjs/LvglJsEngine.hpp"
#include "dpfjs/host/TjsHostRuntime.hpp" // TjsHostRuntime + quickjs.h/tjs.h
#include "dpfjs/Env.hpp"                 // dpfjs::getenvWithPrefix

#include "PluginShared.hpp"
#include "ContextTargets.hpp"             // per-context routing for the __rp_* window hooks
#include "host/input/GamepadManager.hpp" // SDL controller poll (shared UI-thread input)
#include "host/render/RenderJobRegistry.hpp" // background render jobs (the __rp_*Render hooks)
#include "host/ui/NativeFileDialog.hpp"   // OS-native file picker (pfd) — shared with the SDL host

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>

extern "C" {
#include "lvgl.h"
}

#include "native/core/img/png/lodepng.h"
#include "native/components/component.hpp" // GetWindowInstance() — the lv_binding_js React-tree root

extern "C" {
// Generated by tjsc (CMake retroplug-ui-bundle, -p rp_): the React UI as QuickJS bytecode.
extern const std::uint8_t  rp_ui_bundle[];
extern const std::uint32_t rp_ui_bundle_size;
}

START_NAMESPACE_DISTRHO

class PluginUI; // defined below; forward-declared for the window-size hook installer

namespace {
bool hasGlobalFunction(JSContext* ctx, const char* name) {
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue v      = JS_GetPropertyStr(ctx, global, name);
    const bool ok  = JS_IsFunction(ctx, v);
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, global);
    return ok;
}

// Installs __rp_setWindowSize(w,h) / __rp_isWindowSizeControlled() / __rp_openFileBrowser(...) etc. on
// `ctx`, routed to `ui`. The editor's analog of the setWindowSizeCallback / file-browser RPC seams:
// the editor isn't on the backend RPC side, so it hangs native C-functions on the shared context. Each
// hook carries its editor through per-context func-data (not a process-global), so concurrent plugin
// instances — each with its own control-plane context — never cross-route into one another's window. The
// UI optional-chains them, so they are inert where absent (the headless harness). clearWindowSizeHooks
// un-points this editor's per-context target on teardown (the hooks outlive us on the persistent context).
void installWindowSizeHooks(JSContext* ctx, PluginUI* ui);
void clearWindowSizeHooks(JSContext* ctx, PluginUI* ui);
} // namespace

class PluginUI : public UI {
    // The display layer for this editor session, riding the plugin's shared host (useExternalHost).
    LvglJsEngine jsEngine;

    // Screenshot hook (RETROPLUG_SCREENSHOT_PATH, cadence RETROPLUG_SCREENSHOT_INTERVAL_MS): dump the
    // whole LVGL screen as PNG from the UI thread. Distinct from the emulator RPC's screenshot (one core).
    std::string screenshotPath_;
    std::chrono::milliseconds screenshotInterval_{1000};
    std::chrono::steady_clock::time_point screenshotLast_{};
    bool windowTitleSet_ = false;
    bool allowClose_ = false; // set by requestQuit() so the re-entrant onClose() lets the window close
    unsigned watcherPumpTick_ = 0; // throttles the file-watcher pump in uiIdle (efsw already coalesced)

    // Window geometry: the resize-grip fallback + tiling-WM clamp detection. Once a size comes back
    // different from what we asked (a Wayland/Hyprland tile), wmControlled_ latches true and we stop
    // driving setSize — the compositor owns geometry (mirrors legacy PluginUI).
    ResizeHandle fResizeHandle;
    uint requestedW_ = 0;
    uint requestedH_ = 0;
    bool wmControlled_ = false;
    // True once a resize we asked for actually took (a reported size matched the request) — i.e. we've
    // proven this window is ours to size (it's floating, not tiled). Gates the clamp latch below so a later
    // spurious compositor resize (a floating window shrunk on move) isn't mistaken for a tiling takeover.
    bool sizeHonored_ = false;
    bool debugResize_ = false; // RETROPLUG_DEBUG_RESIZE: log every requestWindowSize / onResize (WM debugging)

    // SDL game-controller poller (reused from the legacy build). Ticked from uiIdle() on the UI thread; it
    // re-emits each transition onto the gamepad-* JS bus that useGamepadInput subscribes to. Inert
    // (ok()==false, update() a no-op) when SDL_INIT_GAMECONTROLLER fails — e.g. headless CI with no device.
    retroplug::GamepadManager gamepad_;

    // The in-flight OS-native file dialog (pfd), opened by requestFileBrowser and polled in uiIdle. Shared
    // with the SDL host so both surface the same picker.
    retroplug::ui::NativeFileDialog nativeDialog_;

    void maybeWriteScreenshot() {
        if (screenshotPath_.empty()) return;
        const auto now = std::chrono::steady_clock::now();
        if (now - screenshotLast_ < screenshotInterval_) return;
        screenshotLast_ = now;

        lv_obj_t* screen = lv_screen_active();
        if (!screen) return;
        lv_draw_buf_t* snap = lv_snapshot_take(screen, LV_COLOR_FORMAT_ARGB8888);
        if (!snap) return;

        const uint32_t w = snap->header.w;
        const uint32_t h = snap->header.h;
        std::vector<unsigned char> rgb(static_cast<size_t>(w) * h * 3);
        const uint8_t* src = snap->data; // ARGB8888 = B,G,R,A on little-endian
        for (size_t i = 0, n = static_cast<size_t>(w) * h; i < n; ++i) {
            rgb[i * 3 + 0] = src[i * 4 + 2];
            rgb[i * 3 + 1] = src[i * 4 + 1];
            rgb[i * 3 + 2] = src[i * 4 + 0];
        }
        const unsigned err = lodepng_encode24_file(screenshotPath_.c_str(), rgb.data(), w, h);
        if (err) d_stderr("[ui] screenshot lodepng error %u: %s", err, lodepng_error_text(err));
        lv_draw_buf_destroy(snap);
    }

    // Poll SDL controllers once per idle and re-emit each transition onto the JS event bus — the gamepad-*
    // channels useGamepadInput subscribes to. Ported from legacy PluginUI::pumpGamepad; native stays dumb
    // (raw SDL button-name strings), while the GB-button mapping / focus routing / bindings all live in TS.
    void pumpGamepad(JSContext* ctx) {
        gamepad_.update([this, ctx](const retroplug::GamepadEvent& ev) {
            switch (ev.kind) {
                case retroplug::GamepadEvent::Kind::Connected: {
                    JSValue args[2] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.name ? ev.name : "")};
                    jsEngine.emit("gamepad-connected", 2, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Disconnected: {
                    JSValue args[1] = {JS_NewInt32(ctx, ev.pad)};
                    jsEngine.emit("gamepad-disconnected", 1, args);
                    JS_FreeValue(ctx, args[0]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Button: {
                    JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.button ? ev.button : ""),
                                       JS_NewBool(ctx, ev.pressed)};
                    jsEngine.emit("gamepad-button", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Axis: {
                    JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.axis ? ev.axis : ""),
                                       JS_NewFloat64(ctx, ev.value)};
                    jsEngine.emit("gamepad-axis", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
            }
        });
    }

public:
    // Ask the host/WM for a window of w×h. Latches wmControlled_ if the compositor has taken geometry
    // (then we don't fight it). Called from the UI via the __rp_setWindowSize seam.
    bool requestWindowSize(uint w, uint h) {
        if (w == 0 || h == 0) return wmControlled_;
        requestedW_ = w;
        requestedH_ = h;
        if (wmControlled_) return true; // don't fight the compositor
        setSize(w, h);
        if (debugResize_)
            d_stdout("[resize] request %ux%u -> cur %ux%u (wmC=%d honored=%d)", w, h, getWidth(), getHeight(),
                     (int)wmControlled_, (int)sizeHonored_);
        return wmControlled_;
    }
    bool isWindowSizeControlled() const { return wmControlled_; }

    // Open the OS-native file dialog for the UI (the menu's Load / Save / Export / Locate items). Two backends:
    //  - portable-file-dialogs (NativeFileDialog), the SAME picker the SDL host uses, WHEN a desktop helper
    //    (zenity/kdialog/…) exists. It surfaces reliably even in a DAW-hosted editor, where DPF's own browser
    //    could bind the hook yet never show a dialog (the reported bug).
    //  - else DPF's built-in openFileBrowser, which needs NO helper (xdg-desktop-portal / libsofd X11) and
    //    works in the standalone. So a helper-less host keeps a working OS dialog instead of silently
    //    dropping to the in-app browser (the regression a hard availability gate caused).
    // `patterns` is a whitespace-separated glob list; `directory` picks a FOLDER (the render "Output Dir");
    // `saving` seeds the save name with defaultName. Non-blocking either way: the pick arrives later via
    // uiFileBrowserSelected (pfd is polled in uiIdle; DPF calls it directly). One dialog is ever in flight.
    void requestFileBrowser(const char* title, const char* patterns, bool saving, const char* defaultName,
                            const char* startDir, bool directory) {
        if (retroplug::ui::NativeFileDialog::available()) {
            nativeDialog_.request(title ? title : "", patterns ? patterns : "", saving,
                                  defaultName ? defaultName : "", startDir ? startDir : "", directory);
            return;
        }
        FileBrowserOptions opts;
        opts.title  = (title && *title) ? title : "Open";
        opts.saving = saving;
        opts.directory = directory; // pick a FOLDER (our DPF fork; Linux + macOS) — the render "Output Dir"
        if (defaultName && *defaultName) opts.defaultName = defaultName;
        if (startDir && *startDir) opts.startDir = startDir;
        if (patterns && *patterns) opts.fileFilterPatterns = patterns;
        openFileBrowser(opts);
    }

    // Close the standalone window for real — called from the UI via the __rp_quitWindow seam once the
    // unsaved-changes prompt is resolved (Save or Discard). allowClose_ lets the re-entrant onClose()
    // (getWindow().close() re-asks) through. Standalone only; a DAW never reaches here.
    void requestQuit() {
        allowClose_ = true;
        getWindow().close();
        getWindow().getApp().quit();
    }

    // Reveal `path` in the OS file manager (the Settings -> Open Settings Folder item). Fire-and-forget
    // via the __rp_openPath seam; a per-OS shell handler backgrounded so it never blocks the UI, mirroring
    // legacy PluginRpcService::openSettingsFolder.
    void openPath(const char* path) {
        if (!path || !*path) return;
        const std::string p(path);
#if defined(__APPLE__)
        const std::string cmd = "open \"" + p + "\" &";
#elif defined(_WIN32)
        const std::string cmd = "start \"\" \"" + p + "\"";
#else
        const std::string cmd = "xdg-open \"" + p + "\" &";
#endif
        (void)std::system(cmd.c_str());
    }

    // Set the OS window title (standalone only — a DAW owns the plugin window). Called from the UI via the
    // __rp_setWindowTitle seam; the JS composes "RetroPlug v<version> - <project>". Overrides the static
    // boot title set in uiIdle.
    void setWindowTitle(const char* title) {
        if (title && *title && getWindow().getApp().isStandalone()) getWindow().setTitle(title);
    }

    PluginUI() : UI(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT), fResizeHandle(this) {
        // Resizable window (DISTRHO_UI_USER_RESIZABLE): seed the requested-size baseline so onResize's
        // clamp detection is armed before the WM's first resize, set the min-size floor (HiDPI-scaled),
        // and hide the fallback grip when the platform gives a native resize border.
        requestedW_ = DISTRHO_UI_DEFAULT_WIDTH;
        requestedH_ = DISTRHO_UI_DEFAULT_HEIGHT;
        const double scaleFactor = getScaleFactor();
        if (d_isNotEqual(scaleFactor, 1.0)) {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
            setSize(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
        } else {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT);
        }
        if (isResizable()) fResizeHandle.hide();

        debugResize_ = dpfjs::getenvWithPrefix("DEBUG_RESIZE") != nullptr;

        if (const char* p = dpfjs::getenvWithPrefix("SCREENSHOT_PATH"); p && *p) {
            screenshotPath_ = p;
            if (const char* iv = dpfjs::getenvWithPrefix("SCREENSHOT_INTERVAL_MS"); iv && *iv)
                if (int ms = std::atoi(iv); ms > 0) screenshotInterval_ = std::chrono::milliseconds(ms);
            d_stdout("[ui] screenshot hook: %s every %lld ms", screenshotPath_.c_str(),
                     static_cast<long long>(screenshotInterval_.count()));
        }

        // Reach the plugin's shared host (in-process) and attach this editor's LVGL layer to it BEFORE
        // init(), so the UI runs on the control-plane context where __rpcSend already lives.
        SharedDSP* shared = nullptr;
        if (void* dspPtr = getPluginInstancePointer()) shared = getSharedDSP(dspPtr);
        if (shared && shared->host)
            jsEngine.useExternalHost(*shared->host);
        else
            d_stderr("[ui] no shared host — UI cannot reach the backend");

        if (!jsEngine.init()) {
            d_stderr("[ui] LvglJsEngine init failed");
            return;
        }

        // Eval the UI bundle once per host: __rp_mountUI is registered by the bundle at module scope, so
        // its absence means the bundle hasn't run yet in this (shared, already-control-plane) context.
        JSContext* ctx = jsEngine.getContext();
        if (ctx && !hasGlobalFunction(ctx, "__rp_mountUI")) {
            if (jsEngine.evalModuleBytecode(rp_ui_bundle, rp_ui_bundle_size) != 0)
                d_stderr("[ui] failed to eval UI bundle");
            else
                d_stdout("[ui] React UI loaded (embedded)");
        }

        jsEngine.attachDisplay(); // → __rp_mountUI

        // The screen is a plain lv_obj, so lv_theme_default (DARK) gives it a rounded border + padding and
        // leaves it scrollable. Black it out, strip the chrome, and clear the scrollable flag so nothing —
        // an off-by-one child, a fixed-size root — can draw a border, inset the UI, or raise a scrollbar.
        if (lv_obj_t* screen = lv_screen_active()) {
            lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
            lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
            lv_obj_set_style_border_width(screen, 0, 0);
            lv_obj_set_style_radius(screen, 0, 0);
            lv_obj_set_style_pad_all(screen, 0, 0);
            lv_obj_remove_flag(screen, LV_OBJ_FLAG_SCROLLABLE);
        }

        // lv_binding_js pins the React-tree root to the display's CURRENT pixel size (480×432 at mount);
        // switch it to 100% so the tree tracks the screen when lv_display_set_resolution grows it on a
        // resize (mirrors legacy PluginUI). Then hang the window-size seam on the shared context.
        if (lv_obj_t* win = GetWindowInstance()) {
            lv_obj_set_style_width(win, lv_pct(100), 0);
            lv_obj_set_style_height(win, lv_pct(100), 0);
        }
        installWindowSizeHooks(ctx, this);

        // Size the window to the already-loaded project's grid BEFORE it first maps. The UI's fit-to-grid
        // effect only runs on the first frame (after the window is shown), so the window would otherwise map
        // at the 480×432 default and get resized afterwards — which a compositor that captures a floating
        // window's size at map time (Hyprland re-applies it on every drag, hyprwm/Hyprland#2105) remembers as
        // the "real" size, snapping back to 480 on a move. Sizing here maps it correct from the start. No-op
        // for an empty project / no control plane (__rp_initialWindowSize returns null).
        if (ctx) applyInitialWindowSize(ctx);
    }

    // Ask the UI bundle for the initial window size of the loaded project (__rp_initialWindowSize, computed
    // the same way App fits the window) and drive it through requestWindowSize. Null / absent → keep the
    // default (empty project, or the headless harness with no bundle helper).
    void applyInitialWindowSize(JSContext* ctx) {
        JSValue global = JS_GetGlobalObject(ctx);
        JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_initialWindowSize");
        if (JS_IsFunction(ctx, fn)) {
            JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 0, nullptr);
            if (JS_IsObject(ret)) {
                JSValue      wv = JS_GetPropertyStr(ctx, ret, "width");
                JSValue      hv = JS_GetPropertyStr(ctx, ret, "height");
                std::uint32_t w = 0, h = 0;
                JS_ToUint32(ctx, &w, wv);
                JS_ToUint32(ctx, &h, hv);
                JS_FreeValue(ctx, wv);
                JS_FreeValue(ctx, hv);
                if (w > 0 && h > 0) requestWindowSize(w, h);
            }
            JS_FreeValue(ctx, ret);
        }
        JS_FreeValue(ctx, fn);
        JS_FreeValue(ctx, global);
    }

    ~PluginUI() override {
        // Unmount (→ __rp_unmountUI) + flush the async widget deletes while the context is still alive,
        // leaving the shared host clean for the next editor session.
        clearWindowSizeHooks(jsEngine.getContext(), this); // hooks outlive us on the shared context — un-point our target
        jsEngine.detachDisplay();
        lv_timer_handler();
        if (lv_obj_t* screen = lv_screen_active()) lv_obj_clean(screen);
    }

protected:
    void parameterChanged(uint32_t, float) override {} // UI drives nothing via params

    // Standalone window-close veto (DPF forwards Window::onClose here only in standalone; a DAW owns the
    // plugin lifecycle). Ask the UI via __rp_onCloseRequested whether to keep the window open: when there
    // are unsaved changes it shows the Save/Discard/Cancel prompt and returns true, so we veto (return
    // false). Once the user confirms, JS calls __rp_quitWindow → requestQuit(), which re-enters here with
    // allowClose_ set. Absent hook (headless / not yet mounted) → allow the close.
    bool onClose() override {
        if (allowClose_) return true;
        JSContext* ctx = jsEngine.getContext();
        if (!ctx) return true;
        JSValue global = JS_GetGlobalObject(ctx);
        JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_onCloseRequested");
        bool veto = false;
        if (JS_IsFunction(ctx, fn)) {
            JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 0, nullptr);
            veto = JS_ToBool(ctx, ret) == 1;
            JS_FreeValue(ctx, ret);
        }
        JS_FreeValue(ctx, fn);
        JS_FreeValue(ctx, global);
        return !veto;
    }

    // The OS file dialog's result (null/empty filename = cancel). Deliver it into JS by calling the
    // __rp_onFileBrowserResult resolver the real Backend registered — same shared context, same UI thread
    // that pumps the JS loop, so a direct call is safe (the awaiting Promise settles on the next tick).
    // Now driven by the NativeFileDialog (pfd) poll in uiIdle rather than DPF's browser, but kept as the DPF
    // override too (USE_FILE_BROWSER stays on for drag-and-drop) so DPF never routes a stray pick elsewhere.
    void uiFileBrowserSelected(const char* filename) override {
        JSContext* ctx = jsEngine.getContext();
        if (!ctx) return;
        JSValue global = JS_GetGlobalObject(ctx);
        JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_onFileBrowserResult");
        if (JS_IsFunction(ctx, fn)) {
            JSValue arg = (filename && *filename) ? JS_NewString(ctx, filename) : JS_NULL;
            JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 1, &arg);
            JS_FreeValue(ctx, ret);
            JS_FreeValue(ctx, arg);
        }
        JS_FreeValue(ctx, fn);
        JS_FreeValue(ctx, global);
    }

#if DISTRHO_UI_FILE_DROP
    // A native OS file drop (drag-and-drop). Forward the newline-joined absolute paths + the view-local drop
    // coordinate onto the JS "file-drop" bus, where the App's useNativeEvent("file-drop") handler routes it
    // (load-as-project / replace-instance / load-sram). Delivered on the UI thread that pumps the JS loop, so
    // a direct emit is safe. Enabled for both standalone and the DAW-hosted editor.
    void uiFileDropped(const char* paths, double x, double y) override {
        if (std::getenv("PUGL_DND_DEBUG"))
            d_stdout("[dnd] uiFileDropped paths=<<%s>> at %.0f,%.0f", paths ? paths : "(null)", x, y);
        JSContext* ctx = jsEngine.getContext();
        if (!ctx || !paths || !*paths) return;
        JSValue args[3] = {JS_NewString(ctx, paths), JS_NewFloat64(ctx, x), JS_NewFloat64(ctx, y)};
        jsEngine.emit("file-drop", 3, args);
        for (JSValue& v : args) JS_FreeValue(ctx, v);
    }
#endif

    void uiIdle() override {
        if (!windowTitleSet_) {
            windowTitleSet_ = true;
            if (getWindow().getApp().isStandalone()) getWindow().setTitle("RetroPlug");
        }
        if (JSContext* ctx = jsEngine.getContext()) {
            jsEngine.emit("frame", 0, nullptr); // drives EmulatorTile's getFrame
            pumpGamepad(ctx);                   // poll controllers → the gamepad-* JS bus
            // Deliver a finished OS file-dialog pick (async; cancel = empty). uiFileBrowserSelected resolves
            // the awaiting JS Promise via __rp_onFileBrowserResult (empty c-string → null → cancel).
            nativeDialog_.poll([this](const std::string& pick) { uiFileBrowserSelected(pick.c_str()); });
            // File watcher: drain native's changed paths + react (config live-reload / bindings refresh /
            // ROM hot-reload). efsw already coalesced the changes on its own thread, so a low cadence (~1/15
            // frames, a few Hz) is plenty and keeps stat/JS churn off the hot path. Inert if the control
            // plane didn't define the hook (older bundle / headless).
            if ((++watcherPumpTick_ % 15) == 0 && hasGlobalFunction(ctx, "__rp_pumpWatcher")) {
                JSValue global = JS_GetGlobalObject(ctx);
                JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_pumpWatcher");
                JSValue ret    = JS_Call(ctx, fn, JS_UNDEFINED, 0, nullptr);
                JS_FreeValue(ctx, ret);
                JS_FreeValue(ctx, fn);
                JS_FreeValue(ctx, global);
            }
        }
        jsEngine.tick();                                               // pump the shared host's JS loop
        maybeWriteScreenshot();
    }

    void onResize(const ResizeEvent& ev) override {
        UI::onResize(ev); // base LVGLWidget::onResize → lv_display_set_resolution + repaint (free)
        const uint w = ev.size.getWidth();
        const uint h = ev.size.getHeight();
        if (debugResize_)
            d_stdout("[resize] onResize ev=%ux%u win=%ux%u (requested %ux%u wmC=%d honored=%d standalone=%d scale=%.2f)",
                     w, h, getWidth(), getHeight(), requestedW_, requestedH_, (int)wmControlled_, (int)sizeHonored_,
                     (int)getWindow().getApp().isStandalone(), getScaleFactor());
        // Latch once a requested size actually took: proof this window is ours to size (floating, not tiled).
        if (requestedW_ != 0 && requestedH_ != 0 && w == requestedW_ && h == requestedH_) sizeHonored_ = true;
#ifdef DISTRHO_OS_LINUX
        // Tiling-WM (Wayland/Hyprland) clamp detection — STANDALONE ONLY, and only for a window we've NEVER
        // been able to size. A size back different from what we asked means the compositor owns geometry, so
        // we latch and stop driving setSize. Linux-only; Win/macOS honour it. But a DAW host also owns the
        // editor window and treats setSize as a resize *request* (VST3 resize_view / CLAP request_resize),
        // echoing back the size it granted here — which legitimately differs from what we asked (e.g. the
        // host's restored editor frame at embed). Reading that as a compositor takeover would freeze the
        // window at its embed size, so a second instance can't grow it and SystemGrid's fitZoom shrinks the
        // tiles instead. In a DAW we keep driving setSize and let fitZoom cover a declined grow. The
        // !sizeHonored_ guard is the other half: a floating window (which HAS honoured our sizes — zoom grows
        // it) must not latch when the compositor spuriously shrinks it on a move; the UI re-asserts the zoom
        // size instead. Only a genuinely tiled window — which never matches a request — still latches.
        if (!wmControlled_ && getWindow().getApp().isStandalone() && !sizeHonored_ && requestedW_ != 0 &&
            requestedH_ != 0 && (w != requestedW_ || h != requestedH_))
            wmControlled_ = true;
#endif
        // Tell the UI the display resized so it re-lays-out (the grid/menu read Dimensions.window at render
        // time; nothing else would trigger a re-render on a user drag / WM tile).
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[2] = {JS_NewUint32(ctx, w), JS_NewUint32(ctx, h)};
            jsEngine.emit("resize", 2, args);
            JS_FreeValue(ctx, args[0]);
            JS_FreeValue(ctx, args[1]);
        }
    }

    bool onKeyboard(const KeyboardEvent& ev) override {
        UI::onKeyboard(ev); // base → LVGL keypad indev (menu arrow nav / Enter)
        if (JSContext* ctx = jsEngine.getContext()) {
            // key is the unshifted code point (DPF gives 'a' for the A key regardless of Shift); pass mod so
            // the prompt text-input can apply Shift → uppercase itself. @see kModifierShift.
            JSValue args[3] = {JS_NewUint32(ctx, ev.key), JS_NewBool(ctx, ev.press), JS_NewUint32(ctx, ev.mod)};
            jsEngine.emit("key", 3, args); // the App's Esc handler + any key policy reads this
            for (JSValue& v : args) JS_FreeValue(ctx, v);
        }
        return true;
    }

    bool onMouse(const MouseEvent& ev) override {
        // Click-to-focus: an embedded plugin child window doesn't get keyboard focus on its own on Windows
        // (pugl never SetFocus()es it, and hosts like Renoise deliver keys to the focused window rather than
        // forwarding effEditKeyDown). Grab keyboard focus on any press so onKeyboard starts receiving keys.
        if (ev.press) getWindow().focus();
        UI::onMouse(ev); // base → LVGL pointer indev (tile focus / onClick)
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[4] = {JS_NewUint32(ctx, ev.button), JS_NewBool(ctx, ev.press),
                               JS_NewFloat64(ctx, ev.pos.getX()), JS_NewFloat64(ctx, ev.pos.getY())};
            jsEngine.emit("mouse", 4, args);
            for (JSValue& v : args) JS_FreeValue(ctx, v);
        }
        return true;
    }

    // Desktop wheel → scroll the hit-tested scrollable ancestor (the menu). Swallow otherwise, so the
    // base's encoder path can't shuffle group focus across widgets. Ported from legacy PluginUI.
    bool onScroll(const ScrollEvent& ev) override {
        lv_obj_t* const scr = lv_screen_active();
        if (scr) {
            lv_point_t p = {static_cast<int32_t>(ev.pos.getX()), static_cast<int32_t>(ev.pos.getY())};
            lv_obj_t* hit = lv_indev_search_obj(scr, &p);
            const int32_t step = 24;
            const int32_t dy = static_cast<int32_t>(ev.delta.getY() * step);
            const int32_t dx = static_cast<int32_t>(ev.delta.getX() * step);
            for (lv_obj_t* it = hit; it; it = lv_obj_get_parent(it)) {
                if (!lv_obj_has_flag(it, LV_OBJ_FLAG_SCROLLABLE)) continue;
                const bool vScroll = (dy != 0) && (lv_obj_get_scroll_top(it) + lv_obj_get_scroll_bottom(it) > 0);
                const bool hScroll = (dx != 0) && (lv_obj_get_scroll_left(it) + lv_obj_get_scroll_right(it) > 0);
                if (vScroll || hScroll) {
                    lv_obj_scroll_by_bounded(it, hScroll ? -dx : 0, vScroll ? dy : 0, LV_ANIM_OFF);
                    return true;
                }
            }
        }
        return true;
    }

    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginUI)
};

namespace {
// Per-context routing for the window-op hooks. Each plugin instance owns its own control-plane JSContext
// (PluginDSP::host_, reached via useExternalHost), and a DAW can have several instances — several editors —
// open at once. A single process-global editor pointer would misroute one instance's window calls into
// whichever editor opened last, and go dead as soon as that one closed. So each __rp_* C-function instead
// carries a stable per-context slot through its QuickJS func-data (retroplug::ContextTargetTable, the
// JS_NewCFunctionData mechanism TjsHostRuntime::bindRpcSend uses) and follows it to the editor at call
// time, needing no global. The hooks are bound once and outlive the editor on the persistent context, so
// editor open/close just re-points / nulls the slot; the slots are owned per-context by g_windowTargets
// (freed at process exit — no per-instance leak, and a live editor is never reached through a stale context).
retroplug::ContextTargetTable<PluginUI> g_windowTargets;

// The editor a hook was bound with, or null between / after editor sessions (callers no-op).
PluginUI* windowUiFromData(JSContext* ctx, JSValue* funcData) {
    return retroplug::contextTargetFromData<PluginUI>(ctx, funcData);
}

// Background render jobs, PROCESS-GLOBAL so a render survives its editor window closing (each job spins its
// own RenderHost + Engine — nothing here references the live plugin). Jobs are tagged with the editor
// (PluginUI*) that started them, so a multi-instance host only shows its own; the static's destructor
// cancels + joins any still-running thread at process exit.
retroplug::RenderJobRegistry g_renderJobs;

// __rp_startRender(systemId, specJson): kick off a background render of a fresh system (the UI has already
// snapshotted the live SRAM/savestate into the spec's sav/state path). Returns the job id.
JSValue jsStartRender(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (!ui || argc < 2) return JS_NewInt64(ctx, 0);
    std::uint32_t systemId = 0;
    JS_ToUint32(ctx, &systemId, argv[0]);
    const char* spec = JS_ToCString(ctx, argv[1]);
    retroplug::RenderJobRegistry::JobId id =
        g_renderJobs.start(ui, systemId, spec ? std::string(spec) : std::string());
    if (spec) JS_FreeCString(ctx, spec);
    return JS_NewInt64(ctx, static_cast<std::int64_t>(id));
}

// __rp_cancelRender(jobId): request cooperative cancellation of a running render.
JSValue jsCancelRender(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue*) {
    if (argc >= 1) {
        std::int64_t id = 0;
        JS_ToInt64(ctx, &id, argv[0]);
        g_renderJobs.cancel(static_cast<retroplug::RenderJobRegistry::JobId>(id));
    }
    return JS_UNDEFINED;
}

// __rp_dismissRenderJob(jobId): drop a finished job (the UI dismisses a completed/errored badge).
JSValue jsDismissRenderJob(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue*) {
    if (argc >= 1) {
        std::int64_t id = 0;
        JS_ToInt64(ctx, &id, argv[0]);
        g_renderJobs.dismiss(static_cast<retroplug::RenderJobRegistry::JobId>(id));
    }
    return JS_UNDEFINED;
}

// __rp_getRenderJobs(): this editor's render jobs as [{ id, systemId, state, renderedMs, message }], for the
// per-frame tile poll. state is "rendering" | "done" | "error" | "cancelled".
JSValue jsGetRenderJobs(JSContext* ctx, JSValueConst, int, JSValueConst*, int, JSValue* funcData) {
    JSValue arr = JS_NewArray(ctx);
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (!ui) return arr;
    std::vector<retroplug::RenderJobRegistry::Status> jobs = g_renderJobs.snapshot(ui);
    for (std::uint32_t i = 0; i < jobs.size(); ++i) {
        const auto& s = jobs[i];
        JSValue o = JS_NewObject(ctx);
        JS_SetPropertyStr(ctx, o, "id", JS_NewInt64(ctx, static_cast<std::int64_t>(s.id)));
        JS_SetPropertyStr(ctx, o, "systemId", JS_NewUint32(ctx, s.systemId));
        JS_SetPropertyStr(ctx, o, "state", JS_NewString(ctx, retroplug::RenderJobRegistry::stateName(s.state)));
        JS_SetPropertyStr(ctx, o, "renderedMs", JS_NewFloat64(ctx, s.renderedMs));
        JS_SetPropertyStr(ctx, o, "message", JS_NewString(ctx, s.message.c_str()));
        JS_SetPropertyUint32(ctx, arr, i, o);
    }
    return arr;
}

JSValue jsSetWindowSize(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (ui && argc >= 2) {
        std::uint32_t w = 0, h = 0;
        JS_ToUint32(ctx, &w, argv[0]);
        JS_ToUint32(ctx, &h, argv[1]);
        ui->requestWindowSize(w, h);
    }
    return JS_UNDEFINED;
}

JSValue jsIsWindowSizeControlled(JSContext* ctx, JSValueConst, int, JSValueConst*, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    return JS_NewBool(ctx, ui && ui->isWindowSizeControlled());
}

// __rp_quitWindow(): close the standalone for real after the unsaved-changes prompt resolves.
JSValue jsQuitWindow(JSContext* ctx, JSValueConst, int, JSValueConst*, int, JSValue* funcData) {
    if (PluginUI* ui = windowUiFromData(ctx, funcData)) ui->requestQuit();
    return JS_UNDEFINED;
}

// __rp_openPath(path): reveal a folder/file in the OS file manager (Settings -> Open Settings Folder).
JSValue jsOpenPath(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (ui && argc >= 1) {
        const char* path = JS_ToCString(ctx, argv[0]);
        ui->openPath(path ? path : "");
        if (path) JS_FreeCString(ctx, path);
    }
    return JS_UNDEFINED;
}

// __rp_setWindowTitle(title): set the standalone OS window title (the UI composes it from version + project).
JSValue jsSetWindowTitle(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (ui && argc >= 1) {
        const char* title = JS_ToCString(ctx, argv[0]);
        ui->setWindowTitle(title ? title : "");
        if (title) JS_FreeCString(ctx, title);
    }
    return JS_UNDEFINED;
}

// __rp_openFileBrowser(title, patterns, saving, defaultName, startDir, directory): open the native OS
// dialog. patterns is a whitespace-separated glob list; startDir (optional, 5th arg) is the folder to open
// in; directory (optional, 6th arg) picks a FOLDER instead of a file. The result comes back later via the
// UI's uiFileBrowserSelected override.
JSValue jsOpenFileBrowser(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv, int, JSValue* funcData) {
    PluginUI* ui = windowUiFromData(ctx, funcData);
    if (ui && argc >= 4) {
        const char* title       = JS_ToCString(ctx, argv[0]);
        const char* patterns    = JS_ToCString(ctx, argv[1]);
        const int   saving      = JS_ToBool(ctx, argv[2]);
        const char* defaultName = JS_ToCString(ctx, argv[3]);
        const char* startDir    = (argc >= 5) ? JS_ToCString(ctx, argv[4]) : nullptr;
        const int   directory   = (argc >= 6) ? JS_ToBool(ctx, argv[5]) : 0;
        ui->requestFileBrowser(title ? title : "", patterns ? patterns : "", saving == 1,
                               defaultName ? defaultName : "", startDir ? startDir : "", directory == 1);
        if (title) JS_FreeCString(ctx, title);
        if (patterns) JS_FreeCString(ctx, patterns);
        if (defaultName) JS_FreeCString(ctx, defaultName);
        if (startDir) JS_FreeCString(ctx, startDir);
    }
    return JS_UNDEFINED;
}

void installWindowSizeHooks(JSContext* ctx, PluginUI* ui) {
    if (!ctx) return;
    auto* slot = g_windowTargets.slotFor(ctx);
    slot->ptr  = ui;
    // The hooks live on the persistent control-plane context and outlive this editor session; bind them
    // once per context, then editor open/close only re-points the slot (above / clearWindowSizeHooks).
    if (hasGlobalFunction(ctx, "__rp_setWindowSize")) return;

    JSValue g = JS_GetGlobalObject(ctx);
    auto bind = [&](const char* name, JSCFunctionData* fn, int length) {
        JSValue data = retroplug::packContextTarget(ctx, slot);
        JS_SetPropertyStr(ctx, g, name, JS_NewCFunctionData(ctx, fn, length, 0, 1, &data));
        JS_FreeValue(ctx, data);
    };
    bind("__rp_setWindowSize", jsSetWindowSize, 2);
    bind("__rp_isWindowSizeControlled", jsIsWindowSizeControlled, 0);
    // Always bound: requestFileBrowser picks pfd or DPF's own browser at call time, and DPF's needs no
    // helper — so "File Dialogs: OS Native" gives a real OS dialog on every desktop host, not just ones
    // with zenity/kdialog. (The DAW-hosted-with-no-helper corner is the one weak spot, no worse than before.)
    bind("__rp_openFileBrowser", jsOpenFileBrowser, 6);
    bind("__rp_quitWindow", jsQuitWindow, 0);
    bind("__rp_openPath", jsOpenPath, 1);
    bind("__rp_setWindowTitle", jsSetWindowTitle, 1);
    bind("__rp_startRender", jsStartRender, 2);
    bind("__rp_cancelRender", jsCancelRender, 1);
    bind("__rp_dismissRenderJob", jsDismissRenderJob, 1);
    bind("__rp_getRenderJobs", jsGetRenderJobs, 0);
    JS_FreeValue(ctx, g);
}

void clearWindowSizeHooks(JSContext* ctx, PluginUI* ui) {
    g_windowTargets.clear(ctx, ui);
}
} // namespace

UI* createUI() { return new PluginUI(); }

END_NAMESPACE_DISTRHO
