#include "GreenfieldUiHarness.hpp"

#include <cstdint>

extern "C" {
    #include <quickjs.h>
}

#include "BackendRpcRegistration.hpp"

// The embedded greenfield UI bundle (QuickJS bytecode), generated by retroplug-greenfield-ui-bundle
// into build/native-greenfield/ui-bundle_data.c with the gfui_ prefix, and linked into the test binary.
extern "C" {
    extern const std::uint8_t  gfui_ui_bundle[];
    extern const std::uint32_t gfui_ui_bundle_size;
}

namespace rpuigf {

GreenfieldUiHarness::GreenfieldUiHarness(std::uint32_t width, std::uint32_t height)
    : core_(width, height) {}

GreenfieldUiHarness::~GreenfieldUiHarness() {
    // server_/transport_ reference the engine's JS context; reset them before core_ tears the engine
    // down (member destruction is reverse-declaration order, which already does this — explicit for
    // clarity).
    server_.reset();
    transport_.reset();
}

bool GreenfieldUiHarness::boot() {
    if (booted_) return true;
    if (!core_.init()) return false;

    LvglJsEngine& engine = core_.engine();
    JSContext* ctx = engine.getContext();
    if (!ctx) return false;

    // rpcpp server over the QuickJS object codec (marshals request/response as live JS objects against
    // ctx — nothing serialized). The transport's async sink is unused (the client is synchronous).
    transport_ = std::make_unique<rpcpp::QuickJSTransport>(ctx, [](JSContext*, JSValue) {});
    server_    = std::make_unique<BackendRpcServer>(service_, *transport_, rpcpp::QuickJSCodec{ctx});
    registerBackendRpcMethods(*server_);

    // globalThis[Symbol.for("plugin")] = { __rpcSend } — the namespace realBackend.ts targets.
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue sym    = JS_NewSymbol(ctx, "plugin", /*is_global*/ 1);
    JSAtom atom    = JS_ValueToAtom(ctx, sym);
    JSValue ns     = JS_NewObjectProto(ctx, JS_NULL);
    BackendRpcServer* srv = server_.get();
    engine.host().bindRpcSend(ns, [srv](JSContext* sctx, JSValueConst req) -> JSValue {
        auto out = srv->processMessage(req);
        if (!out) return JS_NULL;        // notification / no reply
        return out->materialize(sctx);   // owned; handed back to JS synchronously
    });
    JS_DefinePropertyValue(ctx, global, atom, ns, JS_PROP_C_W_E);
    JS_FreeAtom(ctx, atom);
    JS_FreeValue(ctx, sym);
    JS_FreeValue(ctx, global);

    // Eval the greenfield UI bundle (the React app + realBackend), then bind the display + mount React.
    if (engine.evalModuleBytecode(gfui_ui_bundle, gfui_ui_bundle_size) != 0) return false;
    engine.attachDisplay();

    booted_ = true;
    return true;
}

} // namespace rpuigf
