// retroplug-cli — the txiki/QuickJS host for RetroPlug's embedded TypeScript.
//
// Two entry points, both embedding the same runtime + HarnessRpcService:
//   retroplug-cli --test <bundle.js>   run a TS test module (TAP output)
//   retroplug-cli <args...>            run the embedded end-user CLI app
//
// The CLI app logic lives in packages/cli, bundled to QuickJS bytecode and
// embedded here (the no-Node end-user path). Set RETROPLUG_CLI_BUNDLE_PATH to a
// built bundle .js to load it from source for dev iteration (mirrors the
// plugin's RETROPLUG_BUNDLE_PATH).

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include "TestHarness.hpp"

#ifdef RETROPLUG_CLI_BUNDLE_EMBEDDED
extern "C" {
    // Generated by tjsc — see CMakeLists.txt CLI bundle pipeline. The end-user
    // CLI module (packages/cli) compiled to QuickJS bytecode.
    extern const std::uint8_t  cli_bundle[];
    extern const std::uint32_t cli_bundle_size;
}
#endif

int main(int argc, char** argv) try {
    // `--test <bundle.js>`: run a TS test module in the embedded runtime (TAP).
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--test") == 0) {
            if (i + 1 >= argc) {
                std::fprintf(stderr, "--test requires a JS file argument\n");
                return 2;
            }
            TestHarness harness;
            return harness.runFile(argv[i + 1]);
        }
    }

    // Default: run the embedded end-user CLI app. The user args (argv[1..]) are
    // passed through to JS via getArgv(); the bundle reports its exit code.
    const std::vector<std::string> args(argv + 1, argv + argc);
    TestHarness harness;

    if (const char* devPath = std::getenv("RETROPLUG_CLI_BUNDLE_PATH");
        devPath && *devPath)
        return harness.runBundleFromFile(devPath, args);

#ifdef RETROPLUG_CLI_BUNDLE_EMBEDDED
    return harness.runBundle(cli_bundle, cli_bundle_size, args);
#else
    std::fprintf(stderr,
        "no embedded CLI bundle (built without Node); set RETROPLUG_CLI_BUNDLE_PATH "
        "to a built bundle .js, or use --test\n");
    return 2;
#endif
} catch (const std::exception& e) {
    std::fprintf(stderr, "error: %s\n", e.what());
    return 1;
}
