#include "UiTestHarness.hpp"

#include <cstdlib>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <unordered_set>

// LVGL is built in custom-global mode (LV_GLOBAL_CUSTOM): the application must
// provide lv_global_default(). In the plugin DPF's LVGLWidget supplies a
// per-instance one (deps/dpf-widgets/generic/LVGL.cpp); headless we need a
// single process-wide instance. Zero-initialized like DPF's calloc; lv_init()
// populates it. Leaked intentionally (process-lifetime singleton).
extern "C" lv_global_t* lv_global_default(void) {
    static lv_global_t* g = static_cast<lv_global_t*>(std::calloc(1, sizeof(lv_global_t)));
    return g;
}

#include "PluginJsBridge.hpp"
#include "system/MemoryType.hpp"    // rp::MemoryType / AccessType / MemoryAccessor
#include "system/RomFormat.hpp"
#include "system/SystemBase.hpp"
#include "system/SystemTypes.hpp"   // AudioBlockInfo
#include "transport/CommandQueue.hpp"
#include "system/sameboy/SameBoyConfig.hpp"
#include "system/sameboy/SameBoySystem.hpp"
#include "project/ProjectSerialization.hpp"

extern "C" {
    #include <quickjs.h>
}

// lv_binding_js internals (global widget registry + root window + PNG encoder).
#include "native/core/basic/comp.hpp"          // comp_map, BasicComponent, ECOMP_TYPE
#include "native/components/component.hpp"      // GetWindowInstance()
#include "native/core/img/png/lodepng.h"

#include "../../cli/HostPath.hpp"   // rpcli::resolveHostPath (/tmp -> %TEMP%\retroplug on Windows)

// The embedded React UI bundle (QuickJS bytecode), generated by ui-regenerate
// into build/ui/bundle_data.c and linked into this test binary.
extern "C" {
    extern const uint8_t  ui_bundle[];
    extern const uint32_t ui_bundle_size;
}

namespace rpui {

namespace {

// The active harness, for the static JS / LVGL trampolines (single runtime,
// single-threaded, one harness at a time — same recovery pattern as
// cli/TestHarness.cpp's g_activeImpl).
UiTestHarness* g_active = nullptr;

// Simulated millisecond clock. Advanced by pump() so LVGL timers fire
// deterministically without wall-clock dependence.
std::uint32_t g_tickMs = 0;
std::uint32_t tickCb() { return g_tickMs; }

// No-op flush: the draw buffer already holds the rendered pixels; there's no
// GL texture / window to push to. Just acknowledge so LVGL continues.
void flushCb(lv_display_t* disp, const lv_area_t*, uint8_t*) {
    lv_display_flush_ready(disp);
}

// Keypad indev: pop one queued LVGL key code per read (PRESSED while queued,
// then RELEASED), like dpf-widgets' keyBuffer. Drives menu focus-group nav.
void keypadReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* h = static_cast<UiTestHarness*>(lv_indev_get_driver_data(indev));
    if (h && !h->keyQueue().empty()) {
        data->state = LV_INDEV_STATE_PRESSED;
        data->key   = h->keyQueue().front();
        h->keyQueue().pop_front();
        data->continue_reading = !h->keyQueue().empty();
    } else {
        data->state = LV_INDEV_STATE_RELEASED;
    }
}

// Pointer indev: report the harness's synthetic cursor position + button state.
void pointerReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* h = static_cast<UiTestHarness*>(lv_indev_get_driver_data(indev));
    if (!h) { data->state = LV_INDEV_STATE_RELEASED; return; }
    data->point = h->mousePos();
    data->state = h->mouseDown() ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
}

// Collect every live lv_obj under `o` (depth-first). The QUERIES below walk the
// live tree rather than the global comp_map: lv_binding_js can leave a freed
// component in comp_map after an unmount (e.g. the Menu -> AboutPanel swap), and
// dereferencing its dangling instance crashes. The tree only holds live objects.
void collectTree(lv_obj_t* o, std::vector<lv_obj_t*>& out) {
    if (!o) return;
    out.push_back(o);
    const std::uint32_t n = lv_obj_get_child_count(o);
    for (std::uint32_t i = 0; i < n; ++i) collectTree(lv_obj_get_child(o, i), out);
}

std::vector<std::uint8_t> slurpBytes(const std::string& path) {
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) throw std::runtime_error("cannot open " + path);
    const std::streamsize size = in.tellg();
    if (size <= 0) throw std::runtime_error("empty file: " + path);
    in.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> buf(static_cast<std::size_t>(size));
    if (!in.read(reinterpret_cast<char*>(buf.data()), size))
        throw std::runtime_error("read failed: " + path);
    return buf;
}

// globalThis.__rp_tagTestId(uid, name): the UI calls this from a ref so we can
// map a stable name to the rendered lv_obj. uid is lv_binding_js's component id
// (a string); comp_map resolves it to the native instance. Inert in the real
// plugin (the function isn't installed there — the UI uses optional chaining).
JSValue jsTagTestId(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (!g_active || argc < 2) return JS_UNDEFINED;
    const char* uid  = JS_ToCString(ctx, argv[0]);
    const char* name = JS_ToCString(ctx, argv[1]);
    if (uid && name) {
        auto it = comp_map.find(uid);
        if (it != comp_map.end() && it->second)
            g_active->recordTestId(name, it->second->instance);
    }
    if (uid)  JS_FreeCString(ctx, uid);
    if (name) JS_FreeCString(ctx, name);
    return JS_UNDEFINED;
}

} // namespace

bool Snapshot::isFlat() const {
    if (argb.size() < 8) return true;
    const std::uint32_t first = *reinterpret_cast<const std::uint32_t*>(argb.data());
    for (std::size_t i = 4; i + 4 <= argb.size(); i += 4)
        if (*reinterpret_cast<const std::uint32_t*>(argb.data() + i) != first)
            return false;
    return true;
}

UiTestHarness::UiTestHarness(std::uint32_t width, std::uint32_t height)
    : width_(width), height_(height) {}

UiTestHarness::~UiTestHarness() {
    // Mirror PluginUI's teardown ordering: drop the bridge, clean the widget
    // tree while the JS context is still alive (so delete events drain safely),
    // then shut the engine and tear down the LVGL display.
    bridge_.reset();
    if (lv_obj_t* scr = lv_screen_active()) lv_obj_clean(scr);
    engine_.shutdown();
    if (keypad_)  lv_indev_delete(keypad_);
    if (pointer_) lv_indev_delete(pointer_);
    if (display_) lv_display_delete(display_);
    if (group_)   lv_group_delete(group_);
    recentFiles_.reset();
    userConfig_.reset();
    if (!recentDir_.empty() || !userConfigDir_.empty()) {
        std::error_code ec;
        if (!recentDir_.empty())     std::filesystem::remove_all(recentDir_, ec);
        if (!userConfigDir_.empty()) std::filesystem::remove_all(userConfigDir_, ec);
    }
    if (g_active == this) g_active = nullptr;
}

bool UiTestHarness::boot() {
    if (booted_) return true;
    g_active = this;

    // --- LVGL: the cheap, non-GL subset of LVGLWidget::init ----------------
    lv_init(); // idempotent in v9
    lv_tick_set_cb(tickCb);

    display_ = lv_display_create(width_, height_);
    if (!display_) return false;

    const lv_color_format_t cf = lv_display_get_color_format(display_);
    const std::uint32_t stride = lv_draw_buf_width_to_stride(width_, cf);
    drawBuf_.assign(static_cast<std::size_t>(stride) * height_, 0);
    lv_display_set_buffers(display_, drawBuf_.data(), nullptr, drawBuf_.size(),
                           LV_DISPLAY_RENDER_MODE_DIRECT);
    lv_display_set_flush_cb(display_, flushCb);

    group_ = lv_group_create();
    lv_group_set_default(group_);
    keypad_ = lv_indev_create();
    lv_indev_set_type(keypad_, LV_INDEV_TYPE_KEYPAD);
    lv_indev_set_read_cb(keypad_, keypadReadCb);
    lv_indev_set_driver_data(keypad_, this);
    lv_indev_set_group(keypad_, group_);
    pointer_ = lv_indev_create();
    lv_indev_set_type(pointer_, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(pointer_, pointerReadCb);
    lv_indev_set_driver_data(pointer_, this);

    // --- JS engine + bridge + UI bundle ------------------------------------
    if (!engine_.init()) return false;

    // Match PluginUI: black screen background + root window tracks the display.
    if (lv_obj_t* scr = lv_screen_active()) {
        lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), 0);
        lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    }
    if (lv_obj_t* win = GetWindowInstance()) {
        lv_obj_set_style_width(win, lv_pct(100), 0);
        lv_obj_set_style_height(win, lv_pct(100), 0);
    }

    engine_.setParamWriteCallback([](uint32_t, float) {});
    engine_.registerParameter(0, "gain");

    installTestIdHook();

    // Recent-projects list in a per-harness temp dir so it never touches the real
    // user config. Wired into the bridge so the Recent menu + its RPCs work; the
    // onChange hook mirrors PluginUI, refetching the list in the UI on every edit.
    recentDir_ = std::filesystem::temp_directory_path() /
                 ("rp_ui_recent_" + std::to_string(reinterpret_cast<std::uintptr_t>(this)));
    std::error_code ec;
    std::filesystem::create_directories(recentDir_, ec);
    recentFiles_ = std::make_unique<RecentFiles>(recentDir_);
    recentFiles_->setOnChange([this] {
        if (engine_.getContext()) engine_.emit("recent-files-changed", 0, nullptr);
    });
    recentFiles_->start();

    // Per-harness UserConfig in a temp dir (same isolation as recentFiles_). The
    // reload callback emits "user-config-changed" exactly like PluginUI, so the
    // UI refetches and re-derives — e.g. live default-zoom propagation.
    userConfigDir_ = std::filesystem::temp_directory_path() /
                     ("rp_ui_cfg_" + std::to_string(reinterpret_cast<std::uintptr_t>(this)));
    std::filesystem::create_directories(userConfigDir_, ec);
    userConfig_ = std::make_unique<UserConfig>(userConfigDir_);
    userConfig_->setOnReload([this] {
        if (engine_.getContext()) engine_.emit("user-config-changed", 0, nullptr);
    });
    userConfig_->start();

    bridge_ = std::make_unique<PluginJsBridge>(
        engine_.host(), &project_, &commands_, &events_, &sampleRate_, &focusedSystemId_,
        userConfig_.get(), recentFiles_.get());
    // Route JS events out through this harness's display engine.
    bridge_->setEmitSink([this](const char* ch, int argc, JSValueConst* argv) {
        engine_.emit(ch, argc, argv);
    });

    // Stub the file browser so open*Browser RPCs succeed headlessly. The actual
    // chosen path is injected by the test via selectFile() -> onFileBrowserSelected.
    // Count the opens so a test can assert a browser did (or didn't) pop.
    browserOpenCount_ = 0;
    bridge_->setOpenFileBrowserCallback(
        [this](const char*, bool, const char*, const char*, const char*) { ++browserOpenCount_; });

    // Record standalone-quit requests so a UI test can assert the unsaved-changes
    // modal's Discard/Save → quit path fired.
    bridge_->setQuitCallback([this] { quitRequested_ = true; });

    if (engine_.evalModuleBytecode(ui_bundle, ui_bundle_size) != 0) return false;

    booted_ = true;
    return true;
}

void UiTestHarness::installTestIdHook() {
    JSContext* ctx = engine_.getContext();
    if (!ctx) return;
    JSValue g = JS_GetGlobalObject(ctx);
    JS_SetPropertyStr(ctx, g, "__rp_tagTestId",
                      JS_NewCFunction(ctx, jsTagTestId, "__rp_tagTestId", 2));
    JS_FreeValue(ctx, g);
}

std::uint32_t UiTestHarness::loadRom(const std::string& path, const std::string& savPath) {
    auto bytes = slurpBytes(path);
    if (detectRomFormat(bytes) != RomFormat::SameBoy)
        throw std::runtime_error("UiTestHarness::loadRom supports SameBoy ROMs only: " + path);

    SameBoyConfig cfg;
    cfg.romPath  = path;
    cfg.model    = SameBoyModel::CgbC;
    cfg.fastBoot = true;
    // Optional cartridge SRAM image (a .sav file): seeds battery RAM so LSDj
    // boots straight to the song screen (skips the 12-15s self-test). Read as
    // raw bytes — we deliberately do NOT link the LSDj sav codec into this
    // binary (its reflect-cpp instantiations clash with the RPC layer's and
    // break listSystems serialization). A prebuilt .sav (the golden corpus,
    // ../resources/roms/lsdj/<rom>.sav) is the input instead.
    if (!savPath.empty()) cfg.sram = slurpBytes(savPath);
    auto sys = std::make_unique<SameBoySystem>(
        project_.nextSystemId(), cfg, std::move(bytes));
    sys->onActivate(sampleRate_.load());
    const SystemId id = sys->id();
    project_.adoptSystem(sys.release());
    project_.rebuildLinkGroups();
    // Focus it so the UI routes keyboard input here (PluginUI drops keys when
    // focus is 0). The DSP does this on the AddSystem command; we load directly.
    focusedSystemId_.store(id);
    notifyConfigChanged(); // UI re-queries listSystems + getFocus
    return static_cast<std::uint32_t>(id);
}

void UiTestHarness::reopenEditor() {
    engine_.detachDisplay();
    pump(10);                 // flush LVGL async deletes from the unmount
    engine_.reattachDisplay();
    pump(30);                 // let the re-mounted React tree settle
}

void UiTestHarness::notifyConfigChanged() {
    if (engine_.getContext()) engine_.emit("config-changed", 0, nullptr);
}

void UiTestHarness::notifyProjectLoaded() {
    if (engine_.getContext()) engine_.emit("project-loaded", 0, nullptr);
}

bool UiTestHarness::loadProject(const std::string& path) {
    return bridge_ && bridge_->loadProjectFromPath(rpcli::resolveHostPath(path));
}

void UiTestHarness::requestCloseConfirm() {
    if (bridge_) bridge_->requestCloseConfirm();   // emits "confirm-close"
}

void UiTestHarness::selectFile(const std::string& path) {
    if (bridge_) bridge_->onFileBrowserSelected(rpcli::resolveHostPath(path).c_str());
}

void UiTestHarness::writeFile(const std::string& path,
                              const std::vector<std::uint8_t>& bytes) {
    const std::string out = rpcli::resolveHostPath(path);
    std::ofstream f(out, std::ios::binary | std::ios::trunc);
    if (!f.write(reinterpret_cast<const char*>(bytes.data()),
                 static_cast<std::streamsize>(bytes.size())).good())
        throw std::runtime_error("UiTestHarness::writeFile failed: " + out);
}

void UiTestHarness::writeProjectJson(const std::string& path,
                                     const std::string& romPath,
                                     std::uint8_t zoom,
                                     const std::string& savPath) {
    // Schema-correct thin project (one path-only SameBoy system) via the real
    // serializer — hand-authored JSON is too brittle against reflect-cpp.
    // Store ABSOLUTE asset paths, as a real file-dialog load does — a bare
    // relative like "../resources/x.gb" would otherwise be resolved against the
    // .rplg's own dir by loadProjectFromPath's project-relative path handling.
    auto absPath = [](const std::string& p) {
        std::error_code ec;
        std::string a = std::filesystem::weakly_canonical(rpcli::resolveHostPath(p), ec).string();
        return a.empty() ? rpcli::resolveHostPath(p) : a;
    };
    SameBoyConfig sb;
    sb.romPath = absPath(romPath);
    if (!savPath.empty()) sb.savPath = absPath(savPath);
    ProjectConfig cfg;
    cfg.settings.zoom = zoom;
    cfg.systems.push_back(sb);
    const std::string json = projectConfigToJsonFile(cfg);
    const std::string out = rpcli::resolveHostPath(path);
    std::ofstream f(out, std::ios::binary | std::ios::trunc);
    if (!f.write(json.data(), static_cast<std::streamsize>(json.size())).good())
        throw std::runtime_error("UiTestHarness::writeProjectJson failed: " + out);
}

void UiTestHarness::seedRecent(const std::string& path, const std::string& name) {
    if (recentFiles_) recentFiles_->add(rpcli::resolveHostPath(path), name);   // fires onChange -> refetch
}

void UiTestHarness::pump(int iterations) {
    constexpr std::uint32_t kFrames = 1024; // ~23ms at 44.1kHz
    if (scratchL_.size() < kFrames) { scratchL_.resize(kFrames); scratchR_.resize(kFrames); }
    float* outs[2] = { scratchL_.data(), scratchR_.data() };
    for (int i = 0; i < iterations; ++i) {
        // Drain UI->DSP commands before processing, like PluginDSP::run. This is
        // how RPC button presses (keyboard input routed through the UI) reach the
        // emulator. We only need ButtonPress headless (ROMs are loaded directly,
        // not via the LoadRom/AddSystem commands).
        Command cmd;
        bool configMutated = false;
        bool projectLoaded = false;
        while (commands_.tryPop(cmd)) {
            if (cmd.kind == Command::Kind::ButtonPress) {
                const auto& bp = cmd.payload.buttonPress;
                if (SystemBase* sys = project_.findSystem(bp.systemId))
                    sys->pressButton(bp.button, bp.down);
            } else if (cmd.kind == Command::Kind::LoadProject) {
                // Mirror PluginDSP's LoadProject handler so a project committed
                // by the RPC service (after relinking) actually applies in-harness.
                ProjectConfig* config = cmd.payload.loadProject.config;
                if (config) {
                    const SystemId first = project_.loadFromConfig(*config);
                    focusedSystemId_.store(first);
                    project_.rebuildLinkGroups();
                    project_.onActivate(sampleRate_.load());
                    delete config;
                    // A whole-project replace: emit ProjectLoaded so the UI
                    // re-seeds its settings too (not just structure).
                    projectLoaded = true;
                }
            } else if (cmd.kind == Command::Kind::LoadRom) {
                // Mirror PluginDSP's LoadRom so menu-driven ROM loads (e.g. the
                // embedded loadMgb) apply in headless UI tests: adopt into an
                // empty project, else replace the focused system. The incoming
                // system is already onActivate'd by the RPC service.
                SystemBase* incoming = cmd.payload.loadRom.newSystem;
                if (incoming) {
                    if (project_.systems().empty()) {
                        project_.adoptSystem(incoming);
                        focusedSystemId_.store(incoming->id());
                    } else {
                        SystemId target = focusedSystemId_.load();
                        if (!project_.findSystem(target))
                            target = project_.systems().front()->id();
                        delete project_.swapSystem(target, incoming);
                        focusedSystemId_.store(incoming->id());
                    }
                    project_.rebuildLinkGroups();
                    configMutated = true;
                }
            } else if (cmd.kind == Command::Kind::SetZoom) {
                // Mirror PluginDSP's SetZoom: update the replica only, NO
                // config-changed echo — the UI owns zoom and edits it
                // optimistically. 0..6 (0 = inherit the user default).
                const std::uint8_t z = cmd.payload.setZoom.zoom;
                if (z <= 6) project_.config().settings.zoom = z;
            } else if (cmd.kind == Command::Kind::SetLayout) {
                // Mirror PluginDSP's SetLayout: replica only, no echo.
                project_.config().settings.layout = cmd.payload.setLayout.layout;
            } else if (cmd.kind == Command::Kind::SetMidiRouting) {
                // Mirror PluginDSP's SetMidiRouting: replica only, no echo.
                project_.config().settings.midiRouting = cmd.payload.setMidiRouting.routing;
            } else if (cmd.kind == Command::Kind::SetAudioRouting) {
                // Mirror PluginDSP's SetAudioRouting: replica only, no echo.
                project_.config().settings.audioRouting = cmd.payload.setAudioRouting.routing;
            } else if (cmd.kind == Command::Kind::SetFastBoot) {
                // Boolean config toggle. Mirrors PluginDSP's handler so the
                // cyclable Fast Boot menu row reflects in headless UI tests
                // (the real round-trip is DSP-thread only; here we apply it
                // directly and re-notify the UI, as with loadRom above).
                const auto& fb = cmd.payload.setFastBoot;
                if (SystemBase* sys = project_.findSystem(fb.id)) {
                    const auto cur = sys->fastBoot();
                    if (cur && *cur != fb.enabled) {
                        sys->setFastBoot(fb.enabled);
                        configMutated = true;
                    }
                }
            } else if (cmd.kind == Command::Kind::AddSystem) {
                // Mirror PluginDSP's AddSystem so the menu's "Add Instance" /
                // "Duplicate Instance" flows apply in headless UI tests. The
                // incoming system is already onActivate'd by the RPC service.
                SystemBase* incoming = cmd.payload.addSystem.newSystem;
                if (incoming) {
                    project_.adoptSystem(incoming);
                    project_.rebuildLinkGroups();
                    if (focusedSystemId_.load() == 0)
                        focusedSystemId_.store(incoming->id());
                    configMutated = true;
                }
            } else if (cmd.kind == Command::Kind::RemoveSystem) {
                // Mirror PluginDSP's RemoveSystem so "Remove Instance" applies.
                // No event-queue consumer headless — delete the released system
                // directly (the plugin hands it back to the UI thread to free).
                const SystemId removedId = cmd.payload.removeSystem.id;
                delete project_.removeSystemAndRelease(removedId);
                project_.rebuildLinkGroups();
                if (focusedSystemId_.load() == removedId) {
                    focusedSystemId_.store(project_.systems().empty()
                        ? SystemId{0} : project_.systems().front()->id());
                }
                configMutated = true;
            }
        }
        // ProjectLoaded supersedes ConfigChanged for the same drain — a load is
        // a superset re-seed, so fire only the one event (mirrors PluginUI.cpp).
        if (projectLoaded) notifyProjectLoaded();
        else if (configMutated) notifyConfigChanged();

        // Advance the emulator so framebuffers publish (no DSP thread headless),
        // matching the per-tick emulator advance the plugin's audio thread does.
        std::fill_n(scratchL_.data(), kFrames, 0.0f);
        std::fill_n(scratchR_.data(), kFrames, 0.0f);
        AudioBlockInfo info{ kFrames, sampleRate_.load(), 120.0, 0.0, false };
        project_.onProcess(info, outs);

        g_tickMs += 23; // keep UI tick roughly in step with the audio block
        if (bridge_) {
            bridge_->pumpAsync();
            bridge_->pumpMemorySnapshots();
        }
        if (engine_.getContext()) engine_.emit("frame", 0, nullptr);
        engine_.tick();
        lv_timer_handler();
    }
}

Snapshot UiTestHarness::snapshot() {
    Snapshot out;
    lv_obj_t* scr = lv_screen_active();
    if (!scr) return out;
    lv_draw_buf_t* snap = lv_snapshot_take(scr, LV_COLOR_FORMAT_ARGB8888);
    if (!snap) return out;
    out.width  = snap->header.w;
    out.height = snap->header.h;
    const std::size_t bytes = static_cast<std::size_t>(out.width) * out.height * 4;
    out.argb.assign(snap->data, snap->data + bytes);
    lv_draw_buf_destroy(snap);
    return out;
}

bool UiTestHarness::snapshotPng(const std::string& path) {
    Snapshot s = snapshot();
    if (s.argb.empty()) return false;
    std::vector<unsigned char> rgb(static_cast<std::size_t>(s.width) * s.height * 3);
    for (std::size_t i = 0, n = static_cast<std::size_t>(s.width) * s.height; i < n; ++i) {
        rgb[i * 3 + 0] = s.argb[i * 4 + 2]; // B,G,R,A -> R,G,B
        rgb[i * 3 + 1] = s.argb[i * 4 + 1];
        rgb[i * 3 + 2] = s.argb[i * 4 + 0];
    }
    return lodepng_encode24_file(rpcli::resolveHostPath(path).c_str(), rgb.data(), s.width, s.height) == 0;
}

// Live lv_binding_js components: walk the tree, keep objects whose user_data is a
// BasicComponent currently in comp_map (so non-component LVGL objects + freed
// entries are both excluded).
static std::unordered_set<BasicComponent*> validComponentSet() {
    std::unordered_set<BasicComponent*> valid;
    for (const auto& [uid, bc] : comp_map) if (bc) valid.insert(bc);
    return valid;
}

std::vector<std::uint8_t> UiTestHarness::readMemory(std::uint32_t id, int memType) {
    SystemBase* sys = project_.findSystem(static_cast<SystemId>(id));
    if (!sys) return {};
    rp::MemoryAccessor acc = sys->getMemory(static_cast<rp::MemoryType>(memType),
                                            rp::AccessType::Read);
    if (!acc.valid() || acc.size() == 0) return {};
    return std::vector<std::uint8_t>(acc.data(), acc.data() + acc.size());
}

std::size_t UiTestHarness::widgetCount() const {
    const auto valid = validComponentSet();
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    std::size_t n = 0;
    for (lv_obj_t* o : objs) {
        auto* bc = static_cast<BasicComponent*>(lv_obj_get_user_data(o));
        if (bc && valid.count(bc)) ++n;
    }
    return n;
}

std::size_t UiTestHarness::countByType(int compType) const {
    const auto valid = validComponentSet();
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    std::size_t n = 0;
    for (lv_obj_t* o : objs) {
        auto* bc = static_cast<BasicComponent*>(lv_obj_get_user_data(o));
        if (bc && valid.count(bc) && static_cast<int>(bc->type) == compType) ++n;
    }
    return n;
}

lv_obj_t* UiTestHarness::findFirstByType(int compType) const {
    const auto valid = validComponentSet();
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    for (lv_obj_t* o : objs) {
        auto* bc = static_cast<BasicComponent*>(lv_obj_get_user_data(o));
        if (bc && valid.count(bc) && static_cast<int>(bc->type) == compType) return o;
    }
    return nullptr;
}

lv_obj_t* UiTestHarness::findByText(const std::string& text) const {
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    for (lv_obj_t* o : objs) {
        if (!lv_obj_check_type(o, &lv_label_class)) continue; // live label: safe to read
        const char* t = lv_label_get_text(o);
        if (t && text == t) return o;
    }
    return nullptr;
}

lv_obj_t* UiTestHarness::findByTextContaining(const std::string& substr) const {
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    for (lv_obj_t* o : objs) {
        if (!lv_obj_check_type(o, &lv_label_class)) continue;
        const char* t = lv_label_get_text(o);
        if (t && std::string(t).find(substr) != std::string::npos) return o;
    }
    return nullptr;
}

lv_obj_t* UiTestHarness::findByTestId(const std::string& name) const {
    auto it = testIds_.find(name);
    if (it == testIds_.end()) return nullptr;
    // Only return it if still live (its slot may have unmounted).
    std::vector<lv_obj_t*> objs;
    collectTree(lv_screen_active(), objs);
    for (lv_obj_t* o : objs) if (o == it->second) return o;
    return nullptr;
}

lv_obj_t* UiTestHarness::focusedObject() const {
    if (!keypad_) return nullptr;
    lv_group_t* g = lv_indev_get_group(keypad_); // the menu's group once claimed
    return g ? lv_group_get_focused(g) : nullptr;
}

WidgetInfo UiTestHarness::widgetInfo(lv_obj_t* obj) const {
    WidgetInfo wi;
    if (!obj) return wi;
    wi.found = true;
    lv_area_t a;
    lv_obj_get_coords(obj, &a); // absolute (screen) coordinates
    wi.x = a.x1;
    wi.y = a.y1;
    wi.width  = lv_area_get_width(&a);
    wi.height = lv_area_get_height(&a);
    wi.childCount = lv_obj_get_child_count(obj);
    if (lv_obj_check_type(obj, &lv_label_class)) {
        if (const char* t = lv_label_get_text(obj)) wi.text = t;
    }
    return wi;
}

void UiTestHarness::tapKey(std::uint32_t lvKey) {
    keyQueue_.push_back(lvKey);
    // Mirror PluginUI: also fire the JS "key" channel (press then release) for
    // handlers that live there (prompt/capture/Esc/game input). LVGL key code ->
    // DPF key code (the value runtime/lvgljs/input.ts expects).
    std::uint32_t dpf;
    switch (lvKey) {
        case LV_KEY_UP:    dpf = 0xE036; break;
        case LV_KEY_DOWN:  dpf = 0xE038; break;
        case LV_KEY_RIGHT: dpf = 0xE037; break;
        case LV_KEY_LEFT:  dpf = 0xE035; break;
        case LV_KEY_ENTER: dpf = 0x0D;   break;
        case LV_KEY_ESC:   dpf = 0x1B;   break;
        default:           dpf = lvKey;  break;
    }
    JSContext* ctx = engine_.getContext();
    auto emitKey = [&](bool press) {
        if (!ctx) return;
        JSValue args[2] = { JS_NewUint32(ctx, dpf), JS_NewBool(ctx, press) };
        engine_.emit("key", 2, args);
        JS_FreeValue(ctx, args[0]);
        JS_FreeValue(ctx, args[1]);
    };
    emitKey(true);
    pump(2);  // keypad indev: PRESSED then RELEASED through lv_timer_handler
    emitKey(false);
    pump(1);
}

void UiTestHarness::clickAt(std::int32_t x, std::int32_t y) {
    JSContext* ctx = engine_.getContext();
    auto emitMouse = [&](bool press) {
        if (!ctx) return;
        JSValue args[4] = { JS_NewUint32(ctx, 0), JS_NewBool(ctx, press),
                            JS_NewFloat64(ctx, x), JS_NewFloat64(ctx, y) };
        engine_.emit("mouse", 4, args);
        for (JSValue& v : args) JS_FreeValue(ctx, v);
    };
    mousePos_  = { x, y };
    mouseDown_ = true;
    emitMouse(true);
    pump(2);  // register the press at (x,y)
    mouseDown_ = false;
    emitMouse(false);
    pump(2);  // release -> LVGL fires CLICKED -> onClick
}

} // namespace rpui
