#!/usr/bin/env bash
set -euo pipefail

# generate.sh — one-time (idempotent) source generation for the iOS AUv3 spike.
#
# Mirrors what the desktop CMake build generates, but with host tools only so
# the Xcode iOS project can compile everything directly (no cross-compiled
# build-time helpers):
#   - applies the SameBoy per-channel audio patch (idempotent; SameBoySystem.cpp
#     calls GB_apu_set_channel_sample_callback from it)
#   - assembles the SameBoy boot ROMs via RGBDS -> generated/system/sameboy/bootroms/*.h
#   - embeds the mGB ROM -> generated/roms/mgb_rom_data.c (extern mgb_rom / mgb_rom_len)
#   - emits generated/sameboy_version.h (#define GB_VERSION "...")
#   - clones reflect-cpp (header-only; SameBoyConfig.hpp needs rfl/Literal.hpp)
#
# Prereqs: brew install rgbds   (rgbasm / rgblink / rgbgfx)

cd "$(dirname "$0")"
REPO="$(cd .. && pwd)"
SB="$REPO/deps/sameboy"
GEN="$PWD/generated"
DEPS="$PWD/.deps"
BUILD="$PWD/.build"

for t in rgbasm rgblink rgbgfx cc python3 git; do
    command -v "$t" >/dev/null || { echo "error: $t not found (RGBDS: brew install rgbds)"; exit 1; }
done
[ -f "$SB/Core/gb.h" ] || { echo "error: deps/sameboy is empty — run: git submodule update --init deps/sameboy"; exit 1; }

mkdir -p "$GEN/system/sameboy/bootroms" "$GEN/roms" "$BUILD" "$DEPS"

# --- SameBoy per-channel audio patch (same idempotent dance as cmake/sameboy.cmake)
PATCH="$REPO/cmake/patches/sameboy-per-channel-audio.patch"
if git -C "$SB" apply --reverse --check "$PATCH" 2>/dev/null; then
    echo "sameboy: per-channel patch already present"
else
    git -C "$SB" apply --check "$PATCH" || {
        echo "error: per-channel patch no longer applies to deps/sameboy"; exit 1; }
    git -C "$SB" apply "$PATCH"
    echo "sameboy: applied per-channel patch"
fi

# --- reflect-cpp headers (header-only; only rfl/Literal.hpp is consumed)
if [ ! -d "$DEPS/reflect-cpp/include" ]; then
    git clone --quiet --depth 1 --branch v0.19.0 \
        https://github.com/getml/reflect-cpp "$DEPS/reflect-cpp"
    echo "reflect-cpp: cloned v0.19.0"
fi

# --- bin2h / bin2c (symbol-compatible with cmake/bin2h.cmake + bin2c.cmake)
emit_bytes() { # <input> — hex bytes, 12 per line, to stdout
    python3 -c '
import sys
data = open(sys.argv[1], "rb").read()
for i in range(0, len(data), 12):
    print("    " + ",".join(f"0x{b:02X}" for b in data[i:i+12]) + ",")
' "$1"
}
bin2h() { # <input> <symbol> <output.h>
    local n; n=$(stat -f%z "$1")
    { printf '// auto-generated by ios/generate.sh — do not edit\n#pragma once\n#include <stddef.h>\n\n'
      printf 'static const size_t %s_len = %s;\nstatic const unsigned char %s[%s] = {\n' "$2" "$n" "$2" "$n"
      emit_bytes "$1"
      printf '};\n'; } > "$3"
}
bin2c() { # <input> <symbol> <output.c>
    local n; n=$(stat -f%z "$1")
    { printf '// auto-generated by ios/generate.sh — do not edit\n'
      printf 'const unsigned int %s_len = %s;\nconst unsigned char %s[%s] = {\n' "$2" "$n" "$2" "$n"
      emit_bytes "$1"
      printf '};\n'; } > "$3"
}

# --- boot ROMs (pb12 host helper + RGBDS; mirrors cmake/sameboy_bootroms.cmake)
cc -O2 -std=c99 -o "$BUILD/pb12" "$SB/BootROMs/pb12.c"
rgbgfx -Z -u -c embedded -o "$BUILD/SameBoyLogo.2bpp" "$SB/BootROMs/SameBoyLogo.png"
"$BUILD/pb12" < "$BUILD/SameBoyLogo.2bpp" > "$BUILD/SameBoyLogo.pb12"

for name in dmg_boot mgb_boot cgb_boot cgb0_boot cgb_boot_fast agb_boot sgb_boot sgb2_boot; do
    rgbasm --include "$BUILD" --include "$SB/BootROMs" -o "$BUILD/$name.o" "$SB/BootROMs/$name.asm"
    rgblink -x -o "$BUILD/$name.bin" "$BUILD/$name.o"
    bin2h "$BUILD/$name.bin" "$name" "$GEN/system/sameboy/bootroms/$name.h"
    echo "bootrom: $name.h"
done

# --- embedded mGB ROM (EmbeddedRoms.hpp expects extern mgb_rom / mgb_rom_len)
bin2c "$REPO/resources/roms/mGB.gb" mgb_rom "$GEN/roms/mgb_rom_data.c"
echo "rom: mgb_rom_data.c"

# --- GB_VERSION (force-included via OTHER_CFLAGS in project.yml)
VER="$(sed -n 's/^VERSION[[:space:]]*:=[[:space:]]*//p' "$SB/version.mk" | tr -d '[:space:]')"
printf '#ifndef GB_VERSION\n#define GB_VERSION "%s"\n#endif\n' "$VER" > "$GEN/sameboy_version.h"
echo "version: GB_VERSION=\"$VER\""

echo "done — now run: xcodegen (in ios/), then open RetroPlugIOS.xcodeproj"
