/*
 * RetroPlug UI — thin shell.
 *
 * Responsibilities:
 *  - DPF lifecycle (constructor sizing, uiIdle, onResize, parameterChanged,
 *    uiFileBrowserSelected).
 *  - JS engine + bridge ownership.
 *  - Forward DPF keyboard and mouse events to LVGL focus AND to JS via the
 *    "key" and "mouse" event channels. Routing decisions live in TS.
 *  - Drain DSP→UI events (free released SystemBase pointers off the audio
 *    thread) and emit a per-tick "frame" event for React.
 *
 * This file deliberately knows nothing about menus, GB button mapping, or
 * framebuffer rendering. Those live in TS (ui/EmulatorTile.tsx,
 * runtime/lvgljs/input.ts, ui/PluginUI.tsx).
 */

#include "DistrhoUI.hpp"
#include "Application.hpp"   // DGL Application (getWindow().getApp().quit() on close)
#include "ResizeHandle.hpp"
#include "GamepadManager.hpp"
#include "dpfjs/LvglJsEngine.hpp"
#include "PluginJsBridge.hpp"
#include "PluginShared.hpp"
#include "Version.hpp"
#include "dpfjs/Env.hpp"
#include "config/RecentFiles.hpp"
#include "config/UserConfig.hpp"

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <optional>
#include <string>
#include <vector>

extern "C" {
    #include "lvgl.h"
}

#include "native/core/img/png/lodepng.h"

#include "transport/EventQueue.hpp"

extern "C" {
    // Generated by tjsc — see CMakeLists.txt UI bundle pipeline. Holds the
    // UI module compiled to QuickJS bytecode.
    extern const uint8_t  ui_bundle[];
    extern const uint32_t ui_bundle_size;
}

START_NAMESPACE_DISTRHO

// Fallback for plugin formats where DSP and UI live in separate binaries (LV2).
// In-process formats (VST3/CLAP/…) link PluginDSP.cpp's strong getSharedDSPData,
// which must win over this default.
#if defined(_MSC_VER)
// MSVC has no weak symbols; emulate with /alternatename — the linker uses this
// default only when getSharedDSPData is otherwise undefined (LV2's UI binary).
// DPF uses the same idiom (choc_DynamicLibrary.h). Mangled name is x64-specific.
SharedDSPData* getSharedDSPData_weakDefault(void*) { return nullptr; }
#pragma comment(linker, "/alternatename:?getSharedDSPData@DISTRHO@@YAPEAUSharedDSPData@1@PEAX@Z=?getSharedDSPData_weakDefault@DISTRHO@@YAPEAUSharedDSPData@1@PEAX@Z")
#else
__attribute__((weak))
SharedDSPData* getSharedDSPData(void*) { return nullptr; }
#endif

// --------------------------------------------------------------------------------------------------------------------

class LVGLPluginUI : public UI
{
    float fGain = 0.0f;
    ResizeHandle fResizeHandle;
    // The display layer for this editor session. Adds LVGL/React on top of the
    // DSP-owned plugin-lifetime host (in-process, via useExternalHost) or owns
    // its own host (LV2 separate-binary UI / no DSP).
    LvglJsEngine jsEngine;
    // -> shared->jsBridge (in-process, DSP-owned + plugin-lifetime) OR
    // ownedBridge_ (LV2 fallback). Never owned via this pointer.
    PluginJsBridge* bridge = nullptr;
    retroplug::GamepadManager gamepad;
    SharedDSPData* shared = nullptr;
    // Set true once the user confirms an unsaved-changes close, so the re-entrant
    // onClose() (from requestStandaloneQuit) allows the window to close.
    bool allowClose_ = false;
    // -> shared->userConfig (in-process, DSP-owned) OR &*ownedUserConfig_ (LV2).
    // uiIdle pumps its file-watch reloads on the UI thread.
    UserConfig* userConfig_ = nullptr;
    // LV2 / no-DSP fallback: the editor owns the runtime bits the DSP would own
    // in-process. Declared AFTER jsEngine so they destruct FIRST: stop the
    // watcher + drop the bridge before the JS context (jsEngine) tears down, so
    // a stray bg-thread file event can't race into a half-destroyed context.
    std::optional<UserConfig>       ownedUserConfig_;
    std::optional<RecentFiles>      ownedRecentFiles_;
    std::unique_ptr<PluginJsBridge> ownedBridge_;

    // Track the last setSize request so we can detect a tiled-WM clamp.
    // Once `wmControlled_` flips true (compositor returned a different
    // size than we asked for) we leave it true — the WM owns geometry
    // for the rest of the session.
    uint requestedW_     = 0;
    uint requestedH_     = 0;
    bool wmControlled_   = false;

    // Screenshot hook (env-var triggered). When RETROPLUG_SCREENSHOT_PATH is
    // set, periodically dump the current LVGL screen as PNG. Cadence is
    // RETROPLUG_SCREENSHOT_INTERVAL_MS (default 1000). All work happens on
    // the UI thread inside uiIdle.
    std::string screenshotPath_;
    std::chrono::milliseconds screenshotInterval_{1000};
    std::chrono::steady_clock::time_point screenshotLast_{};

    // The JACK standalone titles its window "<maker>: <name>" once, after we're
    // constructed but before the event loop. Override it to "RetroPlug v<ver>"
    // on the first uiIdle (standalone only — plugin hosts own their frame).
    bool windowTitleSet_ = false;

    void maybeWriteScreenshot()
    {
        if (screenshotPath_.empty()) return;

        const auto now = std::chrono::steady_clock::now();
        if (now - screenshotLast_ < screenshotInterval_) return;
        screenshotLast_ = now;

        lv_obj_t* screen = lv_screen_active();
        if (!screen) return;

        lv_draw_buf_t* snap = lv_snapshot_take(screen, LV_COLOR_FORMAT_ARGB8888);
        if (!snap) return;

        const uint32_t w = snap->header.w;
        const uint32_t h = snap->header.h;
        std::vector<unsigned char> rgb(static_cast<size_t>(w) * h * 3);
        // ARGB8888 in memory is B,G,R,A on little-endian; transcode to RGB.
        const uint8_t* src = snap->data;
        for (size_t i = 0, n = static_cast<size_t>(w) * h; i < n; ++i) {
            rgb[i * 3 + 0] = src[i * 4 + 2];
            rgb[i * 3 + 1] = src[i * 4 + 1];
            rgb[i * 3 + 2] = src[i * 4 + 0];
        }

        const unsigned err = lodepng_encode24_file(screenshotPath_.c_str(),
                                                   rgb.data(), w, h);
        if (err)
            d_stderr("Screenshot lodepng error %u: %s",
                     err, lodepng_error_text(err));

        lv_draw_buf_destroy(snap);
    }

    // Drain DSP→UI events:
    //  - SystemReleased: the DSP shipped a displaced SystemBase back so the
    //    UI thread can free it. Must run before anything else that could
    //    observe a stale system pointer.
    //  - ConfigChanged: project *structure* changed (add/remove/model/link).
    //    Re-emitted to JS as "config-changed"; React re-fetches its system
    //    list + focus but keeps the settings it owns.
    //  - ProjectLoaded: the whole project was replaced (setState / LoadProject).
    //    Re-emitted as "project-loaded"; React does a full re-seed including
    //    settings. Supersedes ConfigChanged for the same drain — a load is a
    //    superset re-seed, so we fire only the one JS event.
    void drainEvents()
    {
        if (!shared || !shared->events) return;
        bool configChanged = false;
        bool projectLoaded = false;
        Event ev;
        while (shared->events->tryPop(ev)) {
            switch (ev.kind) {
                case Event::Kind::SystemReleased:
                    delete ev.payload.systemReleased.system;
                    break;
                case Event::Kind::ConfigChanged:
                    configChanged = true;
                    break;
                case Event::Kind::ProjectLoaded:
                    projectLoaded = true;
                    break;
                case Event::Kind::None:
                default:
                    break;
            }
        }
        if (!jsEngine.getContext()) return;
        if (projectLoaded)
            jsEngine.emit("project-loaded", 0, nullptr);
        else if (configChanged)
            jsEngine.emit("config-changed", 0, nullptr);
    }

public:
    bool requestWindowSize(uint w, uint h)
    {
        if (w == 0 || h == 0) return wmControlled_;
        requestedW_ = w;
        requestedH_ = h;
        if (wmControlled_) return true; // don't fight the compositor
        setSize(w, h);
        return wmControlled_;
    }

    bool isWindowSizeControlled() const { return wmControlled_; }

    LVGLPluginUI()
        : UI(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT),
          fResizeHandle(this)
    {
        // Seed the requested-size baseline. The WM may already have decided
        // a different size by the time onResize fires (Hyprland tiles us
        // before the UI initializes); without this, the detection branch
        // would skip because the guard `requestedW_ != 0` was false.
        requestedW_ = DISTRHO_UI_DEFAULT_WIDTH;
        requestedH_ = DISTRHO_UI_DEFAULT_HEIGHT;

        const double scaleFactor = getScaleFactor();

        if (d_isNotEqual(scaleFactor, 1.0))
        {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
            setSize(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
        }
        else
        {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT);
        }

        if (isResizable())
            fResizeHandle.hide();

        // Generic framework feature: prefixed env var (RETROPLUG_SCREENSHOT_PATH).
        if (const char* p = dpfjs::getenvWithPrefix("SCREENSHOT_PATH"); p && *p) {
            screenshotPath_ = p;
            if (const char* iv = dpfjs::getenvWithPrefix("SCREENSHOT_INTERVAL_MS"); iv && *iv) {
                if (int ms = std::atoi(iv); ms > 0)
                    screenshotInterval_ = std::chrono::milliseconds(ms);
            }
            d_stdout("Screenshot hook enabled: %s every %lld ms",
                     screenshotPath_.c_str(),
                     static_cast<long long>(screenshotInterval_.count()));
        }

        // In-process plugin formats: reach the DSP-owned Project + plugin-lifetime
        // runtime via the shared pointer. LV2-UI (separate binary) returns nullptr.
        if (void* dspPtr = getPluginInstancePointer())
            shared = getSharedDSPData(dspPtr);

        // In-process: attach this editor session to the DSP's plugin-lifetime
        // runtime + its already-constructed rpc bridge (the context + evaluated
        // bundle persist across window close/reopen). Must switch the engine to
        // the external host BEFORE init().
        const bool inProcess = shared && shared->jsHost && shared->jsBridge;
        if (inProcess) {
            jsEngine.useExternalHost(*shared->jsHost);
            bridge      = shared->jsBridge;
            userConfig_ = shared->userConfig;
        }

        if (jsEngine.init())
        {
            jsEngine.setParamWriteCallback(
                [this](uint32_t idx, float val) {
                    editParameter(idx, true);
                    setParameterValue(idx, val);
                    editParameter(idx, false);
                });
            const auto& params = kRetroPlugDescriptor.parameters;
            for (uint32_t i = 0; i < params.size(); ++i)
                jsEngine.registerParameter(i, params[i].symbol);

            if (!inProcess) {
                // LV2 / no DSP: own the runtime bits the DSP owns in-process —
                // config watchers + the rpc bridge (with no project, so the
                // service degrades). Watchers before the bridge so it hands a
                // non-null UserConfig to the service.
                ownedUserConfig_.emplace();
                ownedRecentFiles_.emplace();
                userConfig_ = &*ownedUserConfig_;
                ownedUserConfig_->setOnReload([this]() {
                    if (jsEngine.getContext())
                        jsEngine.emit("user-config-changed", 0, nullptr);
                });
                ownedUserConfig_->start();
                ownedRecentFiles_->setOnChange([this]() {
                    if (jsEngine.getContext())
                        jsEngine.emit("recent-files-changed", 0, nullptr);
                });
                ownedRecentFiles_->start();
                ownedBridge_ = std::make_unique<PluginJsBridge>(
                    jsEngine.host(), nullptr, nullptr, nullptr, nullptr, nullptr,
                    &*ownedUserConfig_, &*ownedRecentFiles_);
                bridge = ownedBridge_.get();
            }

            // Route JS events (rpc-message frames + service string events) out
            // through this editor session's display engine. Cleared on close so
            // the DSP-owned bridge stops delivering to a gone engine.
            bridge->setEmitSink([this](const char* ch, int argc, JSValueConst* argv) {
                jsEngine.emit(ch, argc, argv);
            });

            // The bridge invokes this for any file-browser action — Open ROM,
            // Add instance, Save project, Load project. The flags map to
            // DPF's FileBrowserOptions: `saving=true` flips the dialog into
            // save mode, `defaultName` pre-fills the filename field.
            bridge->setOpenFileBrowserCallback([this](const char* title,
                                                      bool saving,
                                                      const char* defaultName,
                                                      const char* patterns,
                                                      const char* filterName) {
                FileBrowserOptions opts;
                opts.title              = title ? title : "";
                opts.saving             = saving;
                opts.defaultName        = defaultName ? defaultName : "";
                opts.fileFilterPatterns = patterns;    // nullable → no filter
                opts.fileFilterName     = filterName;  // nullable → generated label
                openFileBrowser(opts);
            });

            // Window-size plumbing: JS asks the UI to resize; the UI relays
            // to DPF. The query callback lets JS detect tiled-WM clamping.
            bridge->setWindowSizeCallback([this](uint w, uint h) {
                requestWindowSize(w, h);
            });
            bridge->setIsWindowSizeControlledQuery([this]() {
                return isWindowSizeControlled();
            });

            // Standalone close-veto: the modal asks us to actually quit once the
            // user confirms (or after a save). See onClose() below.
            bridge->setQuitCallback([this]() { requestStandaloneQuit(); });

            // Auto-load a project on startup. Useful for fast debug loops
            // and for headless agent verification of LoadProject (the
            // alternative is driving the native file dialog under Xvfb
            // which doesn't reliably work).
            if (const char* p = std::getenv("RETROPLUG_AUTOLOAD_PROJECT"); p && *p) {
                d_stdout("[PluginUI] auto-loading project: %s", p);
                bridge->loadProjectFromPath(p);
            }
            // Diagnostic shortcut for framebuffer verification: load a ROM
            // directly without going through the file dialog. Mirrors the
            // _PROJECT path above. Plain debug aid — not part of the public
            // env var surface.
            if (const char* p = std::getenv("RETROPLUG_AUTOLOAD_ROM"); p && *p) {
                d_stdout("[PluginUI] auto-loading ROM: %s", p);
                bridge->loadRomFromPath(p);
            }

            // Evaluate the UI bundle exactly once per host: a reused (persistent)
            // host from a prior editor session already has it registered
            // (module caching would no-op a re-eval anyway). attachDisplay()
            // below (re)mounts via the bundle's __rp_mountUI hook regardless.
            if (jsEngine.contextFresh())
            {
                // Generic dev override: <PREFIX>BUNDLE_PATH (RETROPLUG_BUNDLE_PATH)
                // loads the UI bundle from source instead of the embedded bytecode.
                const char* devPath = dpfjs::getenvWithPrefix("BUNDLE_PATH");
                if (devPath && *devPath)
                {
                    if (jsEngine.evalModule(devPath) != 0)
                        d_stderr("Failed to load %s", devPath);
                    else
                        d_stdout("LvglJsEngine: React UI loaded from %s", devPath);
                }
                else
                {
                    if (jsEngine.evalModuleBytecode(ui_bundle, ui_bundle_size) != 0)
                        d_stderr("Failed to load embedded UI bundle");
                    else
                        d_stdout("LvglJsEngine: React UI loaded (embedded)");
                }
            }

            // Bind this editor session's LVGL display + mount the React tree
            // (attachDisplay calls __rp_mountUI on the evaluated bundle).
            jsEngine.attachDisplay();

            // Force the LVGL screen background to black. Without this the
            // default-light theme leaks a light grey/white through any gap
            // not covered by the React tree (visible especially on tiled
            // WMs that pad the window beyond our requested size).
            if (lv_obj_t* screen = lv_screen_active()) {
                lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
                lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
            }

            // lv_binding_js's WindowInit() pins the React-tree root's
            // width/height to the LVGL display's CURRENT pixel size. That
            // captures the initial 480x432 and never updates when the
            // compositor resizes us, so React's "100%" stays bound to
            // 480x432 forever. Switch to lv_pct(100) so the root tracks
            // the active screen — which IS resized by lv_display_set_resolution.
            if (lv_obj_t* win = GetWindowInstance()) {
                lv_obj_set_style_width(win, lv_pct(100), 0);
                lv_obj_set_style_height(win, lv_pct(100), 0);
            }
        }
        else
        {
            d_stderr("Failed to initialize LvglJsEngine");
        }
    }

    ~LVGLPluginUI() override
    {
        // Stop the (possibly DSP-owned, plugin-lifetime) bridge from calling
        // back into this closing editor. The service guards each of these, so
        // clearing them makes the calls no-ops after we're gone.
        if (bridge) {
            bridge->setEmitSink({});
            bridge->setOpenFileBrowserCallback(nullptr);
            bridge->setWindowSizeCallback(nullptr);
            bridge->setIsWindowSizeControlledQuery(nullptr);
            bridge->setQuitCallback(nullptr);
        }

        // Unmount the React tree (via __rp_unmountUI) + drop the display binding
        // WHILE the JS context is still alive, leaving a persistent (DSP-owned)
        // host clean for the next editor session. Then flush the unmount's async
        // widget deletes with a valid context — otherwise the base UI destructor
        // walks the tree after member destruction (context freed) and any event
        // that fires during deletion hits lv_binding_js's FireEventToJS which
        // does `qrt->ctx` with no null check. lv_obj_clean drains any residual.
        jsEngine.detachDisplay();
        lv_timer_handler();
        if (lv_obj_t* screen = lv_screen_active())
            lv_obj_clean(screen);
    }

protected:
    void parameterChanged(uint32_t index, float value) override
    {
        if (index == 0) fGain = value;
        jsEngine.pushParameter(index, value);
    }

    // Standalone window-close veto (DPF forwards Window::onClose here only when
    // running standalone; a DAW owns the plugin lifecycle). If there are unsaved
    // changes, pop the in-app modal and veto this close; the modal calls back
    // into requestStandaloneQuit() once the user confirms / after a save.
    bool onClose() override
    {
        if (allowClose_) return true;                 // confirmed — let it close
        if (!bridge || !bridge->hasUnsavedChanges()) return true;
        bridge->requestCloseConfirm();                // emits "confirm-close" to the UI
        return false;                                 // keep the window open
    }

    // Called from the modal (via the quit RPC) to actually close after confirm.
    void requestStandaloneQuit()
    {
        allowClose_ = true;
        getWindow().close();
        getWindow().getApp().quit();
    }

    void uiIdle() override
    {
        // Standalone window title: "RetroPlug v<version>" (overrides DPF's
        // "<maker>: <name>"). Once, after the loop starts so DPF's set has run.
        if (!windowTitleSet_) {
            windowTitleSet_ = true;
            if (getWindow().getApp().isStandalone())
                getWindow().setTitle("RetroPlug v" RETROPLUG_VERSION_STRING);
        }

        drainEvents();

        // Drain the user-config watcher's dirty flag on the UI thread.
        // efsw fires on a bg thread but only flips an atomic; the parse +
        // RPC-event emit lives here.
        if (userConfig_) userConfig_->pumpReloadsOnUiThread();

        // Walk live memory subscriptions, read tear-free snapshots from the
        // DSP-published triple-buffers, hash for dedup, push "memory"
        // notifications through the rpcpp transport for any region that
        // changed since the last tick. Cheap when no subscriptions are
        // active. Runs BEFORE pumpAsync so notifications added here drain
        // in the same uiIdle tick rather than landing on the next one.
        if (bridge) bridge->pumpMemorySnapshots();

        // ROM-file watcher tick: triggers replaceRomFromPath when a watched
        // ROM's mtime has changed since the last poll. Cheap when no
        // system has the flag enabled.
        if (bridge) bridge->pumpRomWatchers();

        // SRAM auto-save tick: when the global Auto Save preference is on,
        // flush changed battery RAM to the sibling `<rom>.sav` (throttled).
        if (bridge) bridge->pumpSramAutoSave();

        // Drain the rpcpp transport's outgoing queue — async resolver
        // responses AND notification frames (incl. memory snapshots) land
        // in `engine.emit("rpc-message", ...)` for the JS transport to
        // forward to its onFrame handler.
        if (bridge) bridge->pumpAsync();

        // Emit a per-tick "frame" event so React's <EmulatorTile> knows to
        // poll plugin.getFrame. One emit per UI idle ties cadence to LVGL's
        // redraw — host-throttled when the window isn't visible.
        if (JSContext* ctx = jsEngine.getContext()) {
            jsEngine.emit("frame", 0, nullptr);
            pumpGamepad(ctx);
        }

        jsEngine.tick();
        maybeWriteScreenshot();
    }

    // Poll SDL game controllers and forward press / release / axis / hot-
    // plug events to the JS bridge using per-event channels. Mirrors the
    // keyboard pattern at onKeyboard() below: C++ owns the device read,
    // TS owns the policy (key/button → GameboyButton, menu nav, etc.).
    void pumpGamepad(JSContext* ctx)
    {
        gamepad.update([this, ctx](const retroplug::GamepadEvent& ev) {
            switch (ev.kind) {
                case retroplug::GamepadEvent::Kind::Connected: {
                    JSValue args[2] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.name ? ev.name : ""),
                    };
                    jsEngine.emit("gamepad-connected", 2, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Disconnected: {
                    JSValue args[1] = { JS_NewInt32(ctx, ev.pad) };
                    jsEngine.emit("gamepad-disconnected", 1, args);
                    JS_FreeValue(ctx, args[0]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Button: {
                    JSValue args[3] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.button ? ev.button : ""),
                        JS_NewBool(ctx, ev.pressed),
                    };
                    jsEngine.emit("gamepad-button", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Axis: {
                    JSValue args[3] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.axis ? ev.axis : ""),
                        JS_NewFloat64(ctx, ev.value),
                    };
                    jsEngine.emit("gamepad-axis", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
            }
        });
    }

    void uiFileBrowserSelected(const char* filename) override
    {
        if (!filename || !*filename) return; // user cancelled
        if (!bridge) return;
        bridge->onFileBrowserSelected(filename);
    }

    void onResize(const ResizeEvent& ev) override
    {
        UI::onResize(ev);
        const uint w = ev.size.getWidth();
        const uint h = ev.size.getHeight();
        d_stderr("[PluginUI] onResize %ux%u (asked %ux%u, wmControlled=%d)",
                 w, h, requestedW_, requestedH_, wmControlled_ ? 1 : 0);
#ifdef DISTRHO_OS_LINUX
        // Tiled-WM (e.g. Wayland/Hyprland) clamp detection. Only Linux
        // compositors tile/clamp the window out from under us; on Windows and
        // macOS the WM honours setSize, so a legitimate resize (DPI scaling,
        // host-driven sizing, user drag) must NOT be mistaken for a clamp.
        if (!wmControlled_ && requestedW_ != 0 && requestedH_ != 0) {
            if (w != requestedW_ || h != requestedH_) {
                wmControlled_ = true;
                d_stderr("[PluginUI] window-size compositor-controlled (asked %ux%u, got %ux%u); "
                         "JS will center content from now on",
                         requestedW_, requestedH_, w, h);
            }
        }
#endif
    }

    bool onKeyboard(const KeyboardEvent& ev) override
    {
        // Always forward to LVGL focus routing first — the parent chain
        // (LVGLWidget<TopLevelWidget>::onKeyboard) translates the DPF key
        // and writes it into LVGL's keyBuffer for the focused widget.
        UI::onKeyboard(ev);

        // Then mirror the event to JS so TS-side routing (game input,
        // menu toggle, etc.) can react. JS is the single source of truth
        // for keyboard policy.
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[2] = {
                JS_NewUint32(ctx, ev.key),
                JS_NewBool(ctx, ev.press),
            };
            jsEngine.emit("key", 2, args);
            JS_FreeValue(ctx, args[0]);
            JS_FreeValue(ctx, args[1]);
        }
        return true;
    }

    // Desktop wheel-to-scroll. The default LVGLWidget path feeds the wheel
    // into an ENCODER indev — LVGL interprets ticks as group-focus
    // navigation, which bounces focus through unrelated <View>s instead of
    // scrolling the panel under the pointer. Hit-test directly, find the
    // nearest scrollable ancestor with content overflow, scroll it.
    bool onScroll(const ScrollEvent& ev) override
    {
        lv_obj_t* const scr = lv_screen_active();
        if (scr != nullptr) {
            lv_point_t p = {
                static_cast<int32_t>(ev.pos.getX()),
                static_cast<int32_t>(ev.pos.getY()),
            };
            lv_obj_t* hit = lv_indev_search_obj(scr, &p);
            const int32_t step = 24;
            const int32_t dy   = static_cast<int32_t>(ev.delta.getY() * step);
            const int32_t dx   = static_cast<int32_t>(ev.delta.getX() * step);
            for (lv_obj_t* it = hit; it != nullptr; it = lv_obj_get_parent(it)) {
                if (!lv_obj_has_flag(it, LV_OBJ_FLAG_SCROLLABLE)) continue;
                const int32_t st = lv_obj_get_scroll_top(it);
                const int32_t sb = lv_obj_get_scroll_bottom(it);
                const int32_t sl = lv_obj_get_scroll_left(it);
                const int32_t sr = lv_obj_get_scroll_right(it);
                const bool vScroll = (dy != 0) && (st + sb > 0);
                const bool hScroll = (dx != 0) && (sl + sr > 0);
                if (vScroll || hScroll) {
                    // Sign convention: scroll_by_bounded's dy is opposite of
                    // the visible scroll direction (positive dy = scroll
                    // up). DPF delta.y > 0 = wheel up = pass dy as-is. X is
                    // opposite again (DPF delta.x > 0 = scroll right = LVGL
                    // negative dx).
                    lv_obj_scroll_by_bounded(it,
                                             hScroll ? -dx : 0,
                                             vScroll ?  dy : 0,
                                             LV_ANIM_OFF);
                    return true;
                }
            }
        }
        // Nothing scrollable under the cursor — swallow rather than fall
        // through to UI::onScroll, which would feed the encoder indev and
        // shuffle group focus across unrelated widgets.
        return true;
    }

    bool onMouse(const MouseEvent& ev) override
    {
        // Forward to LVGL so the framework's pointer routing (focus, onClick,
        // press style) still works. LVGL itself only sees a single binary
        // "is pressed" state regardless of which mouse button — fine for the
        // existing left-click-to-focus path on tiles.
        UI::onMouse(ev);

        // Mirror to JS so TS can implement button-aware policy (right-click
        // opens the per-instance menu). Same pattern as onKeyboard above.
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[4] = {
                JS_NewUint32(ctx, ev.button),
                JS_NewBool(ctx, ev.press),
                JS_NewFloat64(ctx, ev.pos.getX()),
                JS_NewFloat64(ctx, ev.pos.getY()),
            };
            jsEngine.emit("mouse", 4, args);
            JS_FreeValue(ctx, args[0]);
            JS_FreeValue(ctx, args[1]);
            JS_FreeValue(ctx, args[2]);
            JS_FreeValue(ctx, args[3]);
        }
        return true;
    }

    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(LVGLPluginUI)
};

// --------------------------------------------------------------------------------------------------------------------

UI* createUI()
{
    return new LVGLPluginUI();
}

// --------------------------------------------------------------------------------------------------------------------

END_NAMESPACE_DISTRHO
