// retroplug-sdl — the standalone RetroPlug for framebuffer handhelds (Anbernic / muOS) and any plain
// Linux desktop, hosted on SDL2 instead of DPF/pugl. muOS has no X11 (fbdev + Mali EGL only), so the
// DPF JACK standalone — whose window comes from pugl's X11-only Linux backend — can't run there. This
// host reuses the ENTIRE core (retroplug-backend Engine + cores + txiki runtime, and the SAME embedded
// control-plane + React/LVGL UI bytecode the plugin ships) and swaps only the thin shell:
//
//   * window + present : SDL2 software renderer (LVGL renders into a CPU ARGB8888 buffer; we upload it
//                        with SDL_UpdateTexture + SDL_RenderCopy — SDL drives Mali GLES2 internally, so
//                        no manual GL, no desktop-GL-over-Mali fuss).
//   * audio            : an SDL2 audio callback that drives Engine::processBlock per block (mirrors
//                        PluginDSP::run / AudioDriverRpcService::audioLoop, minus DPF).
//   * input            : SDL keyboard → the LVGL keypad indev + the "key" JS bus; GamepadManager →
//                        the gamepad-* JS bus (emulator input / TS bindings) AND the keypad indev
//                        (menu navigation, since a handheld has no arrow keys).
//
// It composes PluginDSP's control-plane boot (the backend service graph + __rpcSend on
// Symbol.for("plugin") + the cp bundle) and PluginUI's mount (the UI bundle + LVGL display) onto ONE
// TjsHostRuntime, exactly as the DPF plugin splits them across its DSP and UI halves. The non-GL LVGL
// setup mirrors packages/native/test/ui/RenderCore.cpp; the boot mirrors plugin/PluginDSP.cpp.

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <memory>
#include <string>
#include <vector>

#include <SDL.h>

extern "C" {
#include "lvgl.h"
}

#include "dpfjs/LvglJsEngine.hpp"            // LVGL display layer over the shared txiki host
#include "dpfjs/host/TjsHostRuntime.hpp"     // shared txiki/QuickJS host (+ tjs.h/quickjs.h)

#include "host/engine/Engine.hpp"
#include "host/engine/EngineInvoker.hpp"
#include "host/input/GamepadManager.hpp"     // SDL controller poll (shared UI-thread input)
#include "host/rpc/BackendRpcRegistration.hpp"
#include "system/CoreBackends.hpp"
#include "system/SystemFactory.hpp"
#include "TypedRpcServer.h"
#include "codecs/QuickJSCodec.h"
#include "transports/QuickJSTransport.h"

#include "native/components/component.hpp"   // GetWindowInstance() — the lv_binding_js React-tree root
#include "native/core/img/png/lodepng.h"     // lodepng_encode24_file (headless screenshot proof)

// The embedded bytecode bundles (tjsc, rp_ prefix), generated by CMake — the SAME artifacts the plugin
// links: cp-bundle_data.c (control plane, composes stores + DSP kernel + __rp_* globals) and
// ui-bundle_data.c (the React UI, registers __rp_mountUI).
extern "C" {
extern const std::uint8_t  rp_cp_bundle[];
extern const std::uint32_t rp_cp_bundle_size;
extern const std::uint8_t  rp_ui_bundle[];
extern const std::uint32_t rp_ui_bundle_size;
}

// LVGL is built LV_GLOBAL_CUSTOM: the application must supply lv_global_default(). In the plugin DPF's
// LVGLWidget provides a per-instance one; standalone (single window, single runtime) we provide one
// process-wide instance, zero-initialized like DPF's calloc — lv_init() populates it. (Same pattern as
// RenderCore.cpp.)
extern "C" lv_global_t* lv_global_default(void) {
    static lv_global_t* g = static_cast<lv_global_t*>(std::calloc(1, sizeof(lv_global_t)));
    return g;
}

using BackendRpcServer = rpcpp::TypedRpcServer<rpcpp::Empty, rpcpp::QuickJSCodec>;

namespace {

// Whole-process state, reached by the LVGL indev read callbacks (via driver_data), the SDL audio
// callback (via userdata), and the __rp_* window hooks (single instance → a file-scope pointer is fine,
// unlike the plugin's per-context routing for multi-instance DAWs).
struct AppState {
    // --- the shared runtime + backend graph (PluginDSP's control plane) ---
    TjsHostRuntime host;
    Engine         engine;
    SystemFactory  factory;
    QueuedInvoker  invoker{engine, engine.registry()};
    HostRpcService   hostSvc;
    EngineRpcService engineSvc{engine, factory, invoker};
    std::unique_ptr<rpcpp::QuickJSTransport> transport;
    std::unique_ptr<BackendRpcServer>        server;

    // --- the UI display layer (PluginUI), on the SAME host ---
    LvglJsEngine  ui{host};   // external-host ctor: adds only the LVGL layer, never shuts host down
    lv_display_t* display = nullptr;
    std::vector<std::uint8_t> drawBuf;
    lv_group_t*   group = nullptr;
    lv_indev_t*   keypad = nullptr;
    lv_indev_t*   pointer = nullptr;

    // synthetic input state the indev read callbacks pull from
    std::deque<std::uint32_t> keyQueue;   // pending LVGL key codes (keypad indev)
    lv_point_t mousePos{0, 0};
    bool       mouseDown = false;

    // --- SDL shell ---
    SDL_Window*   window = nullptr;
    SDL_Renderer* renderer = nullptr;
    SDL_Texture*  texture = nullptr;
    SDL_AudioDeviceID audioDev = 0;
    retroplug::GamepadManager gamepad;

    std::uint32_t width = 640;
    std::uint32_t height = 480;
    bool running = true;

    // audio scratch (pre-sized to the device block, so the callback never allocates)
    std::vector<float> audioL, audioR;
    double sampleRate = 48000.0;
};

AppState* g_app = nullptr;  // single instance

// ---- LVGL glue (mirrors RenderCore's non-GL subset) -----------------------------------------------

// No-op flush: in LV_DISPLAY_RENDER_MODE_DIRECT the draw buffer already holds the full rendered frame,
// which the main loop uploads to the SDL texture. Just acknowledge so LVGL continues.
void flushCb(lv_display_t* disp, const lv_area_t*, uint8_t*) { lv_display_flush_ready(disp); }

void keypadReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* a = static_cast<AppState*>(lv_indev_get_driver_data(indev));
    if (a && !a->keyQueue.empty()) {
        data->state = LV_INDEV_STATE_PRESSED;
        data->key   = a->keyQueue.front();
        a->keyQueue.pop_front();
        data->continue_reading = !a->keyQueue.empty();
    } else {
        data->state = LV_INDEV_STATE_RELEASED;
    }
}

void pointerReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* a = static_cast<AppState*>(lv_indev_get_driver_data(indev));
    if (!a) { data->state = LV_INDEV_STATE_RELEASED; return; }
    data->point = a->mousePos;
    data->state = a->mouseDown ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
}

// LVGL's tick source: real wall-clock ms so timers/animations run in real time.
std::uint32_t sdlTicksCb(void) { return SDL_GetTicks(); }

// ---- backend boot (PluginDSP::bootControlPlane, DPF-free) ------------------------------------------

bool readReady(TjsHostRuntime& host) {
    JSContext* ctx = host.context();
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, "__rp_ready");
    const bool r = JS_ToBool(ctx, v) > 0;
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return r;
}

// Call globalThis[name](arg?) on the control-plane context (main thread). Returns the string result, or
// "" for non-string / missing / exception. Mirrors PluginDSP::callGlobal (used for autoload here).
std::string callGlobal(TjsHostRuntime& host, const char* name, const char* arg) {
    JSContext* ctx = host.context();
    JSValue g  = JS_GetGlobalObject(ctx);
    JSValue fn = JS_GetPropertyStr(ctx, g, name);
    std::string out;
    if (JS_IsFunction(ctx, fn)) {
        JSValue argv[1];
        int argc = 0;
        if (arg) { argv[0] = JS_NewString(ctx, arg); argc = 1; }
        JSValue ret = JS_Call(ctx, fn, g, argc, argc ? argv : nullptr);
        if (argc) JS_FreeValue(ctx, argv[0]);
        if (JS_IsException(ret)) {
            JSValue exc = JS_GetException(ctx);
            const char* s = JS_ToCString(ctx, exc);
            std::fprintf(stderr, "[retroplug-sdl] %s threw: %s\n", name, s ? s : "?");
            if (s) JS_FreeCString(ctx, s);
            JS_FreeValue(ctx, exc);
        } else if (JS_IsString(ret)) {
            const char* s = JS_ToCString(ctx, ret);
            if (s) { out = s; JS_FreeCString(ctx, s); }
        } else if (JS_IsBool(ret)) {
            out = JS_ToBool(ctx, ret) > 0 ? "true" : "false";
        }
        JS_FreeValue(ctx, ret);
    }
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, g);
    return out;
}

bool hasGlobalFunction(JSContext* ctx, const char* name) {
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, name);
    const bool ok = JS_IsFunction(ctx, v);
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return ok;
}

// ---- __rp_* window hooks (PluginUI's window-op seam, single-instance) ------------------------------
// The UI optional-chains these, so anything we omit is simply inert. We provide the handful a handheld
// standalone needs; the file-browser / render-job hooks are left to a later milestone.

JSValue jsQuitWindow(JSContext*, JSValueConst, int, JSValueConst*) {
    if (g_app) g_app->running = false;
    return JS_UNDEFINED;
}
// Report the window as WM-controlled so the UI fits its grid via zoom instead of trying to resize a
// fixed fullscreen handheld window.
JSValue jsIsWindowSizeControlled(JSContext* ctx, JSValueConst, int, JSValueConst*) { return JS_NewBool(ctx, 1); }
JSValue jsSetWindowSize(JSContext*, JSValueConst, int, JSValueConst*) { return JS_UNDEFINED; }
JSValue jsSetWindowTitle(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && g_app->window && argc >= 1) {
        const char* t = JS_ToCString(ctx, argv[0]);
        if (t && *t) SDL_SetWindowTitle(g_app->window, t);
        if (t) JS_FreeCString(ctx, t);
    }
    return JS_UNDEFINED;
}
JSValue jsOpenPath(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (argc >= 1) {
        const char* p = JS_ToCString(ctx, argv[0]);
        if (p && *p) { const std::string cmd = "xdg-open \"" + std::string(p) + "\" &"; (void)std::system(cmd.c_str()); }
        if (p) JS_FreeCString(ctx, p);
    }
    return JS_UNDEFINED;
}

void installWindowHooks(JSContext* ctx) {
    JSValue g = JS_GetGlobalObject(ctx);
    auto bind = [&](const char* name, JSCFunction* fn, int len) {
        JS_SetPropertyStr(ctx, g, name, JS_NewCFunction(ctx, fn, name, len));
    };
    bind("__rp_quitWindow", jsQuitWindow, 0);
    bind("__rp_isWindowSizeControlled", jsIsWindowSizeControlled, 0);
    bind("__rp_setWindowSize", jsSetWindowSize, 2);
    bind("__rp_setWindowTitle", jsSetWindowTitle, 1);
    bind("__rp_openPath", jsOpenPath, 1);
    JS_FreeValue(ctx, g);
}

// ---- input translation ----------------------------------------------------------------------------

// Push an LVGL key onto the keypad queue AND emit the "key" JS bus (press+release), mirroring
// RenderCore::tapKey / PluginUI::onKeyboard. dpf is the DPF keycode the TS input layer expects.
void feedKey(AppState& a, std::uint32_t lvKey, std::uint32_t dpf, bool press) {
    JSContext* ctx = a.ui.getContext();
    if (press) a.keyQueue.push_back(lvKey);
    if (ctx) {
        JSValue args[2] = {JS_NewUint32(ctx, dpf), JS_NewBool(ctx, press)};
        a.ui.emit("key", 2, args);
        JS_FreeValue(ctx, args[0]);
        JS_FreeValue(ctx, args[1]);
    }
}

// Map an SDL keysym to (LVGL key, DPF keycode). Returns false for keys we don't translate.
bool mapSdlKey(SDL_Keycode k, std::uint32_t& lv, std::uint32_t& dpf) {
    switch (k) {
        case SDLK_UP:     lv = LV_KEY_UP;    dpf = 0xE036; return true;
        case SDLK_DOWN:   lv = LV_KEY_DOWN;  dpf = 0xE038; return true;
        case SDLK_RIGHT:  lv = LV_KEY_RIGHT; dpf = 0xE037; return true;
        case SDLK_LEFT:   lv = LV_KEY_LEFT;  dpf = 0xE035; return true;
        case SDLK_RETURN: lv = LV_KEY_ENTER; dpf = 0x0D;   return true;
        case SDLK_ESCAPE: lv = LV_KEY_ESC;   dpf = 0x1B;   return true;
        default: return false;
    }
}

// Map a GamepadManager button NAME (raw SDL button string) to an LVGL key for MENU navigation. A
// handheld has no arrow keys, so the d-pad + A/B drive the LVGL keypad focus group directly. In-game
// input is separate — the same button also rides the gamepad-* JS bus (TS bindings → pressButton).
bool mapPadButtonToLvKey(const char* name, std::uint32_t& lv) {
    if (!name) return false;
    if (std::strcmp(name, "dpup") == 0)    { lv = LV_KEY_UP;    return true; }
    if (std::strcmp(name, "dpdown") == 0)  { lv = LV_KEY_DOWN;  return true; }
    if (std::strcmp(name, "dpleft") == 0)  { lv = LV_KEY_LEFT;  return true; }
    if (std::strcmp(name, "dpright") == 0) { lv = LV_KEY_RIGHT; return true; }
    if (std::strcmp(name, "a") == 0)       { lv = LV_KEY_ENTER; return true; }
    if (std::strcmp(name, "b") == 0)       { lv = LV_KEY_ESC;   return true; }
    return false;
}

// Poll controllers once per frame → re-emit each transition onto the gamepad-* JS bus (exactly as
// PluginUI::pumpGamepad) and, for menu buttons, into the keypad queue.
void pumpGamepad(AppState& a) {
    JSContext* ctx = a.ui.getContext();
    if (!ctx) return;
    a.gamepad.update([&a, ctx](const retroplug::GamepadEvent& ev) {
        switch (ev.kind) {
            case retroplug::GamepadEvent::Kind::Connected: {
                JSValue args[2] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.name ? ev.name : "")};
                a.ui.emit("gamepad-connected", 2, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Disconnected: {
                JSValue args[1] = {JS_NewInt32(ctx, ev.pad)};
                a.ui.emit("gamepad-disconnected", 1, args);
                JS_FreeValue(ctx, args[0]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Button: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.button ? ev.button : ""),
                                   JS_NewBool(ctx, ev.pressed)};
                a.ui.emit("gamepad-button", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                std::uint32_t lv;
                if (ev.pressed && mapPadButtonToLvKey(ev.button, lv)) a.keyQueue.push_back(lv);
                break;
            }
            case retroplug::GamepadEvent::Kind::Axis: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.axis ? ev.axis : ""),
                                   JS_NewFloat64(ctx, ev.value)};
                a.ui.emit("gamepad-axis", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                break;
            }
        }
    });
}

// ---- audio ----------------------------------------------------------------------------------------
// SDL calls this on its own audio thread. It owns the Engine while running (setAudioThreadOwns(true)),
// so it drains the control-thread command ring each block then renders — mirrors PluginDSP::run.
void audioCb(void* userdata, Uint8* stream, int len) {
    auto* a = static_cast<AppState*>(userdata);
    const int frames = len / static_cast<int>(2 * sizeof(float));
    if (frames <= 0) { std::memset(stream, 0, len); return; }
    if (static_cast<int>(a->audioL.size()) < frames) { a->audioL.resize(frames); a->audioR.resize(frames); }

    a->invoker.drainInto(a->engine);
    a->engine.setBpm(120.0);
    a->engine.setTransport(true);
    a->engine.processBlock(static_cast<std::uint32_t>(frames), a->audioL.data(), a->audioR.data());

    auto* out = reinterpret_cast<float*>(stream);
    for (int i = 0; i < frames; ++i) { out[2 * i] = a->audioL[i]; out[2 * i + 1] = a->audioR[i]; }
}

// ---- screenshot (headless proof) ------------------------------------------------------------------
// Reuse LVGL's own snapshot (like PluginUI::maybeWriteScreenshot) so a headless run (SDL_VIDEODRIVER=
// offscreen) can dump a PNG and a test can assert the UI rendered. lodepng is linked via lvgl-js-native.
bool writeScreenshot(const std::string& path);

// ---- boot ------------------------------------------------------------------------------------------

bool bootControlPlane(AppState& a) {
    if (!a.host.init()) { std::fprintf(stderr, "[retroplug-sdl] TjsHostRuntime init failed\n"); return false; }
    JSContext* ctx = a.host.context();

    registerCoreBackends(a.factory);

    a.transport = std::make_unique<rpcpp::QuickJSTransport>(ctx, [](JSContext*, JSValue) {});
    a.server    = std::make_unique<BackendRpcServer>(*a.transport, rpcpp::QuickJSCodec{ctx});
    registerHostRpc(*a.server, a.hostSvc);
    registerEmulatorRpc(*a.server, a.engineSvc);
    registerDspKernelRpc(*a.server, a.engineSvc);
    a.server->addDiscoveryMethod();

    // globalThis[Symbol.for("plugin")] = { __rpcSend } — the namespace realBackend.ts targets.
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue sym    = JS_NewSymbol(ctx, "plugin", /*is_global*/ 1);
    JSAtom atom    = JS_ValueToAtom(ctx, sym);
    JSValue ns     = JS_NewObjectProto(ctx, JS_NULL);
    BackendRpcServer* srv = a.server.get();
    a.host.bindRpcSend(ns, [srv](JSContext* sctx, JSValueConst req) -> JSValue {
        auto out = srv->processMessage(req);
        if (!out) return JS_NULL;
        return out->materialize(sctx);
    });
    JS_DefinePropertyValue(ctx, global, atom, ns, JS_PROP_C_W_E);
    JS_FreeAtom(ctx, atom);
    JS_FreeValue(ctx, sym);
    JS_FreeValue(ctx, global);

    // Systems bake the sample rate at construct — set it BEFORE the bundle composes / autoloads.
    a.engine.setSampleRate(a.sampleRate);

    a.host.evalModuleBytecode(rp_cp_bundle, rp_cp_bundle_size);
    for (int i = 0; i < 1000 && !readReady(a.host); ++i) a.host.pump();
    if (!readReady(a.host)) { std::fprintf(stderr, "[retroplug-sdl] control plane not ready\n"); return false; }
    return true;
}

bool setupUi(AppState& a) {
    lv_init();
    lv_tick_set_cb(sdlTicksCb);

    a.display = lv_display_create(a.width, a.height);
    if (!a.display) return false;
    const lv_color_format_t cf = lv_display_get_color_format(a.display);
    const std::uint32_t stride = lv_draw_buf_width_to_stride(a.width, cf);
    a.drawBuf.assign(static_cast<std::size_t>(stride) * a.height, 0);
    lv_display_set_buffers(a.display, a.drawBuf.data(), nullptr, a.drawBuf.size(), LV_DISPLAY_RENDER_MODE_DIRECT);
    lv_display_set_flush_cb(a.display, flushCb);

    a.group = lv_group_create();
    lv_group_set_default(a.group);
    a.keypad = lv_indev_create();
    lv_indev_set_type(a.keypad, LV_INDEV_TYPE_KEYPAD);
    lv_indev_set_read_cb(a.keypad, keypadReadCb);
    lv_indev_set_driver_data(a.keypad, &a);
    lv_indev_set_group(a.keypad, a.group);
    a.pointer = lv_indev_create();
    lv_indev_set_type(a.pointer, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(a.pointer, pointerReadCb);
    lv_indev_set_driver_data(a.pointer, &a);

    if (!a.ui.init()) { std::fprintf(stderr, "[retroplug-sdl] LvglJsEngine init failed\n"); return false; }

    JSContext* ctx = a.ui.getContext();
    if (ctx && !hasGlobalFunction(ctx, "__rp_mountUI")) {
        if (a.ui.evalModuleBytecode(rp_ui_bundle, rp_ui_bundle_size) != 0) {
            std::fprintf(stderr, "[retroplug-sdl] failed to eval UI bundle\n");
            return false;
        }
    }
    a.ui.attachDisplay(); // → __rp_mountUI

    // Black out the screen + strip the theme chrome, and make the React-tree root track the screen (100%)
    // — same as PluginUI so nothing draws a border / inset / scrollbar.
    if (lv_obj_t* screen = lv_screen_active()) {
        lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
        lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
        lv_obj_set_style_border_width(screen, 0, 0);
        lv_obj_set_style_radius(screen, 0, 0);
        lv_obj_set_style_pad_all(screen, 0, 0);
        lv_obj_remove_flag(screen, LV_OBJ_FLAG_SCROLLABLE);
    }
    if (lv_obj_t* win = GetWindowInstance()) {
        lv_obj_set_style_width(win, lv_pct(100), 0);
        lv_obj_set_style_height(win, lv_pct(100), 0);
    }
    if (ctx) installWindowHooks(ctx);
    return true;
}

bool setupSdl(AppState& a) {
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_GAMECONTROLLER) != 0) {
        std::fprintf(stderr, "[retroplug-sdl] SDL_Init failed: %s\n", SDL_GetError());
        return false;
    }
    Uint32 winFlags = 0;
    if (std::getenv("RETROPLUG_SDL_FULLSCREEN")) winFlags |= SDL_WINDOW_FULLSCREEN;
    a.window = SDL_CreateWindow("RetroPlug", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                a.width, a.height, winFlags);
    if (!a.window) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateWindow failed: %s\n", SDL_GetError()); return false; }
    a.renderer = SDL_CreateRenderer(a.window, -1, SDL_RENDERER_SOFTWARE);
    if (!a.renderer) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateRenderer failed: %s\n", SDL_GetError()); return false; }
    a.texture = SDL_CreateTexture(a.renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING,
                                  a.width, a.height);
    if (!a.texture) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateTexture failed: %s\n", SDL_GetError()); return false; }

    // Audio: open before boot so the obtained rate seeds the Engine. The dummy driver (headless) still
    // fires the callback, so the emulator advances even with no device.
    SDL_AudioSpec want{}, have{};
    want.freq = static_cast<int>(a.sampleRate);
    want.format = AUDIO_F32SYS;
    want.channels = 2;
    want.samples = 1024;
    want.callback = audioCb;
    want.userdata = &a;
    a.audioDev = SDL_OpenAudioDevice(nullptr, 0, &want, &have, SDL_AUDIO_ALLOW_FREQUENCY_CHANGE);
    if (a.audioDev == 0) {
        std::fprintf(stderr, "[retroplug-sdl] SDL_OpenAudioDevice failed: %s (continuing muted)\n", SDL_GetError());
    } else {
        a.sampleRate = have.freq;
        a.audioL.assign(have.samples, 0.0f);
        a.audioR.assign(have.samples, 0.0f);
    }
    return true;
}

void present(AppState& a) {
    SDL_UpdateTexture(a.texture, nullptr, a.drawBuf.data(),
                      static_cast<int>(lv_draw_buf_width_to_stride(a.width, lv_display_get_color_format(a.display))));
    SDL_RenderClear(a.renderer);
    SDL_RenderCopy(a.renderer, a.texture, nullptr, nullptr);
    SDL_RenderPresent(a.renderer);
}

void handleEvents(AppState& a) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        switch (ev.type) {
            case SDL_QUIT: a.running = false; break;
            case SDL_KEYDOWN:
            case SDL_KEYUP: {
                std::uint32_t lv, dpf;
                if (mapSdlKey(ev.key.keysym.sym, lv, dpf)) feedKey(a, lv, dpf, ev.type == SDL_KEYDOWN);
                break;
            }
            case SDL_MOUSEMOTION: a.mousePos = {ev.motion.x, ev.motion.y}; break;
            case SDL_MOUSEBUTTONDOWN:
            case SDL_MOUSEBUTTONUP:
                a.mousePos = {ev.button.x, ev.button.y};
                a.mouseDown = ev.type == SDL_MOUSEBUTTONDOWN;
                break;
            default: break;
        }
    }
}

} // namespace

int main(int argc, char** argv) {
    AppState app;
    g_app = &app;

    // --- args / env ---
    std::string autoloadPath;
    if (const char* env = std::getenv("RETROPLUG_AUTOLOAD_PROJECT")) autoloadPath = env;
    long exitAfterFrames = 0;
    if (const char* env = std::getenv("RETROPLUG_SDL_EXIT_AFTER_FRAMES")) exitAfterFrames = std::atol(env);
    std::string screenshotPath;
    if (const char* env = std::getenv("RETROPLUG_SDL_SCREENSHOT")) screenshotPath = env;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--autoload" && i + 1 < argc) autoloadPath = argv[++i];
        else if (arg == "--width" && i + 1 < argc) app.width = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        else if (arg == "--height" && i + 1 < argc) app.height = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        else if (arg == "--screenshot" && i + 1 < argc) screenshotPath = argv[++i];
    }

    if (!setupSdl(app)) return 1;
    if (!bootControlPlane(app)) return 1;

    // Autoload a .rplg project before the audio thread takes the Engine (structural build runs direct).
    if (!autoloadPath.empty()) {
        const std::string ok = callGlobal(app.host, "__rp_loadProjectPath", autoloadPath.c_str());
        std::fprintf(stderr, "[retroplug-sdl] autoload %s -> %s\n", autoloadPath.c_str(), ok.empty() ? "false/void" : ok.c_str());
    }

    if (!setupUi(app)) return 1;

    // Hand the Engine to the SDL audio thread (control-plane edits become push-only, drained per block)
    // then start it. Mirrors PluginDSP::activate.
    app.invoker.setAudioThreadOwns(true);
    if (app.audioDev) SDL_PauseAudioDevice(app.audioDev, 0);

    std::fprintf(stderr, "[retroplug-sdl] running %ux%u @ %.0f Hz\n", app.width, app.height, app.sampleRate);

    // --- the 60 fps loop: input → JS frame → LVGL render → present ---
    long frame = 0;
    while (app.running) {
        const Uint32 t0 = SDL_GetTicks();
        handleEvents(app);
        if (JSContext* ctx = app.ui.getContext()) {
            app.ui.emit("frame", 0, nullptr); // drives EmulatorTile's getFrame
            pumpGamepad(app);
            (void)ctx;
        }
        app.ui.tick();          // pump the shared host's JS/libuv loop
        lv_timer_handler();     // LVGL indev read + layout + render into drawBuf
        present(app);

        if (!screenshotPath.empty() && exitAfterFrames > 0 && frame + 1 == exitAfterFrames)
            writeScreenshot(screenshotPath);
        if (exitAfterFrames > 0 && ++frame >= exitAfterFrames) app.running = false;

        const Uint32 dt = SDL_GetTicks() - t0;
        if (dt < 16) SDL_Delay(16 - dt); // ~60 fps
    }

    // --- teardown: reclaim the Engine, unmount, drop SDL ---
    if (app.audioDev) { SDL_PauseAudioDevice(app.audioDev, 1); SDL_CloseAudioDevice(app.audioDev); }
    app.invoker.setAudioThreadOwns(false);
    app.invoker.drainInto(app.engine);
    app.invoker.reclaimReleased();

    if (app.display) lv_display_enable_invalidation(app.display, false);
    if (lv_obj_t* screen = lv_screen_active()) lv_obj_clean(screen);
    app.ui.detachDisplay();
    lv_timer_handler();

    if (app.texture) SDL_DestroyTexture(app.texture);
    if (app.renderer) SDL_DestroyRenderer(app.renderer);
    if (app.window) SDL_DestroyWindow(app.window);
    SDL_Quit();
    g_app = nullptr;
    return 0;
}

namespace {
bool writeScreenshot(const std::string& path) {
    lv_obj_t* screen = lv_screen_active();
    if (!screen) return false;
    lv_draw_buf_t* snap = lv_snapshot_take(screen, LV_COLOR_FORMAT_ARGB8888);
    if (!snap) return false;
    const std::uint32_t w = snap->header.w, h = snap->header.h;
    std::vector<unsigned char> rgb(static_cast<std::size_t>(w) * h * 3);
    const std::uint8_t* src = snap->data; // ARGB8888 = B,G,R,A little-endian
    for (std::size_t i = 0, n = static_cast<std::size_t>(w) * h; i < n; ++i) {
        rgb[i * 3 + 0] = src[i * 4 + 2];
        rgb[i * 3 + 1] = src[i * 4 + 1];
        rgb[i * 3 + 2] = src[i * 4 + 0];
    }
    const unsigned err = lodepng_encode24_file(path.c_str(), rgb.data(), w, h);
    lv_draw_buf_destroy(snap);
    if (err) { std::fprintf(stderr, "[retroplug-sdl] screenshot error %u\n", err); return false; }
    std::fprintf(stderr, "[retroplug-sdl] screenshot -> %s (%ux%u)\n", path.c_str(), w, h);
    return true;
}
} // namespace
