// retroplug-sdl — the standalone RetroPlug for framebuffer handhelds (Anbernic / muOS) and any plain
// Linux desktop, hosted on SDL2 instead of DPF/pugl. muOS has no X11 (fbdev + Mali EGL only), so the
// DPF JACK standalone — whose window comes from pugl's X11-only Linux backend — can't run there. This
// host reuses the ENTIRE core (retroplug-backend Engine + cores + txiki runtime, and the SAME embedded
// control-plane + React/LVGL UI bytecode the plugin ships) and swaps only the thin shell:
//
//   * window + present : SDL2 software renderer (LVGL renders into a CPU ARGB8888 buffer; we upload it
//                        with SDL_UpdateTexture + SDL_RenderCopy — SDL drives Mali GLES2 internally, so
//                        no manual GL, no desktop-GL-over-Mali fuss).
//   * audio            : an SDL2 audio callback that drives Engine::processBlock per block (mirrors
//                        PluginDSP::run / AudioDriverRpcService::audioLoop, minus DPF).
//   * input            : SDL keyboard → the LVGL keypad indev + the "key" JS bus; GamepadManager →
//                        the gamepad-* JS bus (emulator input / TS bindings) AND the keypad indev
//                        (menu navigation, since a handheld has no arrow keys).
//
// It composes PluginDSP's control-plane boot (the backend service graph + __rpcSend on
// Symbol.for("plugin") + the cp bundle) and PluginUI's mount (the UI bundle + LVGL display) onto ONE
// TjsHostRuntime, exactly as the DPF plugin splits them across its DSP and UI halves. The non-GL LVGL
// setup mirrors packages/native/test/ui/RenderCore.cpp; the boot mirrors plugin/PluginDSP.cpp.

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#if defined(__linux__)
#include <atomic>
#include <pthread.h>
#include <sched.h>
#include <unistd.h>
#endif

// We own main() (a plain console entry). On Windows/macOS SDL's <SDL.h> otherwise #defines main → SDL_main
// and pulls in the SDL2main entry shim (which we don't link — only SDL2::SDL2). Defining SDL_MAIN_HANDLED
// before the include keeps our main() intact on every platform; setupSdl() calls SDL_SetMainReady() to match.
// (Harmless on Linux, where SDL never redefines main.)
#define SDL_MAIN_HANDLED
#include <SDL.h>

#include <portaudio.h>   // audio backend (deps/portaudio, pipewire branch) — replaces SDL audio

#include <rfl/json.hpp>  // audio.json / midi.json (device settings), tolerant JSON like the role-config crossing

extern "C" {
#include "lvgl.h"
}

#include "dpfjs/LvglJsEngine.hpp"            // LVGL display layer over the shared txiki host
#include "dpfjs/host/TjsHostRuntime.hpp"     // shared txiki/QuickJS host (+ tjs.h/quickjs.h)

#include "host/engine/Engine.hpp"
#include "host/engine/EngineInvoker.hpp"
#include "host/input/GamepadManager.hpp"     // SDL controller poll (shared UI-thread input)
#include "host/input/MidiIo.hpp"             // RtMidi in/out seam (virtual + hardware ports)
#include "host/rpc/BackendRpcRegistration.hpp"
#include "host/ui/SoftwareLvglDisplay.hpp"   // shared LvInputState + display/indev scaffold (also used by test/ui)
#include "system/CoreBackends.hpp"
#include "system/SystemFactory.hpp"
#include "TypedRpcServer.h"
#include "codecs/QuickJSCodec.h"
#include "transports/QuickJSTransport.h"

#include "native/components/component.hpp"   // GetWindowInstance() — the lv_binding_js React-tree root
#include "native/core/img/png/lodepng.h"     // lodepng_encode24_file (headless screenshot proof)

#include "host/ui/NativeFileDialog.hpp"      // OS-native file picker (pfd) backing __rp_openFileBrowser

// The embedded bytecode bundles (tjsc, rp_ prefix), generated by CMake — the SAME artifacts the plugin
// links: cp-bundle_data.c (control plane, composes stores + DSP kernel + __rp_* globals) and
// ui-bundle_data.c (the React UI, registers __rp_mountUI).
extern "C" {
extern const std::uint8_t  rp_cp_bundle[];
extern const std::uint32_t rp_cp_bundle_size;
extern const std::uint8_t  rp_ui_bundle[];
extern const std::uint32_t rp_ui_bundle_size;
}

// LVGL is built LV_GLOBAL_CUSTOM: the application must supply lv_global_default(). In the plugin DPF's
// LVGLWidget provides a per-instance one; standalone (single window, single runtime) we provide one
// process-wide instance, zero-initialized like DPF's calloc — lv_init() populates it. (Same pattern as
// RenderCore.cpp.)
extern "C" lv_global_t* lv_global_default(void) {
    static lv_global_t* g = static_cast<lv_global_t*>(std::calloc(1, sizeof(lv_global_t)));
    return g;
}

using BackendRpcServer = rpcpp::TypedRpcServer<rpcpp::Empty, rpcpp::QuickJSCodec>;

namespace {

// Derives the host transport (BPM + playing) from incoming MIDI real-time bytes, so an external clock
// master drives LSDj sync-to-external (the LSDj MidiSync role regenerates 0xF8 from Engine tempo/transport
// via eachTick — it doesn't read the raw wire clock, so feeding setBpm/setTransport is all it takes).
// Audio-thread-only: fed from audioCb, never touched elsewhere → plain members, no locking.
//
// Clock timing: RtMidi timestamps are discarded and messages arrive block-quantized, so we measure the
// pulse rate in audio frames accumulated across blocks (24 PPQN): BPM = 60·sr·pulses / (frames·24). Playing
// follows 0xFA/0xFB (start/continue) and 0xFC (stop), plus a ~0.5 s clock-presence timeout so a bare-clock
// master with no start/stop still plays. With NO clock at all we fall back to a free-running 120/playing
// (the standalone's prior always-on behaviour), so non-sync use (mGB, un-synced LSDj) is unchanged.
struct MidiClockSync {
    double sampleRate = 48000.0;
    long long frameClock = 0;      // monotonic frames processed
    long long lastClockFrame = 0;  // frameClock at the most recent 0xF8
    long long windowFrames = 0;    // frames accumulated in the current tempo window
    int  windowPulses = 0;         // 0xF8 count in the current window
    double bpm = 120.0;            // last good estimate
    bool active = false;           // clock seen within the timeout
    bool stopped = false;          // explicit 0xFC latch (overrides clock presence)

    static constexpr int    kWindowPulses = 24; // one quarter-note → a stable estimate ~2×/s
    static constexpr double kTimeoutSec   = 0.5;

    // One drained real-time byte. Returns true if it was a transport byte (so the caller skips staging it).
    bool onByte(std::uint8_t status) {
        switch (status) {
            case 0xF8: active = true; lastClockFrame = frameClock; ++windowPulses; return true; // clock
            case 0xFA: case 0xFB: active = true; stopped = false; lastClockFrame = frameClock; return true; // start/continue
            case 0xFC: stopped = true; return true; // stop
            default: return false;
        }
    }

    // Call once per audio block, after that block's bytes, with the block's frame count.
    void advance(long long frames) {
        if (active) {
            windowFrames += frames;
            if (windowPulses >= kWindowPulses && windowFrames > 0) {
                const double est = 60.0 * sampleRate * windowPulses / (static_cast<double>(windowFrames) * 24.0);
                if (est >= 20.0 && est <= 999.0) bpm = est;
                windowPulses = 0;
                windowFrames = 0;
            }
            if (frameClock - lastClockFrame > static_cast<long long>(sampleRate * kTimeoutSec)) {
                active = false; stopped = false; windowPulses = 0; windowFrames = 0; // master gone → free-run
            }
        }
        frameClock += frames;
    }

    double outBpm() const { return active ? bpm : 120.0; }
    bool   outPlaying() const { return active ? !stopped : true; }
};

// Whole-process state, reached by the LVGL indev read callbacks (via driver_data), the SDL audio
// callback (via userdata), and the __rp_* window hooks (single instance → a file-scope pointer is fine,
// unlike the plugin's per-context routing for multi-instance DAWs).
struct AppState {
    // --- the shared runtime + backend graph (PluginDSP's control plane) ---
    TjsHostRuntime host;
    Engine         engine;
    SystemFactory  factory;
    QueuedInvoker  invoker{engine, engine.registry()};
    HostRpcService   hostSvc;
    EngineRpcService engineSvc{engine, factory, invoker};
    std::unique_ptr<rpcpp::QuickJSTransport> transport;
    std::unique_ptr<BackendRpcServer>        server;

    // --- the UI display layer (PluginUI), on the SAME host ---
    LvglJsEngine  ui{host};   // external-host ctor: adds only the LVGL layer, never shuts host down
    lv_display_t* display = nullptr;
    std::vector<std::uint8_t> drawBuf;
    lv_group_t*   group = nullptr;
    lv_indev_t*   keypad = nullptr;
    lv_indev_t*   pointer = nullptr;

    // synthetic input state the shared keypad/pointer indev read callbacks pull from (driver_data == &input)
    retroplug::ui::LvInputState input;

    // A desktop file drag-and-drop in progress: SDL delivers one SDL_DROPFILE per file between
    // SDL_DROPBEGIN and SDL_DROPCOMPLETE, so we accumulate the paths here and emit one newline-joined
    // "file-drop" on complete (matching PluginUI::uiFileDropped — resolveDropAction needs ROM+.sav together).
    std::vector<std::string> dropBatch;

    // The in-flight OS-native file dialog (opened by __rp_openFileBrowser). Async: opened here, polled each
    // frame in the main loop (pollFileDialog), the pick delivered to JS on ready. Shared with the plugin host.
    retroplug::ui::NativeFileDialog nativeDialog;

    // --- SDL shell ---
    SDL_Window*   window = nullptr;
    SDL_Renderer* renderer = nullptr;
    SDL_Texture*  texture = nullptr;
    PaStream*     audioStream = nullptr;       // PortAudio output stream (null when muted → headless fallback)
    std::thread   audioPump;                   // headless fallback pump thread (no device); see audioPumpLoop
    std::atomic<bool> audioPumpRun{false};
    retroplug::GamepadManager gamepad;
    retroplug::MidiIo midi;   // RtMidi in/out; drained into the Engine on the audio thread each block
    std::vector<retroplug::MidiIo::Message> midiScratch;  // reused per block (no per-block alloc)
    std::atomic<std::uint64_t> midiStaged{0};             // count staged into the Engine (headless self-test)
    MidiClockSync clockSync;                              // MIDI-clock → BPM/transport (audio thread only)

    std::uint32_t width = 640;
    std::uint32_t height = 480;
    bool running = true;
    // Fullscreen (the handheld): the WM owns a fixed panel, so the UI fits its grid via zoom and
    // __rp_setWindowSize is inert. Windowed (desktop): the window is ours to size, so it grows/shrinks to
    // the grid like the DPF standalone. Set from the SDL_WINDOW_FULLSCREEN flag in setupSdl.
    bool fullscreen = false;

    // Window-geometry ownership — mirrors PluginUI's wmControlled_ / sizeHonored_ / requestedW/H latch, so the
    // resizable SDL window behaves like the DPF standalone under a tiling WM (Wayland/Hyprland). wmControlled
    // starts true for fullscreen and for the Wayland backend (see setupSdl - a Wayland compositor never tells
    // us whether it honored a resize); it also latches true when the compositor hands us a size we never asked
    // for (a tile) before any requested size was ever honored - then we stop driving SDL_SetWindowSize and the
    // UI fits its grid via zoom instead. sizeHonored proves the window is floating (a request took), which
    // vetoes the clamp latch so a spurious compositor resize isn't mistaken for a tiling takeover.
    bool          wmControlled = false;
    bool          sizeHonored = false;
    std::uint32_t requestedW = 0;   // last size asked of the WM (the clamp-detection baseline)
    std::uint32_t requestedH = 0;
    bool          debugResize = false;  // RETROPLUG_DEBUG_RESIZE: log every request / WM resize (WM debugging)

    // audio scratch: `numOutputs` planar channel buffers (pre-sized to the device block so the callback
    // never allocates). The Engine renders planar + routes each system to its pair per audioRouting; we
    // interleave into the SDL stream. numOutputs == reqOutChannels (device opened with allowed_changes=0).
    std::vector<std::vector<float>> audioPlanar;
    std::vector<float*>             audioPtrs;
    int    numOutputs = 2;
    double sampleRate = 48000.0;   // obtained device rate (drives the Engine)
    int    reqSampleRate = 48000;  // requested (UI-configurable) rate + block + channels, persisted to audio.json
    int    reqBlockSize  = 512;    // low-latency default; low-power devices (the handheld) pass a bigger buffer
                                   // via --block-size (e.g. 4096) so the audio callback keeps its deadline
    int    reqOutChannels = 2;     // 2 = stereo mix (default); 4/6/8 = wide stems for a multichannel device
    int    reqHostApi = -1;        // chosen PortAudio host API (PaHostApiTypeId: paPipeWire/paALSA/paJACK/...);
                                   // -1 = Auto (prefer PipeWire, else default). Persisted to audio.json.

    // Present only when LVGL actually redrew: the flush cb unions the changed area here; the loop skips
    // the SDL texture upload + blit entirely on idle frames (a static menu → ~0% CPU instead of a full
    // 640×480 upload every frame). dirty starts true so the first frame always shows.
    bool dirty = true;
    lv_area_t dirtyRect{0, 0, 0, 0};
};

AppState* g_app = nullptr;  // single instance

// Audio device (re)configuration — defined after audioCb (they reference it); declared here so the
// __rp_setAudioConfig hook (bound earlier) can drive a live sample-rate / block-size change.
bool openAudio(AppState& a);
void reconfigureAudio(AppState& a, int sampleRate, int blockSize, int channels, int hostApi);
void loadAudioConfig(AppState& a);
void saveAudioConfig(AppState& a);
// MIDI device (re)selection — declared here so the __rp_setMidiInput/Output hooks (bound earlier) can drive a
// live device change; defined next to reconfigureAudio (it pauses the audio callback the same way).
void reconfigureMidi(AppState& a, bool input, const std::string& name);
void loadMidiConfig(AppState& a);

// Resize the window + everything that tracks its dimensions (the __rp_setWindowSize seam). Defined after the
// LVGL glue; declared here so the window hook can call it. Runs on the UI thread (same as present), so the
// texture/buffer/width swap is race-free.
void requestWindowSize(AppState& a, std::uint32_t w, std::uint32_t h);

// The smallest window we ask for / allow (mirrors the plugin's setGeometryConstraints). SDL clamps every
// SDL_SetWindowSize to this floor, so requestWindowSize has to clamp identically - see the comment there.
constexpr std::uint32_t kMinWindowW = 480;
constexpr std::uint32_t kMinWindowH = 432;

// ---- LVGL glue (mirrors RenderCore's non-GL subset) -----------------------------------------------

// Flush: in LV_DISPLAY_RENDER_MODE_DIRECT the draw buffer already holds the full rendered frame; we just
// record which region changed (union across the refresh's flush calls) so the loop uploads + presents
// only that rect, and skips presenting entirely when nothing changed.
void flushCb(lv_display_t* disp, const lv_area_t* area, uint8_t*) {
    if (g_app && area) {
        if (!g_app->dirty) { g_app->dirtyRect = *area; g_app->dirty = true; }
        else {
            g_app->dirtyRect.x1 = std::min(g_app->dirtyRect.x1, area->x1);
            g_app->dirtyRect.y1 = std::min(g_app->dirtyRect.y1, area->y1);
            g_app->dirtyRect.x2 = std::max(g_app->dirtyRect.x2, area->x2);
            g_app->dirtyRect.y2 = std::max(g_app->dirtyRect.y2, area->y2);
        }
    }
    lv_display_flush_ready(disp);
}

// Keypad + pointer indev read callbacks live in host/ui/SoftwareLvglDisplay.hpp (shared with the test
// harness). AppState embeds retroplug::ui::LvInputState and hands &input to both indevs as driver_data.

// LVGL's tick source: real wall-clock ms so timers/animations run in real time.
std::uint32_t sdlTicksCb(void) { return SDL_GetTicks(); }

// ---- backend boot (PluginDSP::bootControlPlane, DPF-free) ------------------------------------------

bool readReady(TjsHostRuntime& host) {
    JSContext* ctx = host.context();
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, "__rp_ready");
    const bool r = JS_ToBool(ctx, v) > 0;
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return r;
}

// Call globalThis[name](arg?) on the control-plane context (main thread). Returns the string result, or
// "" for non-string / missing / exception. Mirrors PluginDSP::callGlobal (used for autoload here).
std::string callGlobal(TjsHostRuntime& host, const char* name, const char* arg) {
    JSContext* ctx = host.context();
    JSValue g  = JS_GetGlobalObject(ctx);
    JSValue fn = JS_GetPropertyStr(ctx, g, name);
    std::string out;
    if (JS_IsFunction(ctx, fn)) {
        JSValue argv[1];
        int argc = 0;
        if (arg) { argv[0] = JS_NewString(ctx, arg); argc = 1; }
        JSValue ret = JS_Call(ctx, fn, g, argc, argc ? argv : nullptr);
        if (argc) JS_FreeValue(ctx, argv[0]);
        if (JS_IsException(ret)) {
            JSValue exc = JS_GetException(ctx);
            const char* s = JS_ToCString(ctx, exc);
            std::fprintf(stderr, "[retroplug-sdl] %s threw: %s\n", name, s ? s : "?");
            if (s) JS_FreeCString(ctx, s);
            JS_FreeValue(ctx, exc);
        } else if (JS_IsString(ret)) {
            const char* s = JS_ToCString(ctx, ret);
            if (s) { out = s; JS_FreeCString(ctx, s); }
        } else if (JS_IsBool(ret)) {
            out = JS_ToBool(ctx, ret) > 0 ? "true" : "false";
        }
        JS_FreeValue(ctx, ret);
    }
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, g);
    return out;
}

bool hasGlobalFunction(JSContext* ctx, const char* name) {
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, name);
    const bool ok = JS_IsFunction(ctx, v);
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return ok;
}

// ---- __rp_* window hooks (PluginUI's window-op seam, single-instance) ------------------------------
// The UI optional-chains these, so anything we omit is simply inert. We provide the handful a handheld
// standalone needs; the render-job hooks are left to a later milestone.

JSValue jsQuitWindow(JSContext*, JSValueConst, int, JSValueConst*) {
    if (g_app) g_app->running = false;
    return JS_UNDEFINED;
}
// A WM-controlled window (a fullscreen handheld, or a window a tiling compositor tiled) → the UI fits its grid
// via zoom rather than resizing. A floating desktop window is ours to size, so the App's fit-to-grid effect
// drives resizes. Mirrors PluginUI::isWindowSizeControlled — the latch that keeps us from fighting the WM.
JSValue jsIsWindowSizeControlled(JSContext* ctx, JSValueConst, int, JSValueConst*) {
    return JS_NewBool(ctx, g_app ? g_app->wmControlled : 1);
}
// __rp_setWindowSize(w, h): grow/shrink the window to the grid. Mirrors the DPF standalone, where setSize() →
// the platform resize callback reallocs the LVGL buffer + emits "resize"; SDL gives us no such callback, so
// requestWindowSize asks the WM and the SDL_WINDOWEVENT_SIZE_CHANGED handler does the realloc. Inert once the
// WM owns geometry (a fullscreen handheld, or a tiling compositor) — requestWindowSize handles that.
JSValue jsSetWindowSize(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (!g_app || argc < 2) return JS_UNDEFINED;
    std::uint32_t w = 0, h = 0;
    JS_ToUint32(ctx, &w, argv[0]);
    JS_ToUint32(ctx, &h, argv[1]);
    if (w != 0 && h != 0) requestWindowSize(*g_app, w, h);
    return JS_UNDEFINED;
}
JSValue jsSetWindowTitle(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && g_app->window && argc >= 1) {
        const char* t = JS_ToCString(ctx, argv[0]);
        if (t && *t) SDL_SetWindowTitle(g_app->window, t);
        if (t) JS_FreeCString(ctx, t);
    }
    return JS_UNDEFINED;
}
JSValue jsOpenPath(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (argc >= 1) {
        const char* p = JS_ToCString(ctx, argv[0]);
        if (p && *p) {
            const std::string path(p);
            // Open a file/folder in the OS file manager, per platform.
#if defined(_WIN32)
            const std::string cmd = "start \"\" \"" + path + "\"";        // cmd's start; "" = window title
#elif defined(__APPLE__)
            const std::string cmd = "open \"" + path + "\"";
#else
            const std::string cmd = "xdg-open \"" + path + "\" &";
#endif
            (void)std::system(cmd.c_str());
        }
        if (p) JS_FreeCString(ctx, p);
    }
    return JS_UNDEFINED;
}

// Deliver a native file dialog's pick into JS by calling the __rp_onFileBrowserResult resolver the real
// Backend registered (empty path = cancel → null). Same shared context / UI thread that pumps the JS loop,
// so a direct call is safe — the awaiting Promise settles on the next tick. Copy of PluginUI::uiFileBrowserSelected.
void deliverFileBrowserResult(JSContext* ctx, const std::string& path) {
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_onFileBrowserResult");
    if (JS_IsFunction(ctx, fn)) {
        JSValue arg = path.empty() ? JS_NULL : JS_NewString(ctx, path.c_str());
        JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 1, &arg);
        JS_FreeValue(ctx, ret);
        JS_FreeValue(ctx, arg);
    }
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, global);
}

// __rp_openFileBrowser(title, patterns, saving, defaultName, startDir, directory): open the OS-native file
// dialog (bound only where NativeFileDialog::available()). Async — the pick is delivered later by
// pollFileDialog. `patterns` is a whitespace-separated glob list; `directory` picks a FOLDER (the render
// "Output Dir"); `saving` seeds the save name with defaultName.
JSValue jsOpenFileBrowser(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (!g_app || argc < 6) return JS_UNDEFINED;
    auto arg = [&](int i) -> std::string {
        const char* s = JS_ToCString(ctx, argv[i]);
        std::string out = (s && *s) ? s : "";
        if (s) JS_FreeCString(ctx, s);
        return out;
    };
    g_app->nativeDialog.request(arg(0), arg(1), JS_ToBool(ctx, argv[2]) == 1, arg(3), arg(4),
                                JS_ToBool(ctx, argv[5]) == 1);
    return JS_UNDEFINED;
}

// Poll the in-flight OS file dialog once per frame; when the helper finishes, deliver the pick (cancel = empty)
// into JS. Cheap no-op when nothing is open.
void pollFileDialog(AppState& a) {
    JSContext* ctx = a.ui.getContext();
    if (!ctx) return;
    a.nativeDialog.poll([ctx](const std::string& pick) {
        if (std::getenv("RETROPLUG_SDL_DIALOG_SELFTEST")) // headless E2E: prove the full pfd round-trip delivered
            std::fprintf(stderr, "[retroplug-sdl] dialog self-test: picked '%s'\n", pick.c_str());
        deliverFileBrowserResult(ctx, pick);
    });
}

// The PortAudio host APIs usable for output right now — each registered host API (ALSA/PipeWire/JACK/...) that
// has a valid default output device. Drives the Settings > Audio > Driver picker; `type` is a PaHostApiTypeId
// (what AppState::reqHostApi stores + audio.json persists). Depends on the runtime, so it's recomputed on read.
struct HostApiEntry { std::string name; int type; };
std::vector<HostApiEntry> availableHostApis() {
    std::vector<HostApiEntry> out;
    for (PaHostApiIndex i = 0; i < Pa_GetHostApiCount(); ++i) {
        const PaHostApiInfo* h = Pa_GetHostApiInfo(i);
        if (h && h->defaultOutputDevice != paNoDevice) out.push_back({ h->name, static_cast<int>(h->type) });
    }
    return out;
}

// __rp_getAudioConfig(): { sampleRate, blockSize, outChannels, driver, drivers } — the live standalone audio
// device config, for the Audio settings submenu to display the current values. `drivers` is "Auto" plus each
// available host API name; `driver` is the selected name ("Auto" when reqHostApi is -1, or when the persisted
// host API isn't currently available — which is exactly when openAudio falls back to Auto anyway).
JSValue jsGetAudioConfig(JSContext* ctx, JSValueConst, int, JSValueConst*) {
    JSValue o = JS_NewObject(ctx);
    if (g_app) {
        JS_SetPropertyStr(ctx, o, "sampleRate",  JS_NewInt32(ctx, g_app->reqSampleRate));
        JS_SetPropertyStr(ctx, o, "blockSize",   JS_NewInt32(ctx, g_app->reqBlockSize));
        JS_SetPropertyStr(ctx, o, "outChannels", JS_NewInt32(ctx, g_app->reqOutChannels));
        const std::vector<HostApiEntry> apis = availableHostApis();
        JSValue arr = JS_NewArray(ctx);
        JS_SetPropertyUint32(ctx, arr, 0, JS_NewString(ctx, "Auto"));
        std::string selected = "Auto";
        for (std::uint32_t i = 0; i < apis.size(); ++i) {
            JS_SetPropertyUint32(ctx, arr, i + 1, JS_NewString(ctx, apis[i].name.c_str()));
            if (apis[i].type == g_app->reqHostApi) selected = apis[i].name;
        }
        JS_SetPropertyStr(ctx, o, "drivers", arr);
        JS_SetPropertyStr(ctx, o, "driver",  JS_NewString(ctx, selected.c_str()));
    }
    return o;
}

// __rp_setAudioConfig(sampleRate, blockSize, outChannels?, driver?): re-open the audio device with new params on
// the fly (and persist them). Reuses the deactivate→re-rate→reactivate handoff the plugin does for a host SR
// change. outChannels is optional (older UI bundles omit it) — 2/4/6/8; anything else keeps the current count.
// driver is optional — "Auto"/"" = the default (PipeWire-preferred) selection, else a host API name from
// __rp_getAudioConfig().drivers (matched to its PaHostApiTypeId); an unknown name keeps the current driver.
JSValue jsSetAudioConfig(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && argc >= 2) {
        int sr = 0, bs = 0, ch = g_app->reqOutChannels, ha = g_app->reqHostApi;
        JS_ToInt32(ctx, &sr, argv[0]);
        JS_ToInt32(ctx, &bs, argv[1]);
        if (argc >= 3) { int c = 0; JS_ToInt32(ctx, &c, argv[2]); if (c >= 2 && c <= 8 && (c % 2) == 0) ch = c; }
        if (argc >= 4) {
            const char* s = JS_ToCString(ctx, argv[3]);
            const std::string name = s ? s : "";
            if (s) JS_FreeCString(ctx, s);
            if (name.empty() || name == "Auto") ha = -1;
            else for (const HostApiEntry& e : availableHostApis()) if (e.name == name) { ha = e.type; break; }
        }
        if (sr > 0 && bs > 0) reconfigureAudio(*g_app, sr, bs, ch, ha);
    }
    return JS_UNDEFINED;
}

// __rp_getMidiConfig(): { inputs: string[], outputs: string[], selectedInput, selectedOutput } — the live
// hardware MIDI ports + the current device selection, for the Settings > MIDI pickers. "" selection = the
// default (All Devices for input, None for output). Standalone-only; absent in the plugin (DAW routes MIDI).
JSValue jsGetMidiConfig(JSContext* ctx, JSValueConst, int, JSValueConst*) {
    JSValue o = JS_NewObject(ctx);
    if (g_app) {
        auto toArray = [&](const std::vector<std::string>& names) {
            JSValue a = JS_NewArray(ctx);
            for (std::uint32_t i = 0; i < names.size(); ++i)
                JS_SetPropertyUint32(ctx, a, i, JS_NewString(ctx, names[i].c_str()));
            return a;
        };
        JS_SetPropertyStr(ctx, o, "inputs",  toArray(g_app->midi.listInputs()));
        JS_SetPropertyStr(ctx, o, "outputs", toArray(g_app->midi.listOutputs()));
        JS_SetPropertyStr(ctx, o, "selectedInput",  JS_NewString(ctx, g_app->midi.inputSelection().c_str()));
        JS_SetPropertyStr(ctx, o, "selectedOutput", JS_NewString(ctx, g_app->midi.outputSelection().c_str()));
    }
    return o;
}

// __rp_setMidiInput(name) / __rp_setMidiOutput(name): choose a hardware device by port name (empty string =
// the default). Applies immediately (reconnects the RtMidi port) + persists to midi.json.
JSValue jsSetMidiInput(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && argc >= 1) {
        const char* s = JS_ToCString(ctx, argv[0]);
        reconfigureMidi(*g_app, true, s ? s : "");
        if (s) JS_FreeCString(ctx, s);
    }
    return JS_UNDEFINED;
}
JSValue jsSetMidiOutput(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && argc >= 1) {
        const char* s = JS_ToCString(ctx, argv[0]);
        reconfigureMidi(*g_app, false, s ? s : "");
        if (s) JS_FreeCString(ctx, s);
    }
    return JS_UNDEFINED;
}

void installWindowHooks(JSContext* ctx) {
    JSValue g = JS_GetGlobalObject(ctx);
    auto bind = [&](const char* name, JSCFunction* fn, int len) {
        JS_SetPropertyStr(ctx, g, name, JS_NewCFunction(ctx, fn, name, len));
    };
    bind("__rp_quitWindow", jsQuitWindow, 0);
    bind("__rp_isWindowSizeControlled", jsIsWindowSizeControlled, 0);
    bind("__rp_setWindowSize", jsSetWindowSize, 2);
    bind("__rp_setWindowTitle", jsSetWindowTitle, 1);
    bind("__rp_openPath", jsOpenPath, 1);
    bind("__rp_getAudioConfig", jsGetAudioConfig, 0);
    bind("__rp_setAudioConfig", jsSetAudioConfig, 2);
    // MIDI device selection (Settings > MIDI). RtMidi is compiled into retroplug-sdl, so the seam always
    // exists here; the plugin never binds these (hasMidiConfig() is false there → the submenu is hidden).
    bind("__rp_getMidiConfig", jsGetMidiConfig, 0);
    bind("__rp_setMidiInput", jsSetMidiInput, 1);
    bind("__rp_setMidiOutput", jsSetMidiOutput, 1);
    // The OS-native file dialog — only where a desktop helper exists (zenity/kdialog/…). Where none does
    // (the muOS handheld, a bare container) we DON'T bind it: useFileBrowser sees no nativeHook and the
    // "File Dialogs: OS Native" toggle transparently stays in-app. The self-test forces the bind to prove it.
    if (retroplug::ui::NativeFileDialog::available() || std::getenv("RETROPLUG_SDL_DIALOG_SELFTEST"))
        bind("__rp_openFileBrowser", jsOpenFileBrowser, 6);
    // Mark this as a standalone host so the UI shows the "Exit" menu row (a DAW hides it).
    JS_SetPropertyStr(ctx, g, "__rp_isStandalone", JS_NewBool(ctx, 1));
    JS_FreeValue(ctx, g);
}

// ---- input translation ----------------------------------------------------------------------------

// Push an LVGL key onto the keypad queue AND emit the "key" JS bus (press+release), mirroring
// RenderCore::tapKey / PluginUI::onKeyboard. dpf is the DPF keycode the TS input layer expects.
void feedKey(AppState& a, std::uint32_t lvKey, std::uint32_t dpf, bool press) {
    JSContext* ctx = a.ui.getContext();
    if (press && lvKey != 0) a.input.keyQueue.push_back(lvKey);  // only real LVGL nav keys reach the keypad indev
    if (ctx) {
        JSValue args[2] = {JS_NewUint32(ctx, dpf), JS_NewBool(ctx, press)};
        a.ui.emit("key", 2, args);
        JS_FreeValue(ctx, args[0]);
        JS_FreeValue(ctx, args[1]);
    }
}

// Map an SDL keysym to (LVGL key, DPF keycode). The DPF code is what the TS input layer (keyCodes.ts)
// expects on the "key" bus: arrows in the 0xE03x band, ShiftL/R at 0xE051/2, and — crucially — printable
// keys carry their ASCII code verbatim (dpfCodeToKeyName does String.fromCharCode). Only the navigation
// keys get a real LVGL keypad code (`lv`); everything else is bus-only (lv = 0) — game buttons, capture,
// and app actions all live on the "key" bus, not the keypad. Returns false for keys we don't translate.
//
// This must cover every key the default bindings use (bindingMap.ts): dpad = arrows, A = Z, B = X,
// Start = Enter, Select = ShiftL/ShiftR/Backspace — plus anything the user might rebind to. Previously only
// arrows/Enter/Esc were mapped, so A/B/Select (and any letter/modifier binding) never reached the emulator
// OR the key-capture editor.
bool mapSdlKey(SDL_Keycode k, std::uint32_t& lv, std::uint32_t& dpf) {
    lv = 0;
    switch (k) {
        case SDLK_UP:       lv = LV_KEY_UP;    dpf = 0xE036; return true;
        case SDLK_DOWN:     lv = LV_KEY_DOWN;  dpf = 0xE038; return true;
        case SDLK_RIGHT:    lv = LV_KEY_RIGHT; dpf = 0xE037; return true;
        case SDLK_LEFT:     lv = LV_KEY_LEFT;  dpf = 0xE035; return true;
        case SDLK_RETURN:   lv = LV_KEY_ENTER; dpf = 0x0D;   return true;
        case SDLK_KP_ENTER: lv = LV_KEY_ENTER; dpf = 0x0D;   return true;
        case SDLK_ESCAPE:   lv = LV_KEY_ESC;   dpf = 0x1B;   return true;
        // Bus-only keys (no keypad nav): the GB Select defaults + editor keys.
        case SDLK_LSHIFT:   dpf = 0xE051; return true;   // ShiftL
        case SDLK_RSHIFT:   dpf = 0xE052; return true;   // ShiftR
        case SDLK_BACKSPACE:dpf = 0x08;   return true;   // Backspace (Select default; clears a capture row)
        case SDLK_TAB:      dpf = 0x09;   return true;   // Tab (default Cycle-Instances app action)
        case SDLK_PAGEUP:   dpf = 0xE031; return true;   // menu coarse-step
        case SDLK_PAGEDOWN: dpf = 0xE032; return true;
        default:
            // Printable ASCII (letters/digits/punctuation/space): SDL's keycode IS the ASCII code, which is
            // exactly the DPF/DGL "key" bus convention. Covers A=Z, B=X and anything the user rebinds to.
            if (k >= 0x20 && k <= 0x7e) { dpf = static_cast<std::uint32_t>(k); return true; }
            return false;
    }
}

// Poll controllers once per frame → re-emit each transition onto the gamepad-* JS bus (exactly as
// PluginUI::pumpGamepad). The gamepad drives BOTH menu navigation and in-game input purely through this
// bus: the React Menu has its own gamepad handler, and the design contract is that the gamepad bus never
// reaches the LVGL keypad indev (Menu.tsx). So we must NOT also translate gamepad → keypad here — doing
// so double-drives the menu (every move counted twice) while leaving in-game input single (the keypad
// keys hit the idle focus sink). Keyboard still feeds the keypad (mapSdlKey/feedKey) for desktop use.
void pumpGamepad(AppState& a) {
    JSContext* ctx = a.ui.getContext();
    if (!ctx) return;
    a.gamepad.update([&a, ctx](const retroplug::GamepadEvent& ev) {
        switch (ev.kind) {
            case retroplug::GamepadEvent::Kind::Connected: {
                JSValue args[2] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.name ? ev.name : "")};
                a.ui.emit("gamepad-connected", 2, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Disconnected: {
                JSValue args[1] = {JS_NewInt32(ctx, ev.pad)};
                a.ui.emit("gamepad-disconnected", 1, args);
                JS_FreeValue(ctx, args[0]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Button: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.button ? ev.button : ""),
                                   JS_NewBool(ctx, ev.pressed)};
                a.ui.emit("gamepad-button", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Axis: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.axis ? ev.axis : ""),
                                   JS_NewFloat64(ctx, ev.value)};
                a.ui.emit("gamepad-axis", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                break;
            }
        }
    });
}

// ---- audio-thread scheduling (A53 real-time headroom) ----------------------------------------------
#if defined(__linux__)
// The audio path runs at ~1x realtime on the A53 (the SameBoy APU is ~92% of every block), so a
// preempted or core-shared audio thread underruns → choppy sound. Give the audio thread a dedicated core
// + real-time priority, and keep the UI/emulator-advancing work off that core. Best-effort: failures (no
// RT permission when not root) are ignored — it just falls back to the default scheduling.
void tuneAudioThread() {
    const long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
    if (ncpu > 1) {
        cpu_set_t set; CPU_ZERO(&set); CPU_SET(ncpu - 1, &set); // pin to the last core
        pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
    }
    sched_param sp{}; sp.sched_priority = 80;
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);
}
void pinUiThreadAwayFromAudioCore() {
    const long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
    if (ncpu <= 2) return; // too few cores to segregate
    cpu_set_t set; CPU_ZERO(&set);
    for (long c = 0; c + 1 < ncpu; ++c) CPU_SET(c, &set); // all cores except the audio core (the last)
    pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
}
#endif

// ---- audio (PortAudio) ----------------------------------------------------------------------------
// PortAudio (deps/portaudio, `pipewire` branch) drives audio — the native PipeWire host API where available,
// else ALSA. The callback owns the Engine while running (setAudioThreadOwns(true)): it drains the control-
// thread command ring each block then renders, exactly as PluginDSP::run does. renderAudioBlock is the shared
// body called by BOTH the PortAudio callback and the headless fallback pump (below).
void renderAudioBlock(AppState& a, float* out, int frames) {
    const int N = a.numOutputs;
    if (frames <= 0 || N <= 0) return;
    if (static_cast<int>(a.audioPlanar[0].size()) < frames)
        for (int c = 0; c < N; ++c) { a.audioPlanar[c].resize(frames); a.audioPtrs[c] = a.audioPlanar[c].data(); }

    a.invoker.drainInto(a.engine);
    // Drain MIDI the RtMidi callback thread staged into the ring, and hand it to the Engine — we own it on
    // this (audio) thread, exactly like PluginDSP::run stages host MIDI. Frame 0 for now: live hardware MIDI
    // carries no sub-block timing worth preserving (a proper offset from the block clock is a later step).
    a.midi.poll(a.midiScratch);
    a.clockSync.sampleRate = a.sampleRate;
    for (auto& m : a.midiScratch) {
        if (m.bytes.empty() || m.bytes.size() > 3) continue;
        // Real-time transport bytes (0xF8 clock / 0xFA start / 0xFB continue / 0xFC stop) drive the host
        // transport, not the emulator — consume them here and don't stage them (the sync roles regenerate
        // clock from Engine tempo/transport). Everything else (notes/CC/...) is staged as host MIDI in.
        if (m.bytes.size() == 1 && a.clockSync.onByte(m.bytes[0])) continue;
        a.engine.stageMidi(0, std::move(m.bytes));
        a.midiStaged.fetch_add(1, std::memory_order_relaxed);
    }
    a.clockSync.advance(frames);

    a.engine.setBpm(a.clockSync.outBpm());          // 120 free-run until an external clock master appears
    a.engine.setTransport(a.clockSync.outPlaying()); // then locks to its tempo + start/stop
    // Multi-out: render into the N planar channel buffers; the Engine zeroes + routes each system to its
    // pair per audioRouting (MultiOutRouter/ChannelSplitRouter). N=2 collapses every mode to the stereo mix
    // (identical to the old 2-arg path). N=4/6/8 spreads stems across the device's pairs.
    a.engine.processBlock(static_cast<std::uint32_t>(frames), a.audioPtrs.data(), static_cast<std::size_t>(N));

    // Kernel MIDI-out (LSDj MI.OUT / Master Sync / passthrough) → the RtMidi out port, then clear the block's
    // queue. Mirrors PluginDSP::run's writeMidiEvent drain (there it goes to the DAW).
    for (const auto& mo : a.engine.midiOut())
        if (mo.data.size() >= 1 && mo.data.size() <= 3) a.midi.send(mo.data.data(), mo.data.size());
    a.engine.clearMidiOut();

    for (int i = 0; i < frames; ++i)
        for (int c = 0; c < N; ++c) out[i * N + c] = a.audioPlanar[c][i]; // planar → interleaved (frame-major)
}

// The PortAudio stream callback (its own RT thread) — paFloat32 interleaved, numOutputs channels.
int paCallback(const void* /*in*/, void* output, unsigned long frameCount, const PaStreamCallbackTimeInfo*,
               PaStreamCallbackFlags, void* userData) {
    auto* a = static_cast<AppState*>(userData);
#if defined(__linux__)
    static std::atomic<bool> tuned{false};
    if (!tuned.exchange(true)) tuneAudioThread(); // once, on the real audio thread
#endif
    renderAudioBlock(*a, static_cast<float*>(output), static_cast<int>(frameCount));
    return paContinue;
}

// Headless fallback: when no PortAudio device opens (CI / offscreen / no audio server), pump the engine at the
// block cadence into a throwaway buffer on our own thread — so the emulator still advances and the smoke's
// transport / multi-out checks run. This is the role SDL's `dummy` audio driver played (PortAudio has no null
// device). Owns the Engine like the real callback (the host sets audioThreadOwns(true) around start/stop).
void audioPumpLoop(AppState& a) {
    std::vector<float> buf;
    while (a.audioPumpRun.load(std::memory_order_acquire)) {
        const int frames = a.reqBlockSize > 0 ? a.reqBlockSize : 1024;
        buf.assign(static_cast<std::size_t>(frames) * (a.numOutputs > 0 ? a.numOutputs : 1), 0.0f);
        renderAudioBlock(a, buf.data(), frames);
        const double secs = a.sampleRate > 0 ? frames / a.sampleRate : frames / 48000.0;
        std::this_thread::sleep_for(std::chrono::duration<double>(secs)); // approximate realtime (clock/BPM sanity)
    }
}

// Start / stop whichever audio path is active: the real PortAudio stream, or the headless fallback pump.
void startAudio(AppState& a) {
    if (a.audioStream) { Pa_StartStream(a.audioStream); return; }
    a.audioPumpRun.store(true, std::memory_order_release);
    a.audioPump = std::thread(audioPumpLoop, std::ref(a));
}
void stopAudio(AppState& a) {
    if (a.audioStream) { Pa_StopStream(a.audioStream); return; } // blocks until the callback returns (joins it)
    if (a.audioPump.joinable()) { a.audioPumpRun.store(false, std::memory_order_release); a.audioPump.join(); }
}

// Open a PortAudio output stream at the requested rate/block + size the render scratch. numOutputs / sampleRate
// / the planar buffers are ALWAYS set (even when muted) so the Engine + the multi-out self-test behave with no
// device. Returns true if a real stream opened; false = muted (startAudio then runs the fallback pump).
bool openAudio(AppState& a) {
    a.numOutputs = a.reqOutChannels;   // PortAudio opens exactly what we ask
    a.sampleRate = a.reqSampleRate;
    a.audioPlanar.assign(a.numOutputs, std::vector<float>(a.reqBlockSize, 0.0f));
    a.audioPtrs.resize(a.numOutputs);
    for (int c = 0; c < a.numOutputs; ++c) a.audioPtrs[c] = a.audioPlanar[c].data();

    // One-time diagnostic: which host APIs PortAudio registered + their default output (RETROPLUG_DEBUG_AUDIO).
    if (std::getenv("RETROPLUG_DEBUG_AUDIO")) {
        for (PaHostApiIndex i = 0; i < Pa_GetHostApiCount(); ++i) {
            const PaHostApiInfo* h = Pa_GetHostApiInfo(i);
            if (h) std::fprintf(stderr, "[retroplug-sdl] host API %d: %s (type=%d, devices=%d, defaultOut=%d)\n",
                                i, h->name, (int)h->type, h->deviceCount, h->defaultOutputDevice);
        }
    }

    // Choose the output device by host API. Auto (reqHostApi < 0): prefer the native PipeWire host API (the
    // fork's paPipeWire) over PortAudio's default host API, which on Linux resolves to raw ALSA, else the
    // platform default. Otherwise honor the picked host API (Settings > Audio > Driver), falling back to Auto
    // when it's absent / has no output device (e.g. over SSH with no session — then raw ALSA / muted).
    auto hostApiDefaultOut = [](PaHostApiTypeId type) -> PaDeviceIndex {
        const PaHostApiIndex idx = Pa_HostApiTypeIdToHostApiIndex(type);
        if (idx < 0) return paNoDevice;
        const PaHostApiInfo* hi = Pa_GetHostApiInfo(idx);
        return (hi && hi->defaultOutputDevice != paNoDevice) ? hi->defaultOutputDevice : paNoDevice;
    };
    PaDeviceIndex dev = paNoDevice;
    if (a.reqHostApi >= 0) {
        dev = hostApiDefaultOut(static_cast<PaHostApiTypeId>(a.reqHostApi));
        if (dev == paNoDevice)
            std::fprintf(stderr, "[retroplug-sdl] audio: requested host API type=%d unavailable, using Auto\n",
                         a.reqHostApi);
    }
    if (dev == paNoDevice) dev = hostApiDefaultOut(paPipeWire); // Auto: prefer PipeWire
    if (dev == paNoDevice) dev = Pa_GetDefaultOutputDevice();   // else the platform default
    if (dev == paNoDevice) {
        std::fprintf(stderr, "[retroplug-sdl] PortAudio: no default output device (muted)\n");
        a.audioStream = nullptr;
        return false;
    }
    PaStreamParameters out{};
    out.device = dev;
    out.channelCount = a.reqOutChannels;
    out.sampleFormat = paFloat32; // interleaved float, frame-major (what renderAudioBlock writes)
    out.suggestedLatency = Pa_GetDeviceInfo(dev)->defaultLowOutputLatency;
    out.hostApiSpecificStreamInfo = nullptr;
    const PaError err = Pa_OpenStream(&a.audioStream, nullptr, &out, a.reqSampleRate,
                                      static_cast<unsigned long>(a.reqBlockSize), paNoFlag, paCallback, &a);
    if (err != paNoError) {
        std::fprintf(stderr, "[retroplug-sdl] Pa_OpenStream(%d Hz, %d frames, %d ch) failed: %s (muted)\n",
                     a.reqSampleRate, a.reqBlockSize, a.reqOutChannels, Pa_GetErrorText(err));
        a.audioStream = nullptr;
        return false;
    }
    if (const PaStreamInfo* info = Pa_GetStreamInfo(a.audioStream)) a.sampleRate = info->sampleRate;
    const PaDeviceInfo* di = Pa_GetDeviceInfo(dev);
    std::fprintf(stderr, "[retroplug-sdl] audio: PortAudio [%s] '%s' %d Hz, %d frames, %d ch\n",
                 di ? Pa_GetHostApiInfo(di->hostApi)->name : "?", di ? di->name : "?",
                 static_cast<int>(a.sampleRate), a.reqBlockSize, a.numOutputs);
    return true;
}

// audio.json / midi.json are NATIVE-owned device settings, read here at startup (setupSdl) before
// bootControlPlane brings up the JS runtime that owns config.json — so they can't live in the TS config, and
// they're standalone-only anyway (the plugin gets audio/MIDI from its DAW). They're small reflect-cpp JSON
// blobs, decoded tolerantly (DefaultIfMissing) exactly like the per-system role config that crosses to native
// (a missing/garbage field takes the struct default). Whole file into a string (empty if unreadable).
std::string slurpTextFile(const std::string& path) {
    std::string out;
    if (FILE* f = std::fopen(path.c_str(), "rb")) {
        char buf[4096];
        size_t n;
        while ((n = std::fread(buf, 1, sizeof buf, f)) > 0) out.append(buf, n);
        std::fclose(f);
    }
    return out;
}
void writeTextFile(const std::string& path, const std::string& text) {
    if (FILE* f = std::fopen(path.c_str(), "wb")) {
        std::fwrite(text.data(), 1, text.size(), f);
        std::fclose(f);
    }
}

// The standalone audio device settings. hostApi is a PaHostApiTypeId (-1 = Auto). Defaults here mirror the
// AppState defaults so a partial/absent file lands on the same values.
struct AudioCfgJson {
    int sampleRate = 48000;
    int blockSize = 512;
    int outChannels = 2;
    int hostApi = -1; // PaHostApiTypeId; -1 = Auto (prefer PipeWire, else default)
};

std::string audioCfgPath(AppState& a) { return a.hostSvc.configDir() + "/audio.json"; }

void loadAudioConfig(AppState& a) {
    const std::string json = slurpTextFile(audioCfgPath(a));
    if (json.empty()) return; // absent/unreadable → keep the compiled-in / --block-size-seeded defaults
    const auto r = rfl::json::read<AudioCfgJson, rfl::DefaultIfMissing>(json);
    if (!r) return; // unparseable → keep defaults
    const AudioCfgJson c = r.value();
    if (c.sampleRate > 0) a.reqSampleRate = c.sampleRate;
    if (c.blockSize > 0) a.reqBlockSize = c.blockSize;
    if (c.outChannels >= 2 && c.outChannels <= 8 && (c.outChannels % 2) == 0) a.reqOutChannels = c.outChannels;
    a.reqHostApi = c.hostApi; // -1 = Auto; any other value is a PaHostApiTypeId (openAudio validates it)
}

void saveAudioConfig(AppState& a) {
    const AudioCfgJson c{ a.reqSampleRate, a.reqBlockSize, a.reqOutChannels, a.reqHostApi };
    writeTextFile(audioCfgPath(a), rfl::json::write(c) + "\n");
}

// The chosen MIDI input/output device names (Settings > MIDI). "" = the default sentinel (All Devices for
// input, None for output).
struct MidiCfgJson {
    std::string input;
    std::string output;
};

std::string midiCfgPath(AppState& a) { return a.hostSvc.configDir() + "/midi.json"; }

void loadMidiConfig(AppState& a) {
    const std::string json = slurpTextFile(midiCfgPath(a));
    if (json.empty()) return;
    const auto r = rfl::json::read<MidiCfgJson, rfl::DefaultIfMissing>(json);
    if (!r) return;
    const MidiCfgJson c = r.value();
    a.midi.setInputSelection(c.input);   // stored now; applied when midi.open() connects the ports
    a.midi.setOutputSelection(c.output);
}

void saveMidiConfig(AppState& a) {
    const MidiCfgJson c{ a.midi.inputSelection(), a.midi.outputSelection() };
    writeTextFile(midiCfgPath(a), rfl::json::write(c) + "\n");
}

// Live audio reconfigure (the Audio settings submenu): stop the device, take the Engine back from the
// audio thread, re-rate it, re-open at the new rate/block, hand it back — the plugin's deactivate →
// setSampleRate → activate handoff. Then persist. Called on the UI thread.
void reconfigureAudio(AppState& a, int sampleRate, int blockSize, int channels, int hostApi) {
    if (sampleRate == a.reqSampleRate && blockSize == a.reqBlockSize && channels == a.reqOutChannels &&
        hostApi == a.reqHostApi &&
        (a.audioStream || a.audioPumpRun.load(std::memory_order_acquire)))
        return; // no-op — same params (incl. driver) + audio already active (real stream or fallback pump)
    stopAudio(a);                                     // Pa_StopStream (joins the callback) or stop+join the pump
    if (a.audioStream) { Pa_CloseStream(a.audioStream); a.audioStream = nullptr; }
    a.invoker.setAudioThreadOwns(false);
    a.invoker.drainInto(a.engine);
    a.reqSampleRate = sampleRate;
    a.reqBlockSize  = blockSize;
    a.reqOutChannels = channels;
    a.reqHostApi = hostApi;
    a.engine.setSampleRate(sampleRate); // re-rate live cores (safe — audio stopped)
    openAudio(a);                       // opens a real stream, or leaves it muted (numOutputs still sized)
    a.invoker.setAudioThreadOwns(true);
    startAudio(a);                      // Pa_StartStream, or start the headless fallback pump
    saveAudioConfig(a);
    std::fprintf(stderr, "[retroplug-sdl] audio reconfigured: %d Hz, %d frames, %d ch (driver type=%d)\n",
                 a.reqSampleRate, a.reqBlockSize, a.reqOutChannels, a.reqHostApi);
}

// Live MIDI device reselection (Settings > MIDI). Briefly stops audio so the callback / pump isn't mid
// poll/send while we reconnect the RtMidi ports — PortAudio has no SDL_LockAudioDevice equivalent, and
// Pa_StopStream joins the callback, so mutating the ports races nothing. A brief audio gap on a manual device
// change is expected (rare action) — the audio-thread analog of reconfigureAudio's handoff.
void reconfigureMidi(AppState& a, bool input, const std::string& name) {
    stopAudio(a);
    if (input) a.midi.setInputSelection(name);
    else       a.midi.setOutputSelection(name);
    startAudio(a);
    saveMidiConfig(a);
    std::fprintf(stderr, "[retroplug-sdl] MIDI %s device -> '%s'\n", input ? "input" : "output",
                 name.empty() ? (input ? "All Devices" : "None") : name.c_str());
}

// ---- screenshot (headless proof) ------------------------------------------------------------------
// Dump the display's composited draw buffer (the exact frame presented, including top-layer overlays
// like the file browser) so a headless run (SDL_VIDEODRIVER=offscreen) can screenshot for a test.
bool writeScreenshot(AppState& a, const std::string& path);

// True if the rendered frame is a single flat colour (nothing drew) — the CI smoke's "the UI actually
// rendered, not just booted" gate. Compares the draw buffer as 32-bit pixels against the first.
bool frameIsBlank(const AppState& a) {
    if (a.drawBuf.size() < 8) return true;
    const auto* px = reinterpret_cast<const std::uint32_t*>(a.drawBuf.data());
    const std::size_t n = a.drawBuf.size() / 4;
    for (std::size_t i = 1; i < n; ++i) if (px[i] != px[0]) return false;
    return true;
}

// ---- boot ------------------------------------------------------------------------------------------

bool bootControlPlane(AppState& a) {
    if (!a.host.init()) { std::fprintf(stderr, "[retroplug-sdl] TjsHostRuntime init failed\n"); return false; }
    JSContext* ctx = a.host.context();

    registerCoreBackends(a.factory);

    a.transport = std::make_unique<rpcpp::QuickJSTransport>(ctx, [](JSContext*, JSValue) {});
    a.server    = std::make_unique<BackendRpcServer>(*a.transport, rpcpp::QuickJSCodec{ctx});
    registerHostRpc(*a.server, a.hostSvc);
    registerEmulatorRpc(*a.server, a.engineSvc);
    registerDspKernelRpc(*a.server, a.engineSvc);
    a.server->addDiscoveryMethod();

    // globalThis[Symbol.for("plugin")] = { __rpcSend } — the namespace realBackend.ts targets.
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue sym    = JS_NewSymbol(ctx, "plugin", /*is_global*/ 1);
    JSAtom atom    = JS_ValueToAtom(ctx, sym);
    JSValue ns     = JS_NewObjectProto(ctx, JS_NULL);
    BackendRpcServer* srv = a.server.get();
    a.host.bindRpcSend(ns, [srv](JSContext* sctx, JSValueConst req) -> JSValue {
        auto out = srv->processMessage(req);
        if (!out) return JS_NULL;
        return out->materialize(sctx);
    });
    JS_DefinePropertyValue(ctx, global, atom, ns, JS_PROP_C_W_E);
    JS_FreeAtom(ctx, atom);
    JS_FreeValue(ctx, sym);
    JS_FreeValue(ctx, global);

    // Systems bake the sample rate at construct — set it BEFORE the bundle composes / autoloads.
    a.engine.setSampleRate(a.sampleRate);

    a.host.evalModuleBytecode(rp_cp_bundle, rp_cp_bundle_size);
    for (int i = 0; i < 1000 && !readReady(a.host); ++i) a.host.pump();
    if (!readReady(a.host)) { std::fprintf(stderr, "[retroplug-sdl] control plane not ready\n"); return false; }
    return true;
}

bool setupUi(AppState& a) {
    lv_init();
    lv_tick_set_cb(sdlTicksCb);

    // Display + indevs: the shared software-LVGL scaffold (host/ui/SoftwareLvglDisplay.hpp), also used by the
    // headless test harness. SDL supplies its own dirty-tracking flush (present() uploads only the changed rect).
    auto sd = retroplug::ui::createSoftwareDisplay(a.width, a.height, a.drawBuf, flushCb, &a.input);
    if (!sd.display) return false;
    a.display = sd.display;
    a.group   = sd.group;
    a.keypad  = sd.keypad;
    a.pointer = sd.pointer;

    if (!a.ui.init()) { std::fprintf(stderr, "[retroplug-sdl] LvglJsEngine init failed\n"); return false; }

    JSContext* ctx = a.ui.getContext();
    if (ctx && !hasGlobalFunction(ctx, "__rp_mountUI")) {
        if (a.ui.evalModuleBytecode(rp_ui_bundle, rp_ui_bundle_size) != 0) {
            std::fprintf(stderr, "[retroplug-sdl] failed to eval UI bundle\n");
            return false;
        }
    }
    a.ui.attachDisplay(); // → __rp_mountUI

    // Black screen, stripped chrome, root pinned to 100% — same as PluginUI (shared with the test harness).
    retroplug::ui::applyChromelessScreen();
    if (ctx) installWindowHooks(ctx);

    // Headless proof of the OS-dialog seam. Reports whether __rp_openFileBrowser is bound + whether a desktop
    // helper is available; if one is (a real or a fake zenity/kdialog in PATH), it drives a real pfd request
    // whose pick pollFileDialog then delivers + logs — exercising the whole request→helper→parse→deliver path.
    if (std::getenv("RETROPLUG_SDL_DIALOG_SELFTEST")) {
        const bool bound = ctx && hasGlobalFunction(ctx, "__rp_openFileBrowser");
        const bool avail = retroplug::ui::NativeFileDialog::available();
        std::fprintf(stderr, "[retroplug-sdl] dialog self-test: __rp_openFileBrowser %s, helper %s\n",
                     bound ? "BOUND" : "MISSING", avail ? "available" : "absent");
        if (avail) a.nativeDialog.request("Self-test", "*.gb", false, "", "/tmp", false);
    }
    return true;
}

bool setupSdl(AppState& a) {
    SDL_SetMainReady(); // required when SDL_MAIN_HANDLED is set (see the <SDL.h> include note)
    // A stable application name → the Wayland app_id / X11 WM_CLASS, so a tiling WM's window rules can target
    // RetroPlug (e.g. Hyprland `windowrulev2 = tile, class:(RetroPlug)`). Set before SDL_Init.
    SDL_SetHint(SDL_HINT_APP_NAME, "RetroPlug");
    // Audio is PortAudio now (not SDL) — init only video + gamepad here.
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) != 0) {
        std::fprintf(stderr, "[retroplug-sdl] SDL_Init failed: %s\n", SDL_GetError());
        return false;
    }
    a.fullscreen = std::getenv("RETROPLUG_SDL_FULLSCREEN") != nullptr;
    // Resizable (not a fixed-size toplevel) so a tiling WM tiles the window instead of auto-floating it, and a
    // floating window can be dragged to any size — the DPF standalone is resizable for exactly this reason. A
    // fullscreen handheld ignores the flag. The min-size floor mirrors the plugin's setGeometryConstraints.
    Uint32 winFlags = a.fullscreen ? SDL_WINDOW_FULLSCREEN : SDL_WINDOW_RESIZABLE;
    a.window = SDL_CreateWindow("RetroPlug", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                a.width, a.height, winFlags);
    if (!a.window) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateWindow failed: %s\n", SDL_GetError()); return false; }
    SDL_SetWindowMinimumSize(a.window, static_cast<int>(kMinWindowW), static_cast<int>(kMinWindowH));
    a.debugResize = std::getenv("RETROPLUG_DEBUG_RESIZE") != nullptr;

    // Seed the geometry-ownership state: fullscreen is WM-controlled from the start; arm the clamp baseline with
    // the initial size so the FIRST compositor resize that differs (a tile) is recognised as a WM takeover.
    //
    // Wayland is WM-controlled too, always. On X11 a resize request is VERIFIABLE: SDL_SetWindowSize round-trips
    // it and reports back the geometry the WM actually granted (X11_SetWindowSize waits on the server, then
    // sends RESIZED with the real size), so a WM that refuses is detected and adopted by onWindowSizeChanged.
    // Wayland has no such feedback - xdg-shell has no client resize request at all: we simply commit the size
    // we want, and the compositor either goes along with it (mutter/kwin) or keeps its own box and SCALES our
    // now-mismatched surface into it, sending nothing either way. Under a compositor that owns geometry
    // (Hyprland, sway, every tiling compositor) that scaling is what stretched a freshly loaded tile across the
    // whole window until the next real configure - a user resize - put surface and window back in step. Since
    // "honored" and "ignored" are indistinguishable from here, we don't guess: the compositor owns the window
    // and the UI fits its grid via zoom. RETROPLUG_SDL_FIT_WINDOW=1 opts back into driving the window size on a
    // compositor known to honor it.
    const char* videoDriver = SDL_GetCurrentVideoDriver();
    const bool  wayland     = videoDriver && SDL_strcmp(videoDriver, "wayland") == 0;
    const bool  forceFit    = std::getenv("RETROPLUG_SDL_FIT_WINDOW") != nullptr;
    a.wmControlled = a.fullscreen || (wayland && !forceFit);
    a.requestedW = a.width;
    a.requestedH = a.height;
    if (a.debugResize)
        std::fprintf(stderr, "[retroplug-sdl] video driver '%s' - window geometry %s\n",
                     videoDriver ? videoDriver : "?", a.wmControlled ? "owned by the WM" : "ours to size");
    a.renderer = SDL_CreateRenderer(a.window, -1, SDL_RENDERER_SOFTWARE);
    if (!a.renderer) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateRenderer failed: %s\n", SDL_GetError()); return false; }
    a.texture = SDL_CreateTexture(a.renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING,
                                  a.width, a.height);
    if (!a.texture) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateTexture failed: %s\n", SDL_GetError()); return false; }

    // Audio: init PortAudio, apply any persisted rate/block (the Audio settings submenu), then open the stream
    // before boot so the obtained rate seeds the Engine. Where no device opens (headless), openAudio leaves it
    // muted and startAudio runs the fallback pump so the emulator still advances (see audioPumpLoop).
    if (const PaError pe = Pa_Initialize(); pe != paNoError)
        std::fprintf(stderr, "[retroplug-sdl] Pa_Initialize failed: %s (running muted)\n", Pa_GetErrorText(pe));
    loadAudioConfig(a);
    openAudio(a);
    return true;
}

void present(AppState& a) {
    if (!a.dirty) return; // nothing redrew this frame — leave the screen as-is (huge idle CPU saving)
    const int stride = static_cast<int>(lv_draw_buf_width_to_stride(a.width, lv_display_get_color_format(a.display)));
    // Upload only the changed region (clamped) from the draw buffer; the streaming texture keeps the rest.
    int x1 = std::max(0, (int)a.dirtyRect.x1), y1 = std::max(0, (int)a.dirtyRect.y1);
    int x2 = std::min((int)a.width - 1, (int)a.dirtyRect.x2), y2 = std::min((int)a.height - 1, (int)a.dirtyRect.y2);
    if (x2 >= x1 && y2 >= y1) {
        SDL_Rect rect{x1, y1, x2 - x1 + 1, y2 - y1 + 1};
        const std::uint8_t* src = a.drawBuf.data() + static_cast<std::size_t>(y1) * stride + static_cast<std::size_t>(x1) * 4;
        SDL_UpdateTexture(a.texture, &rect, src, stride);
    }
    SDL_RenderCopy(a.renderer, a.texture, nullptr, nullptr);
    SDL_RenderPresent(a.renderer);
    a.dirty = false;
}

// Adopt an actual window size — resize every dimension-tracking resource in lockstep: the SDL window (only
// when WE initiated it; a WM-driven change already sized the window), the LVGL display resolution + its
// DIRECT-mode draw buffer, and the streaming SDL texture (a STREAMING texture can't resize in place —
// recreate it). Then force a full-window redraw and tell the UI so it re-lays-out. This inlines what DPF's
// platform resize callback does for the plugin (LVGL::recreateTextureData + emit "resize").
void applyWindowSize(AppState& a, std::uint32_t w, std::uint32_t h, bool fromWm) {
    if (!a.window || !a.display || !a.renderer) return;
    if (w == a.width && h == a.height && a.texture) return; // already at this size — nothing to realloc

    if (!fromWm) SDL_SetWindowSize(a.window, static_cast<int>(w), static_cast<int>(h)); // ask the WM

    // LVGL display: set the new resolution, then re-point it at a freshly sized DIRECT buffer.
    const lv_color_format_t cf = lv_display_get_color_format(a.display);
    const std::uint32_t stride = lv_draw_buf_width_to_stride(w, cf);
    a.drawBuf.assign(static_cast<std::size_t>(stride) * h, 0);
    lv_display_set_resolution(a.display, w, h);
    lv_display_set_buffers(a.display, a.drawBuf.data(), nullptr, a.drawBuf.size(), LV_DISPLAY_RENDER_MODE_DIRECT);

    // SDL streaming texture: recreate at the new size (can't be resized in place).
    if (a.texture) SDL_DestroyTexture(a.texture);
    a.texture = SDL_CreateTexture(a.renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING,
                                  static_cast<int>(w), static_cast<int>(h));

    a.width = w;
    a.height = h;
    a.dirty = true; // present the whole new surface next frame (lv_timer_handler redraws into the new buffer)
    a.dirtyRect = {0, 0, static_cast<std::int32_t>(w) - 1, static_cast<std::int32_t>(h) - 1};

    if (JSContext* ctx = a.ui.getContext()) { // mirror PluginUI::onResize → the UI re-reads Dimensions.window
        JSValue args[2] = {JS_NewUint32(ctx, w), JS_NewUint32(ctx, h)};
        a.ui.emit("resize", 2, args);
        JS_FreeValue(ctx, args[0]);
        JS_FreeValue(ctx, args[1]);
    }
}

// The __rp_setWindowSize seam: the UI asks the WM for a w×h window (grow/shrink to the grid). Mirrors
// PluginUI::requestWindowSize — record the request as the clamp baseline, but don't fight a WM that owns
// geometry (a tiling compositor or a fullscreen handheld); there the UI fits its grid via zoom instead.
void requestWindowSize(AppState& a, std::uint32_t w, std::uint32_t h) {
    // Clamp to the window minimum FIRST, because SDL_SetWindowSize does: a 1x/2x grid (160x144 / 320x288) is
    // below the floor, so the window can only ever become 480x432. Applying the raw request would size the
    // LVGL surface to something the window never takes - and a surface that doesn't match the window is
    // exactly what a compositor scales to fit, which is how a freshly loaded tile ended up stretched across
    // the whole window. The clamped size also has to be what we RECORD, or it comes back through
    // onWindowSizeChanged as "a size we never asked for", i.e. a tiling takeover, wrongly latching
    // wmControlled and killing fit-to-grid for the rest of the session.
    w = std::max(w, kMinWindowW);
    h = std::max(h, kMinWindowH);
    a.requestedW = w; // recorded even when WM-controlled, so onWindowSizeChanged can still latch sizeHonored
    a.requestedH = h;
    if (a.wmControlled) {
        if (a.debugResize)
            std::fprintf(stderr, "[retroplug-sdl] resize request %ux%u ignored (WM owns geometry)\n", w, h);
        return;
    }
    applyWindowSize(a, w, h, /*fromWm=*/false);
}

// SDL_WINDOWEVENT_SIZE_CHANGED: the actual window size changed (our SDL_SetWindowSize, a user drag, or a
// tiling-WM tile). Mirrors PluginUI::onResize — latch sizeHonored when the WM grants a size we asked for
// (proof the window is floating, ours to size), and detect a tiling takeover: a size we never requested,
// before any request was ever honored, means the compositor owns geometry, so latch wmControlled and stop
// driving SDL_SetWindowSize (fullscreen is already wmControlled). Then adopt the new size.
void onWindowSizeChanged(AppState& a, std::uint32_t w, std::uint32_t h) {
    if (a.requestedW != 0 && a.requestedH != 0 && w == a.requestedW && h == a.requestedH) a.sizeHonored = true;
    if (!a.wmControlled && !a.sizeHonored && a.requestedW != 0 && a.requestedH != 0 &&
        (w != a.requestedW || h != a.requestedH)) {
        a.wmControlled = true;
        if (a.debugResize)
            std::fprintf(stderr, "[retroplug-sdl] WM owns geometry (tiled): got %ux%u, never asked for it\n", w, h);
    }
    if (a.debugResize)
        std::fprintf(stderr, "[retroplug-sdl] onResize %ux%u (req %ux%u wmC=%d honored=%d)\n", w, h, a.requestedW,
                     a.requestedH, (int)a.wmControlled, (int)a.sizeHonored);
    applyWindowSize(a, w, h, /*fromWm=*/true);
}

void handleEvents(AppState& a) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        switch (ev.type) {
            // OS window-close (window button / WM / Ctrl-C) → route through the unsaved-changes guard, exactly
            // as the DPF standalone's PluginUI::onClose does (and the Exit menu row already does via JS). The
            // JS guard returns true to veto (it raises the save prompt and later calls __rp_quitWindow itself
            // once the user confirms Save/Discard); false = clean project, quit now. Without this, closing a
            // dirty project by the window button would skip the prompt and lose work.
            case SDL_QUIT: {
                bool veto = false;
                if (JSContext* ctx = a.ui.getContext()) {
                    JSValue global = JS_GetGlobalObject(ctx);
                    JSValue fn     = JS_GetPropertyStr(ctx, global, "__rp_onCloseRequested");
                    if (JS_IsFunction(ctx, fn)) {
                        JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 0, nullptr);
                        veto = JS_ToBool(ctx, ret) == 1;
                        JS_FreeValue(ctx, ret);
                    }
                    JS_FreeValue(ctx, fn);
                    JS_FreeValue(ctx, global);
                }
                if (!veto) a.running = false;
                break;
            }
            // Desktop drag-and-drop → the "file-drop" JS bus (mirrors PluginUI::uiFileDropped). SDL2's
            // SDL_DropEvent carries no coordinates (the x/y fields are SDL3-only) and one path per event, so
            // we batch across begin→complete and read the cursor ourselves for the tile hit-test.
            case SDL_DROPBEGIN: a.dropBatch.clear(); break;
            case SDL_DROPFILE:
                if (ev.drop.file) { a.dropBatch.emplace_back(ev.drop.file); SDL_free(ev.drop.file); }
                break;
            case SDL_DROPCOMPLETE:
                if (JSContext* ctx = a.ui.getContext(); ctx && !a.dropBatch.empty()) {
                    std::string joined;
                    for (const std::string& p : a.dropBatch) { if (!joined.empty()) joined += '\n'; joined += p; }
                    int mx = 0, my = 0;
                    SDL_GetMouseState(&mx, &my); // window-pixel space — the coords hitTestTile expects (best-effort)
                    JSValue args[3] = {JS_NewString(ctx, joined.c_str()),
                                       JS_NewFloat64(ctx, mx), JS_NewFloat64(ctx, my)};
                    a.ui.emit("file-drop", 3, args);
                    for (JSValue& v : args) JS_FreeValue(ctx, v);
                }
                a.dropBatch.clear();
                break;
            case SDL_KEYDOWN:
            case SDL_KEYUP: {
                std::uint32_t lv, dpf;
                if (mapSdlKey(ev.key.keysym.sym, lv, dpf)) feedKey(a, lv, dpf, ev.type == SDL_KEYDOWN);
                break;
            }
            // The WM/user resized the window (a drag-grip resize, or a tiling compositor tiling us) → adopt the
            // new size + run the tiling-clamp detection. SIZE_CHANGED fires for both API- and WM-driven changes.
            case SDL_WINDOWEVENT:
                if (ev.window.event == SDL_WINDOWEVENT_SIZE_CHANGED)
                    onWindowSizeChanged(a, static_cast<std::uint32_t>(ev.window.data1),
                                        static_cast<std::uint32_t>(ev.window.data2));
                break;
            case SDL_MOUSEMOTION: a.input.mousePos = {ev.motion.x, ev.motion.y}; break;
            case SDL_MOUSEBUTTONDOWN:
            case SDL_MOUSEBUTTONUP:
                a.input.mousePos = {ev.button.x, ev.button.y};
                a.input.mouseDown = ev.type == SDL_MOUSEBUTTONDOWN;
                break;
            default: break;
        }
    }
}

} // namespace

int main(int argc, char** argv) {
    AppState app;
    g_app = &app;

    // --- args / env ---
    std::string autoloadPath;
    if (const char* env = std::getenv("RETROPLUG_AUTOLOAD_PROJECT")) autoloadPath = env;
    long exitAfterFrames = 0;
    if (const char* env = std::getenv("RETROPLUG_SDL_EXIT_AFTER_FRAMES")) exitAfterFrames = std::atol(env);
    std::string screenshotPath;
    if (const char* env = std::getenv("RETROPLUG_SDL_SCREENSHOT")) screenshotPath = env;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--autoload" && i + 1 < argc) autoloadPath = argv[++i];
        else if (arg == "--width" && i + 1 < argc) app.width = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        else if (arg == "--height" && i + 1 < argc) app.height = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        // Default audio block size (frames). The compiled-in default is 512 (low latency); a low-power device
        // passes a bigger buffer here (the muOS launcher uses 4096) so the callback keeps its deadline. Parsed
        // before setupSdl → loadAudioConfig, so a saved audio.json (an explicit Settings > Audio pick) still wins.
        else if (arg == "--block-size" && i + 1 < argc) { const int b = std::atoi(argv[++i]); if (b > 0) app.reqBlockSize = b; }
        else if (arg == "--screenshot" && i + 1 < argc) screenshotPath = argv[++i];
    }

    if (!setupSdl(app)) return 1;
    if (!bootControlPlane(app)) return 1;

    // Autoload a .rplg project before the audio thread takes the Engine (structural build runs direct).
    if (!autoloadPath.empty()) {
        const std::string ok = callGlobal(app.host, "__rp_loadProjectPath", autoloadPath.c_str());
        std::fprintf(stderr, "[retroplug-sdl] autoload %s -> %s\n", autoloadPath.c_str(), ok.empty() ? "false/void" : ok.c_str());
    }

    if (!setupUi(app)) return 1;

    // Open MIDI (virtual in/out ports). Non-fatal: the host runs without MIDI if none is available. The
    // audio callback drains app.midi into the Engine per block (see audioCb); RETROPLUG_MIDI_LOG logs input.
    // Apply any persisted device selection (Settings > MIDI) first, so open() connects the chosen device(s)
    // rather than the auto-all-inputs / virtual-only-output default.
    loadMidiConfig(app);
    app.midi.open("RetroPlug");

    // Test/diagnostic hook: dump the enumerated hardware MIDI devices then continue.
    if (std::getenv("RETROPLUG_SDL_MIDI_LIST")) {
        for (const auto& n : app.midi.listInputs())  std::fprintf(stderr, "[retroplug-sdl] MIDI in device:  '%s'\n", n.c_str());
        for (const auto& n : app.midi.listOutputs()) std::fprintf(stderr, "[retroplug-sdl] MIDI out device: '%s'\n", n.c_str());
    }

    // Hand the Engine to the audio thread (control-plane edits become push-only, drained per block) then start
    // it. Mirrors PluginDSP::activate. startAudio runs the PortAudio stream, or the fallback pump when muted.
    app.invoker.setAudioThreadOwns(true);
#if defined(__linux__)
    pinUiThreadAwayFromAudioCore(); // keep the 60 fps UI/emulator work off the audio thread's core
#endif
    startAudio(app);

    std::fprintf(stderr, "[retroplug-sdl] running %ux%u @ %.0f Hz\n", app.width, app.height, app.sampleRate);

    // Test hook: inject a MIDI message into the input ring (no hardware needed) to prove the audio-thread
    // drain path (ring -> audioCb poll -> engine.stageMidi). The staged count is printed on exit.
    if (std::getenv("RETROPLUG_SDL_MIDI_SELFTEST")) {
        const std::uint8_t noteOn[3] = { 0x90, 60, 100 };  // ch1 NoteOn C4
        app.midi.injectForTest(noteOn, 3);
    }

    // Test hook: exercise a live audio reconfigure (device close/reopen + engine re-rate) headlessly.
    if (std::getenv("RETROPLUG_SDL_TEST_RECONFIG")) {
        reconfigureAudio(app, 44100, 512, app.reqOutChannels, app.reqHostApi);
        std::fprintf(stderr, "[retroplug-sdl] post-reconfigure: %d Hz, %d frames, stream=%s\n",
                     app.reqSampleRate, app.reqBlockSize, app.audioStream ? "open" : "muted");
    }

    // Test hook: reconfigure to a wide output (RETROPLUG_SDL_TEST_MULTIOUT=<N ch>) and report the obtained
    // channel count — proves the N-channel device open + planar multi-out render + interleave stride.
    if (const char* env = std::getenv("RETROPLUG_SDL_TEST_MULTIOUT")) {
        const int ch = std::atoi(env);
        reconfigureAudio(app, app.reqSampleRate, app.reqBlockSize, ch, app.reqHostApi);
        std::fprintf(stderr, "[retroplug-sdl] post-multiout: numOutputs=%d planarBufs=%zu stream=%s\n",
                     app.numOutputs, app.audioPlanar.size(), app.audioStream ? "open" : "muted");
    }

    // Test hook: exercise the window resize path (SDL window + LVGL display/buffer + texture) headlessly,
    // the same call the __rp_setWindowSize seam makes. RETROPLUG_SDL_TEST_RESIZE=WxH.
    if (const char* env = std::getenv("RETROPLUG_SDL_TEST_RESIZE")) {
        int w = 0, h = 0;
        if (std::sscanf(env, "%dx%d", &w, &h) == 2 && w > 0 && h > 0) {
            requestWindowSize(app, static_cast<std::uint32_t>(w), static_cast<std::uint32_t>(h));
            int ww = 0, wh = 0;
            SDL_GetWindowSize(app.window, &ww, &wh);
            // wmControlled is printed too: a request the WM clamps or refuses must not be mistaken for a
            // tiling takeover (see requestWindowSize), and that's only observable through this latch.
            std::fprintf(stderr, "[retroplug-sdl] post-resize: state=%ux%u window=%dx%d buf=%zu wmControlled=%d\n",
                         app.width, app.height, ww, wh, app.drawBuf.size(), (int)app.wmControlled);
        }
    }

    // Test hook: push an OS-close (SDL_QUIT) so the close-guard path runs headlessly. With no unsaved
    // changes the guard doesn't veto, so the app exits on the first handleEvents (well before exitAfterFrames).
    if (std::getenv("RETROPLUG_SDL_TEST_QUIT")) {
        SDL_Event q; q.type = SDL_QUIT; SDL_PushEvent(&q);
    }

    // Test hook: drive the MIDI-clock → transport estimator with a synthetic clock at RETROPLUG_SDL_TEST_CLOCK
    // BPM and report the derived tempo/transport (deterministic — no wall-clock dependence).
    if (const char* env = std::getenv("RETROPLUG_SDL_TEST_CLOCK")) {
        double target = std::atof(env);
        if (target <= 0.0) target = 140.0;
        MidiClockSync cs;
        cs.sampleRate = app.sampleRate;
        const long long framesPerPulse = static_cast<long long>(app.sampleRate * 60.0 / (target * 24.0));
        for (int i = 0; i < 48; ++i) { cs.onByte(0xF8); cs.advance(framesPerPulse); } // 2 quarter-notes of clock
        const double derived = cs.outBpm();
        const bool playing = cs.outPlaying();
        cs.onByte(0xFC); cs.advance(framesPerPulse);          // explicit stop
        const bool afterStop = cs.outPlaying();
        for (int i = 0; i < 64; ++i) cs.advance(framesPerPulse); // long clock silence → free-run revert
        std::fprintf(stderr, "[retroplug-sdl] clock self-test: target=%.1f derived=%.1f playing=%d afterStop=%d "
                     "afterTimeout(bpm=%.1f playing=%d)\n",
                     target, derived, (int)playing, (int)afterStop, cs.outBpm(), (int)cs.outPlaying());
    }

    // --- the 60 fps loop: input → JS frame → LVGL render → present ---
    const bool requireNonBlank = std::getenv("RETROPLUG_SDL_REQUIRE_NONBLANK") != nullptr;
    bool nonBlankFail = false;
    long frame = 0;
    while (app.running) {
        const Uint32 t0 = SDL_GetTicks();
        handleEvents(app);
        pollFileDialog(app);    // deliver a finished OS file-dialog pick (async; no-op when none is open)
        if (JSContext* ctx = app.ui.getContext()) {
            app.ui.emit("frame", 0, nullptr); // drives EmulatorTile's getFrame
            pumpGamepad(app);
            (void)ctx;
        }
        app.ui.tick();          // pump the shared host's JS/libuv loop
        lv_timer_handler();     // LVGL indev read + layout + render into drawBuf
        present(app);

        if (exitAfterFrames > 0 && frame + 1 == exitAfterFrames) { // last frame: screenshot + non-blank gate
            if (!screenshotPath.empty()) writeScreenshot(app, screenshotPath);
            if (requireNonBlank && frameIsBlank(app)) {
                nonBlankFail = true;
                std::fprintf(stderr, "[retroplug-sdl] non-blank check FAILED: frame is flat (UI did not render)\n");
            }
        }
        if (exitAfterFrames > 0 && ++frame >= exitAfterFrames) app.running = false;

        const Uint32 dt = SDL_GetTicks() - t0;
        if (dt < 16) SDL_Delay(16 - dt); // ~60 fps
    }
    if (std::getenv("RETROPLUG_SDL_TEST_QUIT"))
        std::fprintf(stderr, "[retroplug-sdl] close-guard test: exited at frame %ld\n", frame);

    // --- teardown: reclaim the Engine, unmount, drop SDL ---
    stopAudio(app); // Pa_StopStream (joins the callback) or stop+join the fallback pump
    if (app.audioStream) { Pa_CloseStream(app.audioStream); app.audioStream = nullptr; }
    Pa_Terminate();
    if (std::getenv("RETROPLUG_SDL_MIDI_SELFTEST"))
        std::fprintf(stderr, "[retroplug-sdl] MIDI self-test: staged %llu message(s) into the Engine\n",
                     static_cast<unsigned long long>(app.midiStaged.load(std::memory_order_relaxed)));
    app.midi.close();
    app.invoker.setAudioThreadOwns(false);
    app.invoker.drainInto(app.engine);
    app.invoker.reclaimReleased();

    // Tear the UI down in the order the LVGL lifecycle expects. Disable invalidation FIRST so the widget
    // deletes below don't walk styles into freed memory (lv_obj_invalidate early-outs). Then detachDisplay()
    // unmounts React + async-deletes every widget (and the window root); a single lv_timer_handler() flushes
    // that async-delete queue. Do NOT lv_obj_clean(screen) beforehand — that deletes the same widgets
    // synchronously, so the async deletes detachDisplay queued then run over freed objects (a UAF that
    // survives on Linux's allocator but is a hard EXC_BAD_ACCESS on macOS / under MALLOC_PERTURB_).
    if (app.display) lv_display_enable_invalidation(app.display, false);
    app.ui.detachDisplay();
    lv_timer_handler();

    if (app.texture) SDL_DestroyTexture(app.texture);
    if (app.renderer) SDL_DestroyRenderer(app.renderer);
    if (app.window) SDL_DestroyWindow(app.window);
    SDL_Quit();
    g_app = nullptr;
    return nonBlankFail ? 2 : 0; // exit 2 = the RETROPLUG_SDL_REQUIRE_NONBLANK gate failed (blank UI)
}

namespace {
bool writeScreenshot(AppState& a, const std::string& path) {
    if (!a.display || a.drawBuf.empty()) return false;
    const std::uint32_t w = a.width, h = a.height;
    const std::uint32_t stride = lv_draw_buf_width_to_stride(w, lv_display_get_color_format(a.display));
    std::vector<unsigned char> rgb(static_cast<std::size_t>(w) * h * 3);
    for (std::uint32_t y = 0; y < h; ++y)
        for (std::uint32_t x = 0; x < w; ++x) {
            const std::uint8_t* px = a.drawBuf.data() + static_cast<std::size_t>(y) * stride + x * 4;
            unsigned char* out = rgb.data() + (static_cast<std::size_t>(y) * w + x) * 3;
            out[0] = px[2]; out[1] = px[1]; out[2] = px[0]; // ARGB8888 (B,G,R,A) -> R,G,B
        }
    const unsigned err = lodepng_encode24_file(path.c_str(), rgb.data(), w, h);
    if (err) { std::fprintf(stderr, "[retroplug-sdl] screenshot error %u\n", err); return false; }
    std::fprintf(stderr, "[retroplug-sdl] screenshot -> %s (%ux%u)\n", path.c_str(), w, h);
    return true;
}
} // namespace
