// retroplug-sdl — the standalone RetroPlug for framebuffer handhelds (Anbernic / muOS) and any plain
// Linux desktop, hosted on SDL2 instead of DPF/pugl. muOS has no X11 (fbdev + Mali EGL only), so the
// DPF JACK standalone — whose window comes from pugl's X11-only Linux backend — can't run there. This
// host reuses the ENTIRE core (retroplug-backend Engine + cores + txiki runtime, and the SAME embedded
// control-plane + React/LVGL UI bytecode the plugin ships) and swaps only the thin shell:
//
//   * window + present : SDL2 software renderer (LVGL renders into a CPU ARGB8888 buffer; we upload it
//                        with SDL_UpdateTexture + SDL_RenderCopy — SDL drives Mali GLES2 internally, so
//                        no manual GL, no desktop-GL-over-Mali fuss).
//   * audio            : an SDL2 audio callback that drives Engine::processBlock per block (mirrors
//                        PluginDSP::run / AudioDriverRpcService::audioLoop, minus DPF).
//   * input            : SDL keyboard → the LVGL keypad indev + the "key" JS bus; GamepadManager →
//                        the gamepad-* JS bus (emulator input / TS bindings) AND the keypad indev
//                        (menu navigation, since a handheld has no arrow keys).
//
// It composes PluginDSP's control-plane boot (the backend service graph + __rpcSend on
// Symbol.for("plugin") + the cp bundle) and PluginUI's mount (the UI bundle + LVGL display) onto ONE
// TjsHostRuntime, exactly as the DPF plugin splits them across its DSP and UI halves. The non-GL LVGL
// setup mirrors packages/native/test/ui/RenderCore.cpp; the boot mirrors plugin/PluginDSP.cpp.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <memory>
#include <string>
#include <vector>

#include <dirent.h>
#include <fnmatch.h>
#include <sys/stat.h>

#if defined(__linux__)
#include <atomic>
#include <pthread.h>
#include <sched.h>
#include <unistd.h>
#endif

#include <SDL.h>

extern "C" {
#include "lvgl.h"
}

#include "dpfjs/LvglJsEngine.hpp"            // LVGL display layer over the shared txiki host
#include "dpfjs/host/TjsHostRuntime.hpp"     // shared txiki/QuickJS host (+ tjs.h/quickjs.h)

#include "host/engine/Engine.hpp"
#include "host/engine/EngineInvoker.hpp"
#include "host/input/GamepadManager.hpp"     // SDL controller poll (shared UI-thread input)
#include "host/rpc/BackendRpcRegistration.hpp"
#include "system/CoreBackends.hpp"
#include "system/SystemFactory.hpp"
#include "TypedRpcServer.h"
#include "codecs/QuickJSCodec.h"
#include "transports/QuickJSTransport.h"

#include "native/components/component.hpp"   // GetWindowInstance() — the lv_binding_js React-tree root
#include "native/core/img/png/lodepng.h"     // lodepng_encode24_file (headless screenshot proof)

// The embedded bytecode bundles (tjsc, rp_ prefix), generated by CMake — the SAME artifacts the plugin
// links: cp-bundle_data.c (control plane, composes stores + DSP kernel + __rp_* globals) and
// ui-bundle_data.c (the React UI, registers __rp_mountUI).
extern "C" {
extern const std::uint8_t  rp_cp_bundle[];
extern const std::uint32_t rp_cp_bundle_size;
extern const std::uint8_t  rp_ui_bundle[];
extern const std::uint32_t rp_ui_bundle_size;
}

// LVGL is built LV_GLOBAL_CUSTOM: the application must supply lv_global_default(). In the plugin DPF's
// LVGLWidget provides a per-instance one; standalone (single window, single runtime) we provide one
// process-wide instance, zero-initialized like DPF's calloc — lv_init() populates it. (Same pattern as
// RenderCore.cpp.)
extern "C" lv_global_t* lv_global_default(void) {
    static lv_global_t* g = static_cast<lv_global_t*>(std::calloc(1, sizeof(lv_global_t)));
    return g;
}

using BackendRpcServer = rpcpp::TypedRpcServer<rpcpp::Empty, rpcpp::QuickJSCodec>;

namespace {

// A native on-screen file browser (there is no OS file dialog on a handheld). Renders on LVGL's top
// layer — above the React UI, outside its tree — and is driven directly by the gamepad/keyboard, so it
// never touches the React focus system. Answers the UI's __rp_openFileBrowser and reports back via
// __rp_onFileBrowserResult (the resolver realBackend.ts installs).
struct Entry { std::string name; bool isDir; };
struct FileBrowser {
    bool active = false;
    lv_obj_t* overlay = nullptr;
    lv_obj_t* list = nullptr;
    lv_obj_t* titleLabel = nullptr;
    std::string title;
    std::string dir;
    std::vector<std::string> patterns; // globs, e.g. {"*.gb","*.gbc"}; empty = all files
    bool saving = false;
    std::vector<Entry> entries;        // current dir contents (".." first)
    std::vector<lv_obj_t*> rows;       // list buttons, parallel to entries
    int sel = 0;
};

// Whole-process state, reached by the LVGL indev read callbacks (via driver_data), the SDL audio
// callback (via userdata), and the __rp_* window hooks (single instance → a file-scope pointer is fine,
// unlike the plugin's per-context routing for multi-instance DAWs).
struct AppState {
    // --- the shared runtime + backend graph (PluginDSP's control plane) ---
    TjsHostRuntime host;
    Engine         engine;
    SystemFactory  factory;
    QueuedInvoker  invoker{engine, engine.registry()};
    HostRpcService   hostSvc;
    EngineRpcService engineSvc{engine, factory, invoker};
    std::unique_ptr<rpcpp::QuickJSTransport> transport;
    std::unique_ptr<BackendRpcServer>        server;

    // --- the UI display layer (PluginUI), on the SAME host ---
    LvglJsEngine  ui{host};   // external-host ctor: adds only the LVGL layer, never shuts host down
    lv_display_t* display = nullptr;
    std::vector<std::uint8_t> drawBuf;
    lv_group_t*   group = nullptr;
    lv_indev_t*   keypad = nullptr;
    lv_indev_t*   pointer = nullptr;

    // synthetic input state the indev read callbacks pull from
    std::deque<std::uint32_t> keyQueue;   // pending LVGL key codes (keypad indev)
    lv_point_t mousePos{0, 0};
    bool       mouseDown = false;

    FileBrowser fb;   // native file-picker overlay (answers __rp_openFileBrowser)

    // --- SDL shell ---
    SDL_Window*   window = nullptr;
    SDL_Renderer* renderer = nullptr;
    SDL_Texture*  texture = nullptr;
    SDL_AudioDeviceID audioDev = 0;
    retroplug::GamepadManager gamepad;

    std::uint32_t width = 640;
    std::uint32_t height = 480;
    bool running = true;

    // audio scratch (pre-sized to the device block, so the callback never allocates)
    std::vector<float> audioL, audioR;
    double sampleRate = 48000.0;   // obtained device rate (drives the Engine)
    int    reqSampleRate = 48000;  // requested (UI-configurable) rate + block, persisted to audio.cfg
    int    reqBlockSize  = 2048;

    // Present only when LVGL actually redrew: the flush cb unions the changed area here; the loop skips
    // the SDL texture upload + blit entirely on idle frames (a static menu → ~0% CPU instead of a full
    // 640×480 upload every frame). dirty starts true so the first frame always shows.
    bool dirty = true;
    lv_area_t dirtyRect{0, 0, 0, 0};
};

AppState* g_app = nullptr;  // single instance

// Audio device (re)configuration — defined after audioCb (they reference it); declared here so the
// __rp_setAudioConfig hook (bound earlier) can drive a live sample-rate / block-size change.
bool openAudio(AppState& a);
void reconfigureAudio(AppState& a, int sampleRate, int blockSize);
void loadAudioConfig(AppState& a);
void saveAudioConfig(AppState& a);

// ---- LVGL glue (mirrors RenderCore's non-GL subset) -----------------------------------------------

// Flush: in LV_DISPLAY_RENDER_MODE_DIRECT the draw buffer already holds the full rendered frame; we just
// record which region changed (union across the refresh's flush calls) so the loop uploads + presents
// only that rect, and skips presenting entirely when nothing changed.
void flushCb(lv_display_t* disp, const lv_area_t* area, uint8_t*) {
    if (g_app && area) {
        if (!g_app->dirty) { g_app->dirtyRect = *area; g_app->dirty = true; }
        else {
            g_app->dirtyRect.x1 = std::min(g_app->dirtyRect.x1, area->x1);
            g_app->dirtyRect.y1 = std::min(g_app->dirtyRect.y1, area->y1);
            g_app->dirtyRect.x2 = std::max(g_app->dirtyRect.x2, area->x2);
            g_app->dirtyRect.y2 = std::max(g_app->dirtyRect.y2, area->y2);
        }
    }
    lv_display_flush_ready(disp);
}

void keypadReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* a = static_cast<AppState*>(lv_indev_get_driver_data(indev));
    if (a && !a->keyQueue.empty()) {
        data->state = LV_INDEV_STATE_PRESSED;
        data->key   = a->keyQueue.front();
        a->keyQueue.pop_front();
        data->continue_reading = !a->keyQueue.empty();
    } else {
        data->state = LV_INDEV_STATE_RELEASED;
    }
}

void pointerReadCb(lv_indev_t* indev, lv_indev_data_t* data) {
    auto* a = static_cast<AppState*>(lv_indev_get_driver_data(indev));
    if (!a) { data->state = LV_INDEV_STATE_RELEASED; return; }
    data->point = a->mousePos;
    data->state = a->mouseDown ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
}

// LVGL's tick source: real wall-clock ms so timers/animations run in real time.
std::uint32_t sdlTicksCb(void) { return SDL_GetTicks(); }

// ---- backend boot (PluginDSP::bootControlPlane, DPF-free) ------------------------------------------

bool readReady(TjsHostRuntime& host) {
    JSContext* ctx = host.context();
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, "__rp_ready");
    const bool r = JS_ToBool(ctx, v) > 0;
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return r;
}

// Call globalThis[name](arg?) on the control-plane context (main thread). Returns the string result, or
// "" for non-string / missing / exception. Mirrors PluginDSP::callGlobal (used for autoload here).
std::string callGlobal(TjsHostRuntime& host, const char* name, const char* arg) {
    JSContext* ctx = host.context();
    JSValue g  = JS_GetGlobalObject(ctx);
    JSValue fn = JS_GetPropertyStr(ctx, g, name);
    std::string out;
    if (JS_IsFunction(ctx, fn)) {
        JSValue argv[1];
        int argc = 0;
        if (arg) { argv[0] = JS_NewString(ctx, arg); argc = 1; }
        JSValue ret = JS_Call(ctx, fn, g, argc, argc ? argv : nullptr);
        if (argc) JS_FreeValue(ctx, argv[0]);
        if (JS_IsException(ret)) {
            JSValue exc = JS_GetException(ctx);
            const char* s = JS_ToCString(ctx, exc);
            std::fprintf(stderr, "[retroplug-sdl] %s threw: %s\n", name, s ? s : "?");
            if (s) JS_FreeCString(ctx, s);
            JS_FreeValue(ctx, exc);
        } else if (JS_IsString(ret)) {
            const char* s = JS_ToCString(ctx, ret);
            if (s) { out = s; JS_FreeCString(ctx, s); }
        } else if (JS_IsBool(ret)) {
            out = JS_ToBool(ctx, ret) > 0 ? "true" : "false";
        }
        JS_FreeValue(ctx, ret);
    }
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, g);
    return out;
}

bool hasGlobalFunction(JSContext* ctx, const char* name) {
    JSValue g = JS_GetGlobalObject(ctx);
    JSValue v = JS_GetPropertyStr(ctx, g, name);
    const bool ok = JS_IsFunction(ctx, v);
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, g);
    return ok;
}

// ---- native file browser ---------------------------------------------------------------------------

// Report the pick (or null on cancel) back to the UI via the resolver realBackend.ts installed.
void fbResult(AppState& a, const char* path) {
    JSContext* ctx = a.ui.getContext();
    if (!ctx) return;
    JSValue g  = JS_GetGlobalObject(ctx);
    JSValue fn = JS_GetPropertyStr(ctx, g, "__rp_onFileBrowserResult");
    if (JS_IsFunction(ctx, fn)) {
        JSValue arg = path ? JS_NewString(ctx, path) : JS_NULL;
        JSValue ret = JS_Call(ctx, fn, JS_UNDEFINED, 1, &arg);
        JS_FreeValue(ctx, ret);
        JS_FreeValue(ctx, arg);
    }
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, g);
}

bool fbMatches(const std::string& name, const std::vector<std::string>& pats) {
    if (pats.empty()) return true;
    for (const auto& p : pats)
        if (fnmatch(p.c_str(), name.c_str(), FNM_CASEFOLD) == 0) return true;
    return false;
}

void fbHighlight(AppState& a) {
    for (int i = 0; i < (int)a.fb.rows.size(); ++i) {
        lv_obj_t* r = a.fb.rows[i];
        if (i == a.fb.sel) {
            lv_obj_set_style_bg_color(r, lv_color_hex(0x1e5aa8), 0);
            lv_obj_set_style_bg_opa(r, LV_OPA_COVER, 0);
            lv_obj_scroll_to_view(r, LV_ANIM_OFF);
        } else {
            lv_obj_set_style_bg_opa(r, LV_OPA_TRANSP, 0);
        }
    }
}

void fbPopulate(AppState& a) {
    if (a.fb.list) lv_obj_clean(a.fb.list);
    a.fb.entries.clear();
    a.fb.rows.clear();

    if (a.fb.dir != "/") a.fb.entries.push_back({"..", true});

    std::vector<Entry> dirs, files;
    if (DIR* d = opendir(a.fb.dir.c_str())) {
        while (struct dirent* e = readdir(d)) {
            std::string n = e->d_name;
            if (n == "." || n == ".." || (!n.empty() && n[0] == '.')) continue; // skip . .. hidden
            struct stat st;
            const std::string full = a.fb.dir + "/" + n;
            const bool isdir = stat(full.c_str(), &st) == 0 && S_ISDIR(st.st_mode);
            if (isdir) dirs.push_back({n, true});
            else if (fbMatches(n, a.fb.patterns)) files.push_back({n, false});
        }
        closedir(d);
    }
    const auto byName = [](const Entry& x, const Entry& y) { return x.name < y.name; };
    std::sort(dirs.begin(), dirs.end(), byName);
    std::sort(files.begin(), files.end(), byName);
    a.fb.entries.insert(a.fb.entries.end(), dirs.begin(), dirs.end());
    a.fb.entries.insert(a.fb.entries.end(), files.begin(), files.end());

    for (const Entry& en : a.fb.entries) {
        const char* icon = en.isDir ? LV_SYMBOL_DIRECTORY : LV_SYMBOL_FILE;
        const std::string label = en.name + (en.isDir && en.name != ".." ? "/" : "");
        lv_obj_t* btn = lv_list_add_button(a.fb.list, icon, label.c_str());
        lv_obj_set_style_radius(btn, 0, 0);
        lv_obj_set_style_border_width(btn, 0, 0);
        a.fb.rows.push_back(btn);
    }
    a.fb.sel = 0;
    if (a.fb.titleLabel)
        lv_label_set_text(a.fb.titleLabel, (a.fb.title + "   " + a.fb.dir).c_str());
    fbHighlight(a);
}

void fbClose(AppState& a) {
    if (a.fb.overlay) { lv_obj_delete(a.fb.overlay); a.fb.overlay = nullptr; }
    a.fb.list = nullptr; a.fb.titleLabel = nullptr;
    a.fb.rows.clear(); a.fb.entries.clear();
    a.fb.active = false;
}

void fbOpen(AppState& a, const char* title, const char* patternsStr, bool saving) {
    if (a.fb.active) return; // one dialog at a time
    a.fb.title  = (title && *title) ? title : "Select file";
    a.fb.saving = saving;
    a.fb.patterns.clear();
    if (patternsStr) { // split on whitespace
        std::string cur;
        for (const char* p = patternsStr; *p; ++p) {
            if (*p == ' ' || *p == '\t') { if (!cur.empty()) { a.fb.patterns.push_back(cur); cur.clear(); } }
            else cur += *p;
        }
        if (!cur.empty()) a.fb.patterns.push_back(cur);
    }
    const auto isdir = [](const char* p) { struct stat st; return stat(p, &st) == 0 && S_ISDIR(st.st_mode); };
    if (isdir("/mnt/mmc/ROMS")) a.fb.dir = "/mnt/mmc/ROMS";
    else if (isdir("/mnt/mmc")) a.fb.dir = "/mnt/mmc";
    else if (const char* h = std::getenv("HOME"); h && isdir(h)) a.fb.dir = h;
    else a.fb.dir = "/";

    lv_obj_t* top = lv_layer_top();
    a.fb.overlay = lv_obj_create(top);
    lv_obj_remove_style_all(a.fb.overlay);
    lv_obj_set_size(a.fb.overlay, lv_pct(100), lv_pct(100));
    lv_obj_set_style_bg_color(a.fb.overlay, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(a.fb.overlay, LV_OPA_COVER, 0);
    lv_obj_set_flex_flow(a.fb.overlay, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(a.fb.overlay, 4, 0);

    a.fb.titleLabel = lv_label_create(a.fb.overlay);
    lv_obj_set_style_text_color(a.fb.titleLabel, lv_color_hex(0x4aa3ff), 0);
    lv_label_set_long_mode(a.fb.titleLabel, LV_LABEL_LONG_DOT);
    lv_obj_set_width(a.fb.titleLabel, lv_pct(100));

    a.fb.list = lv_list_create(a.fb.overlay);
    lv_obj_set_width(a.fb.list, lv_pct(100));
    lv_obj_set_flex_grow(a.fb.list, 1);
    lv_obj_set_style_bg_color(a.fb.list, lv_color_hex(0x000000), 0);
    lv_obj_set_style_border_width(a.fb.list, 0, 0);
    lv_obj_set_style_pad_all(a.fb.list, 0, 0);

    a.fb.active = true;
    fbPopulate(a);
}

void fbMove(AppState& a, int delta) {
    if (a.fb.entries.empty()) return;
    a.fb.sel = std::max(0, std::min((int)a.fb.entries.size() - 1, a.fb.sel + delta));
    fbHighlight(a);
}

void fbActivate(AppState& a) {
    if (a.fb.entries.empty()) return;
    const Entry en = a.fb.entries[a.fb.sel];
    if (en.name == "..") {
        const auto slash = a.fb.dir.find_last_of('/');
        a.fb.dir = (slash == 0 || slash == std::string::npos) ? "/" : a.fb.dir.substr(0, slash);
        fbPopulate(a);
        return;
    }
    const std::string full = (a.fb.dir == "/" ? std::string() : a.fb.dir) + "/" + en.name;
    if (en.isDir) { a.fb.dir = full; fbPopulate(a); return; }
    fbResult(a, full.c_str()); // a file — report + close
    fbClose(a);
}

void fbCancel(AppState& a) { fbResult(a, nullptr); fbClose(a); }

// Feed a gamepad button (raw SDL name) to the browser while it's open. Returns true (always consumes
// input while active). dpad = move, A = enter/descend, B = up/cancel.
void fbGamepad(AppState& a, const char* name, bool pressed) {
    if (!pressed || !name) return;
    if (!std::strcmp(name, "dpup"))        fbMove(a, -1);
    else if (!std::strcmp(name, "dpdown")) fbMove(a, 1);
    else if (!std::strcmp(name, "dpleft")) fbMove(a, -8); // page up
    else if (!std::strcmp(name, "dpright"))fbMove(a, 8);  // page down
    else if (!std::strcmp(name, "a"))      fbActivate(a);
    else if (!std::strcmp(name, "b")) {
        if (a.fb.dir != "/" && a.fb.dir != "/mnt/mmc" && a.fb.dir != "/mnt/mmc/ROMS") {
            // go up a level (B doubles as "up"); cancel only at the start dir
            const auto slash = a.fb.dir.find_last_of('/');
            a.fb.dir = (slash == 0 || slash == std::string::npos) ? "/" : a.fb.dir.substr(0, slash);
            fbPopulate(a);
        } else {
            fbCancel(a);
        }
    }
}

// ---- __rp_* window hooks (PluginUI's window-op seam, single-instance) ------------------------------
// The UI optional-chains these, so anything we omit is simply inert. We provide the handful a handheld
// standalone needs; the render-job hooks are left to a later milestone.

JSValue jsQuitWindow(JSContext*, JSValueConst, int, JSValueConst*) {
    if (g_app) g_app->running = false;
    return JS_UNDEFINED;
}
// Report the window as WM-controlled so the UI fits its grid via zoom instead of trying to resize a
// fixed fullscreen handheld window.
JSValue jsIsWindowSizeControlled(JSContext* ctx, JSValueConst, int, JSValueConst*) { return JS_NewBool(ctx, 1); }
JSValue jsSetWindowSize(JSContext*, JSValueConst, int, JSValueConst*) { return JS_UNDEFINED; }
JSValue jsSetWindowTitle(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && g_app->window && argc >= 1) {
        const char* t = JS_ToCString(ctx, argv[0]);
        if (t && *t) SDL_SetWindowTitle(g_app->window, t);
        if (t) JS_FreeCString(ctx, t);
    }
    return JS_UNDEFINED;
}
JSValue jsOpenPath(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (argc >= 1) {
        const char* p = JS_ToCString(ctx, argv[0]);
        if (p && *p) { const std::string cmd = "xdg-open \"" + std::string(p) + "\" &"; (void)std::system(cmd.c_str()); }
        if (p) JS_FreeCString(ctx, p);
    }
    return JS_UNDEFINED;
}

// __rp_getAudioConfig(): { sampleRate, blockSize } — the live standalone audio device config, for the
// Audio settings submenu to display the current values.
JSValue jsGetAudioConfig(JSContext* ctx, JSValueConst, int, JSValueConst*) {
    JSValue o = JS_NewObject(ctx);
    if (g_app) {
        JS_SetPropertyStr(ctx, o, "sampleRate", JS_NewInt32(ctx, g_app->reqSampleRate));
        JS_SetPropertyStr(ctx, o, "blockSize",  JS_NewInt32(ctx, g_app->reqBlockSize));
    }
    return o;
}

// __rp_setAudioConfig(sampleRate, blockSize): re-open the audio device with new params on the fly (and
// persist them). Reuses the deactivate→re-rate→reactivate handoff the plugin does for a host SR change.
JSValue jsSetAudioConfig(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (g_app && argc >= 2) {
        int sr = 0, bs = 0;
        JS_ToInt32(ctx, &sr, argv[0]);
        JS_ToInt32(ctx, &bs, argv[1]);
        if (sr > 0 && bs > 0) reconfigureAudio(*g_app, sr, bs);
    }
    return JS_UNDEFINED;
}

// __rp_openFileBrowser(title, patterns, saving, defaultName): open the native on-screen picker. The pick
// arrives later via __rp_onFileBrowserResult (matches the plugin's DPF dialog seam).
JSValue jsOpenFileBrowser(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (!g_app || argc < 3) return JS_UNDEFINED;
    const char* title    = JS_ToCString(ctx, argv[0]);
    const char* patterns = JS_ToCString(ctx, argv[1]);
    const int   saving   = JS_ToBool(ctx, argv[2]);
    fbOpen(*g_app, title ? title : "", patterns ? patterns : "", saving == 1);
    if (title) JS_FreeCString(ctx, title);
    if (patterns) JS_FreeCString(ctx, patterns);
    return JS_UNDEFINED;
}

void installWindowHooks(JSContext* ctx) {
    JSValue g = JS_GetGlobalObject(ctx);
    auto bind = [&](const char* name, JSCFunction* fn, int len) {
        JS_SetPropertyStr(ctx, g, name, JS_NewCFunction(ctx, fn, name, len));
    };
    bind("__rp_quitWindow", jsQuitWindow, 0);
    bind("__rp_isWindowSizeControlled", jsIsWindowSizeControlled, 0);
    bind("__rp_setWindowSize", jsSetWindowSize, 2);
    bind("__rp_setWindowTitle", jsSetWindowTitle, 1);
    bind("__rp_openPath", jsOpenPath, 1);
    bind("__rp_openFileBrowser", jsOpenFileBrowser, 4);
    bind("__rp_getAudioConfig", jsGetAudioConfig, 0);
    bind("__rp_setAudioConfig", jsSetAudioConfig, 2);
    // Mark this as a standalone host so the UI shows the "Exit" menu row (a DAW hides it).
    JS_SetPropertyStr(ctx, g, "__rp_isStandalone", JS_NewBool(ctx, 1));
    JS_FreeValue(ctx, g);
}

// ---- input translation ----------------------------------------------------------------------------

// Push an LVGL key onto the keypad queue AND emit the "key" JS bus (press+release), mirroring
// RenderCore::tapKey / PluginUI::onKeyboard. dpf is the DPF keycode the TS input layer expects.
void feedKey(AppState& a, std::uint32_t lvKey, std::uint32_t dpf, bool press) {
    JSContext* ctx = a.ui.getContext();
    if (press) a.keyQueue.push_back(lvKey);
    if (ctx) {
        JSValue args[2] = {JS_NewUint32(ctx, dpf), JS_NewBool(ctx, press)};
        a.ui.emit("key", 2, args);
        JS_FreeValue(ctx, args[0]);
        JS_FreeValue(ctx, args[1]);
    }
}

// Map an SDL keysym to (LVGL key, DPF keycode). Returns false for keys we don't translate.
bool mapSdlKey(SDL_Keycode k, std::uint32_t& lv, std::uint32_t& dpf) {
    switch (k) {
        case SDLK_UP:     lv = LV_KEY_UP;    dpf = 0xE036; return true;
        case SDLK_DOWN:   lv = LV_KEY_DOWN;  dpf = 0xE038; return true;
        case SDLK_RIGHT:  lv = LV_KEY_RIGHT; dpf = 0xE037; return true;
        case SDLK_LEFT:   lv = LV_KEY_LEFT;  dpf = 0xE035; return true;
        case SDLK_RETURN: lv = LV_KEY_ENTER; dpf = 0x0D;   return true;
        case SDLK_ESCAPE: lv = LV_KEY_ESC;   dpf = 0x1B;   return true;
        default: return false;
    }
}

// Poll controllers once per frame → re-emit each transition onto the gamepad-* JS bus (exactly as
// PluginUI::pumpGamepad). The gamepad drives BOTH menu navigation and in-game input purely through this
// bus: the React Menu has its own gamepad handler, and the design contract is that the gamepad bus never
// reaches the LVGL keypad indev (Menu.tsx). So we must NOT also translate gamepad → keypad here — doing
// so double-drives the menu (every move counted twice) while leaving in-game input single (the keypad
// keys hit the idle focus sink). Keyboard still feeds the keypad (mapSdlKey/feedKey) for desktop use.
void pumpGamepad(AppState& a) {
    JSContext* ctx = a.ui.getContext();
    if (!ctx) return;
    a.gamepad.update([&a, ctx](const retroplug::GamepadEvent& ev) {
        // While the native file browser is open it owns all input — drive it and never reach the React UI.
        if (a.fb.active) {
            if (ev.kind == retroplug::GamepadEvent::Kind::Button) fbGamepad(a, ev.button, ev.pressed);
            return;
        }
        switch (ev.kind) {
            case retroplug::GamepadEvent::Kind::Connected: {
                JSValue args[2] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.name ? ev.name : "")};
                a.ui.emit("gamepad-connected", 2, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Disconnected: {
                JSValue args[1] = {JS_NewInt32(ctx, ev.pad)};
                a.ui.emit("gamepad-disconnected", 1, args);
                JS_FreeValue(ctx, args[0]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Button: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.button ? ev.button : ""),
                                   JS_NewBool(ctx, ev.pressed)};
                a.ui.emit("gamepad-button", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                break;
            }
            case retroplug::GamepadEvent::Kind::Axis: {
                JSValue args[3] = {JS_NewInt32(ctx, ev.pad), JS_NewString(ctx, ev.axis ? ev.axis : ""),
                                   JS_NewFloat64(ctx, ev.value)};
                a.ui.emit("gamepad-axis", 3, args);
                JS_FreeValue(ctx, args[0]); JS_FreeValue(ctx, args[1]); JS_FreeValue(ctx, args[2]);
                break;
            }
        }
    });
}

// ---- audio-thread scheduling (A53 real-time headroom) ----------------------------------------------
#if defined(__linux__)
// The audio path runs at ~1x realtime on the A53 (the SameBoy APU is ~92% of every block), so a
// preempted or core-shared audio thread underruns → choppy sound. Give the audio thread a dedicated core
// + real-time priority, and keep the UI/emulator-advancing work off that core. Best-effort: failures (no
// RT permission when not root) are ignored — it just falls back to the default scheduling.
void tuneAudioThread() {
    const long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
    if (ncpu > 1) {
        cpu_set_t set; CPU_ZERO(&set); CPU_SET(ncpu - 1, &set); // pin to the last core
        pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
    }
    sched_param sp{}; sp.sched_priority = 80;
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);
}
void pinUiThreadAwayFromAudioCore() {
    const long ncpu = sysconf(_SC_NPROCESSORS_ONLN);
    if (ncpu <= 2) return; // too few cores to segregate
    cpu_set_t set; CPU_ZERO(&set);
    for (long c = 0; c + 1 < ncpu; ++c) CPU_SET(c, &set); // all cores except the audio core (the last)
    pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
}
#endif

// ---- audio ----------------------------------------------------------------------------------------
// SDL calls this on its own audio thread. It owns the Engine while running (setAudioThreadOwns(true)),
// so it drains the control-thread command ring each block then renders — mirrors PluginDSP::run.
void audioCb(void* userdata, Uint8* stream, int len) {
    auto* a = static_cast<AppState*>(userdata);
#if defined(__linux__)
    static std::atomic<bool> tuned{false};
    if (!tuned.exchange(true)) tuneAudioThread(); // once, on the real audio thread
#endif
    const int frames = len / static_cast<int>(2 * sizeof(float));
    if (frames <= 0) { std::memset(stream, 0, len); return; }
    if (static_cast<int>(a->audioL.size()) < frames) { a->audioL.resize(frames); a->audioR.resize(frames); }

    a->invoker.drainInto(a->engine);
    a->engine.setBpm(120.0);
    a->engine.setTransport(true);
    a->engine.processBlock(static_cast<std::uint32_t>(frames), a->audioL.data(), a->audioR.data());

    auto* out = reinterpret_cast<float*>(stream);
    for (int i = 0; i < frames; ++i) { out[2 * i] = a->audioL[i]; out[2 * i + 1] = a->audioR[i]; }
}

// Open the SDL audio device at the requested rate/block + size the render scratch. No frequency-change
// flag → the device opens at exactly reqSampleRate (PipeWire resamples), so the value the UI shows is
// truthful. Returns false (and the app runs muted) if the device won't open.
bool openAudio(AppState& a) {
    SDL_AudioSpec want{}, have{};
    want.freq = a.reqSampleRate;
    want.format = AUDIO_F32SYS;
    want.channels = 2;
    want.samples = static_cast<Uint16>(a.reqBlockSize);
    want.callback = audioCb;
    want.userdata = &a;
    a.audioDev = SDL_OpenAudioDevice(nullptr, 0, &want, &have, 0);
    if (a.audioDev == 0) {
        std::fprintf(stderr, "[retroplug-sdl] SDL_OpenAudioDevice(%d Hz, %d frames) failed: %s (muted)\n",
                     a.reqSampleRate, a.reqBlockSize, SDL_GetError());
        return false;
    }
    a.sampleRate = have.freq;
    a.audioL.assign(have.samples, 0.0f);
    a.audioR.assign(have.samples, 0.0f);
    return true;
}

std::string audioCfgPath(AppState& a) { return a.hostSvc.configDir() + "/audio.cfg"; }

void loadAudioConfig(AppState& a) {
    if (FILE* f = std::fopen(audioCfgPath(a).c_str(), "r")) {
        int sr = 0, bs = 0;
        if (std::fscanf(f, "%d %d", &sr, &bs) == 2 && sr > 0 && bs > 0) { a.reqSampleRate = sr; a.reqBlockSize = bs; }
        std::fclose(f);
    }
}

void saveAudioConfig(AppState& a) {
    if (FILE* f = std::fopen(audioCfgPath(a).c_str(), "w")) {
        std::fprintf(f, "%d %d\n", a.reqSampleRate, a.reqBlockSize);
        std::fclose(f);
    }
}

// Live audio reconfigure (the Audio settings submenu): stop the device, take the Engine back from the
// audio thread, re-rate it, re-open at the new rate/block, hand it back — the plugin's deactivate →
// setSampleRate → activate handoff. Then persist. Called on the UI thread.
void reconfigureAudio(AppState& a, int sampleRate, int blockSize) {
    if (sampleRate == a.reqSampleRate && blockSize == a.reqBlockSize && a.audioDev) return; // no-op
    if (a.audioDev) { SDL_PauseAudioDevice(a.audioDev, 1); SDL_CloseAudioDevice(a.audioDev); a.audioDev = 0; }
    a.invoker.setAudioThreadOwns(false);
    a.invoker.drainInto(a.engine);
    a.reqSampleRate = sampleRate;
    a.reqBlockSize  = blockSize;
    a.engine.setSampleRate(sampleRate); // re-rate live cores (safe — audio thread stopped)
    if (openAudio(a)) {
        a.invoker.setAudioThreadOwns(true);
        SDL_PauseAudioDevice(a.audioDev, 0);
    }
    saveAudioConfig(a);
    std::fprintf(stderr, "[retroplug-sdl] audio reconfigured: %d Hz, %d frames\n", a.reqSampleRate, a.reqBlockSize);
}

// ---- screenshot (headless proof) ------------------------------------------------------------------
// Dump the display's composited draw buffer (the exact frame presented, including top-layer overlays
// like the file browser) so a headless run (SDL_VIDEODRIVER=offscreen) can screenshot for a test.
bool writeScreenshot(AppState& a, const std::string& path);

// ---- boot ------------------------------------------------------------------------------------------

bool bootControlPlane(AppState& a) {
    if (!a.host.init()) { std::fprintf(stderr, "[retroplug-sdl] TjsHostRuntime init failed\n"); return false; }
    JSContext* ctx = a.host.context();

    registerCoreBackends(a.factory);

    a.transport = std::make_unique<rpcpp::QuickJSTransport>(ctx, [](JSContext*, JSValue) {});
    a.server    = std::make_unique<BackendRpcServer>(*a.transport, rpcpp::QuickJSCodec{ctx});
    registerHostRpc(*a.server, a.hostSvc);
    registerEmulatorRpc(*a.server, a.engineSvc);
    registerDspKernelRpc(*a.server, a.engineSvc);
    a.server->addDiscoveryMethod();

    // globalThis[Symbol.for("plugin")] = { __rpcSend } — the namespace realBackend.ts targets.
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue sym    = JS_NewSymbol(ctx, "plugin", /*is_global*/ 1);
    JSAtom atom    = JS_ValueToAtom(ctx, sym);
    JSValue ns     = JS_NewObjectProto(ctx, JS_NULL);
    BackendRpcServer* srv = a.server.get();
    a.host.bindRpcSend(ns, [srv](JSContext* sctx, JSValueConst req) -> JSValue {
        auto out = srv->processMessage(req);
        if (!out) return JS_NULL;
        return out->materialize(sctx);
    });
    JS_DefinePropertyValue(ctx, global, atom, ns, JS_PROP_C_W_E);
    JS_FreeAtom(ctx, atom);
    JS_FreeValue(ctx, sym);
    JS_FreeValue(ctx, global);

    // Systems bake the sample rate at construct — set it BEFORE the bundle composes / autoloads.
    a.engine.setSampleRate(a.sampleRate);

    a.host.evalModuleBytecode(rp_cp_bundle, rp_cp_bundle_size);
    for (int i = 0; i < 1000 && !readReady(a.host); ++i) a.host.pump();
    if (!readReady(a.host)) { std::fprintf(stderr, "[retroplug-sdl] control plane not ready\n"); return false; }
    return true;
}

bool setupUi(AppState& a) {
    lv_init();
    lv_tick_set_cb(sdlTicksCb);

    a.display = lv_display_create(a.width, a.height);
    if (!a.display) return false;
    const lv_color_format_t cf = lv_display_get_color_format(a.display);
    const std::uint32_t stride = lv_draw_buf_width_to_stride(a.width, cf);
    a.drawBuf.assign(static_cast<std::size_t>(stride) * a.height, 0);
    lv_display_set_buffers(a.display, a.drawBuf.data(), nullptr, a.drawBuf.size(), LV_DISPLAY_RENDER_MODE_DIRECT);
    lv_display_set_flush_cb(a.display, flushCb);

    a.group = lv_group_create();
    lv_group_set_default(a.group);
    a.keypad = lv_indev_create();
    lv_indev_set_type(a.keypad, LV_INDEV_TYPE_KEYPAD);
    lv_indev_set_read_cb(a.keypad, keypadReadCb);
    lv_indev_set_driver_data(a.keypad, &a);
    lv_indev_set_group(a.keypad, a.group);
    a.pointer = lv_indev_create();
    lv_indev_set_type(a.pointer, LV_INDEV_TYPE_POINTER);
    lv_indev_set_read_cb(a.pointer, pointerReadCb);
    lv_indev_set_driver_data(a.pointer, &a);

    if (!a.ui.init()) { std::fprintf(stderr, "[retroplug-sdl] LvglJsEngine init failed\n"); return false; }

    JSContext* ctx = a.ui.getContext();
    if (ctx && !hasGlobalFunction(ctx, "__rp_mountUI")) {
        if (a.ui.evalModuleBytecode(rp_ui_bundle, rp_ui_bundle_size) != 0) {
            std::fprintf(stderr, "[retroplug-sdl] failed to eval UI bundle\n");
            return false;
        }
    }
    a.ui.attachDisplay(); // → __rp_mountUI

    // Black out the screen + strip the theme chrome, and make the React-tree root track the screen (100%)
    // — same as PluginUI so nothing draws a border / inset / scrollbar.
    if (lv_obj_t* screen = lv_screen_active()) {
        lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
        lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
        lv_obj_set_style_border_width(screen, 0, 0);
        lv_obj_set_style_radius(screen, 0, 0);
        lv_obj_set_style_pad_all(screen, 0, 0);
        lv_obj_remove_flag(screen, LV_OBJ_FLAG_SCROLLABLE);
    }
    if (lv_obj_t* win = GetWindowInstance()) {
        lv_obj_set_style_width(win, lv_pct(100), 0);
        lv_obj_set_style_height(win, lv_pct(100), 0);
    }
    if (ctx) installWindowHooks(ctx);
    return true;
}

bool setupSdl(AppState& a) {
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_GAMECONTROLLER) != 0) {
        std::fprintf(stderr, "[retroplug-sdl] SDL_Init failed: %s\n", SDL_GetError());
        return false;
    }
    Uint32 winFlags = 0;
    if (std::getenv("RETROPLUG_SDL_FULLSCREEN")) winFlags |= SDL_WINDOW_FULLSCREEN;
    a.window = SDL_CreateWindow("RetroPlug", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                a.width, a.height, winFlags);
    if (!a.window) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateWindow failed: %s\n", SDL_GetError()); return false; }
    a.renderer = SDL_CreateRenderer(a.window, -1, SDL_RENDERER_SOFTWARE);
    if (!a.renderer) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateRenderer failed: %s\n", SDL_GetError()); return false; }
    a.texture = SDL_CreateTexture(a.renderer, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING,
                                  a.width, a.height);
    if (!a.texture) { std::fprintf(stderr, "[retroplug-sdl] SDL_CreateTexture failed: %s\n", SDL_GetError()); return false; }

    // Audio: apply any persisted rate/block (the Audio settings submenu) then open before boot so the
    // obtained rate seeds the Engine. The dummy driver (headless) still fires the callback, so the
    // emulator advances even with no device.
    loadAudioConfig(a);
    openAudio(a);
    return true;
}

void present(AppState& a) {
    if (!a.dirty) return; // nothing redrew this frame — leave the screen as-is (huge idle CPU saving)
    const int stride = static_cast<int>(lv_draw_buf_width_to_stride(a.width, lv_display_get_color_format(a.display)));
    // Upload only the changed region (clamped) from the draw buffer; the streaming texture keeps the rest.
    int x1 = std::max(0, (int)a.dirtyRect.x1), y1 = std::max(0, (int)a.dirtyRect.y1);
    int x2 = std::min((int)a.width - 1, (int)a.dirtyRect.x2), y2 = std::min((int)a.height - 1, (int)a.dirtyRect.y2);
    if (x2 >= x1 && y2 >= y1) {
        SDL_Rect rect{x1, y1, x2 - x1 + 1, y2 - y1 + 1};
        const std::uint8_t* src = a.drawBuf.data() + static_cast<std::size_t>(y1) * stride + static_cast<std::size_t>(x1) * 4;
        SDL_UpdateTexture(a.texture, &rect, src, stride);
    }
    SDL_RenderCopy(a.renderer, a.texture, nullptr, nullptr);
    SDL_RenderPresent(a.renderer);
    a.dirty = false;
}

void handleEvents(AppState& a) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        switch (ev.type) {
            case SDL_QUIT: a.running = false; break;
            case SDL_KEYDOWN:
            case SDL_KEYUP: {
                // While the file browser is open, keyboard drives it (desktop testing) — not the React UI.
                if (a.fb.active) {
                    if (ev.type == SDL_KEYDOWN) {
                        switch (ev.key.keysym.sym) {
                            case SDLK_UP:     fbMove(a, -1); break;
                            case SDLK_DOWN:   fbMove(a, 1); break;
                            case SDLK_PAGEUP: fbMove(a, -8); break;
                            case SDLK_PAGEDOWN: fbMove(a, 8); break;
                            case SDLK_RETURN: fbActivate(a); break;
                            case SDLK_ESCAPE: fbCancel(a); break;
                            default: break;
                        }
                    }
                    break;
                }
                std::uint32_t lv, dpf;
                if (mapSdlKey(ev.key.keysym.sym, lv, dpf)) feedKey(a, lv, dpf, ev.type == SDL_KEYDOWN);
                break;
            }
            case SDL_MOUSEMOTION: a.mousePos = {ev.motion.x, ev.motion.y}; break;
            case SDL_MOUSEBUTTONDOWN:
            case SDL_MOUSEBUTTONUP:
                a.mousePos = {ev.button.x, ev.button.y};
                a.mouseDown = ev.type == SDL_MOUSEBUTTONDOWN;
                break;
            default: break;
        }
    }
}

} // namespace

int main(int argc, char** argv) {
    AppState app;
    g_app = &app;

    // --- args / env ---
    std::string autoloadPath;
    if (const char* env = std::getenv("RETROPLUG_AUTOLOAD_PROJECT")) autoloadPath = env;
    long exitAfterFrames = 0;
    if (const char* env = std::getenv("RETROPLUG_SDL_EXIT_AFTER_FRAMES")) exitAfterFrames = std::atol(env);
    std::string screenshotPath;
    if (const char* env = std::getenv("RETROPLUG_SDL_SCREENSHOT")) screenshotPath = env;
    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if (arg == "--autoload" && i + 1 < argc) autoloadPath = argv[++i];
        else if (arg == "--width" && i + 1 < argc) app.width = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        else if (arg == "--height" && i + 1 < argc) app.height = static_cast<std::uint32_t>(std::atoi(argv[++i]));
        else if (arg == "--screenshot" && i + 1 < argc) screenshotPath = argv[++i];
    }

    if (!setupSdl(app)) return 1;
    if (!bootControlPlane(app)) return 1;

    // Autoload a .rplg project before the audio thread takes the Engine (structural build runs direct).
    if (!autoloadPath.empty()) {
        const std::string ok = callGlobal(app.host, "__rp_loadProjectPath", autoloadPath.c_str());
        std::fprintf(stderr, "[retroplug-sdl] autoload %s -> %s\n", autoloadPath.c_str(), ok.empty() ? "false/void" : ok.c_str());
    }

    if (!setupUi(app)) return 1;

    // Hand the Engine to the SDL audio thread (control-plane edits become push-only, drained per block)
    // then start it. Mirrors PluginDSP::activate.
    app.invoker.setAudioThreadOwns(true);
#if defined(__linux__)
    pinUiThreadAwayFromAudioCore(); // keep the 60 fps UI/emulator work off the audio thread's core
#endif
    if (app.audioDev) SDL_PauseAudioDevice(app.audioDev, 0);

    std::fprintf(stderr, "[retroplug-sdl] running %ux%u @ %.0f Hz\n", app.width, app.height, app.sampleRate);

    // Test hook: exercise a live audio reconfigure (device close/reopen + engine re-rate) headlessly.
    if (std::getenv("RETROPLUG_SDL_TEST_RECONFIG")) {
        reconfigureAudio(app, 44100, 512);
        std::fprintf(stderr, "[retroplug-sdl] post-reconfigure: %d Hz, %d frames, dev=%u\n",
                     app.reqSampleRate, app.reqBlockSize, app.audioDev);
    }

    // Test hook: open the native file browser at a given dir (headless screenshot verification).
    if (const char* td = std::getenv("RETROPLUG_SDL_TEST_BROWSER")) {
        const char* pats = std::getenv("RETROPLUG_SDL_TEST_BROWSER_PATTERNS");
        fbOpen(app, "Load ROM", pats ? pats : "*.cpp *.hpp *.md *.gb *.rplg", false);
        if (*td == '/') { app.fb.dir = td; fbPopulate(app); }
    }

    // --- the 60 fps loop: input → JS frame → LVGL render → present ---
    long frame = 0;
    while (app.running) {
        const Uint32 t0 = SDL_GetTicks();
        handleEvents(app);
        if (JSContext* ctx = app.ui.getContext()) {
            app.ui.emit("frame", 0, nullptr); // drives EmulatorTile's getFrame
            pumpGamepad(app);
            (void)ctx;
        }
        app.ui.tick();          // pump the shared host's JS/libuv loop
        lv_timer_handler();     // LVGL indev read + layout + render into drawBuf
        present(app);

        if (!screenshotPath.empty() && exitAfterFrames > 0 && frame + 1 == exitAfterFrames)
            writeScreenshot(app, screenshotPath);
        if (exitAfterFrames > 0 && ++frame >= exitAfterFrames) app.running = false;

        const Uint32 dt = SDL_GetTicks() - t0;
        if (dt < 16) SDL_Delay(16 - dt); // ~60 fps
    }

    // --- teardown: reclaim the Engine, unmount, drop SDL ---
    if (app.audioDev) { SDL_PauseAudioDevice(app.audioDev, 1); SDL_CloseAudioDevice(app.audioDev); }
    app.invoker.setAudioThreadOwns(false);
    app.invoker.drainInto(app.engine);
    app.invoker.reclaimReleased();

    if (app.display) lv_display_enable_invalidation(app.display, false);
    if (lv_obj_t* screen = lv_screen_active()) lv_obj_clean(screen);
    app.ui.detachDisplay();
    lv_timer_handler();

    if (app.texture) SDL_DestroyTexture(app.texture);
    if (app.renderer) SDL_DestroyRenderer(app.renderer);
    if (app.window) SDL_DestroyWindow(app.window);
    SDL_Quit();
    g_app = nullptr;
    return 0;
}

namespace {
bool writeScreenshot(AppState& a, const std::string& path) {
    if (!a.display || a.drawBuf.empty()) return false;
    const std::uint32_t w = a.width, h = a.height;
    const std::uint32_t stride = lv_draw_buf_width_to_stride(w, lv_display_get_color_format(a.display));
    std::vector<unsigned char> rgb(static_cast<std::size_t>(w) * h * 3);
    for (std::uint32_t y = 0; y < h; ++y)
        for (std::uint32_t x = 0; x < w; ++x) {
            const std::uint8_t* px = a.drawBuf.data() + static_cast<std::size_t>(y) * stride + x * 4;
            unsigned char* out = rgb.data() + (static_cast<std::size_t>(y) * w + x) * 3;
            out[0] = px[2]; out[1] = px[1]; out[2] = px[0]; // ARGB8888 (B,G,R,A) -> R,G,B
        }
    const unsigned err = lodepng_encode24_file(path.c_str(), rgb.data(), w, h);
    if (err) { std::fprintf(stderr, "[retroplug-sdl] screenshot error %u\n", err); return false; }
    std::fprintf(stderr, "[retroplug-sdl] screenshot -> %s (%ux%u)\n", path.c_str(), w, h);
    return true;
}
} // namespace
