// The greenfield DPF editor — a thin DISTRHO::UI on the generic LVGL top-level widget.
//
// It attaches its LVGL display layer to the plugin's plugin-lifetime TjsHostRuntime (via the in-process
// GreenfieldSharedDSP handoff + LvglJsEngine::useExternalHost), evals the React UI bundle once onto that
// same context, and mounts it. The backend is already reachable there through Symbol.for("plugin")
// .__rpcSend (bound by bootControlPlane), so — unlike the legacy PluginUI — there is no PluginJsBridge,
// no params/gamepad/file-browser plumbing here: the UI drives the real Engine over RPC exactly as the
// headless harness does.
//
// The GL flush, the keypad/pointer indevs, the 60 fps lv_timer_handler, and DPF→LVGL input translation
// all come free from the base widget (dpf-widgets/generic/LVGL). This class only: pumps the JS host +
// emits "frame" per idle, mirrors keyboard/mouse to the JS event bus (the App's Esc handler / policy),
// swallows the wheel into a hit-tested scroll, and dumps a screenshot on the env hook.

#include "DistrhoUI.hpp"
#include "Application.hpp" // getWindow().getApp().isStandalone()

#include "dpfjs/LvglJsEngine.hpp"
#include "dpfjs/host/TjsHostRuntime.hpp" // TjsHostRuntime + quickjs.h/tjs.h
#include "dpfjs/Env.hpp"                 // dpfjs::getenvWithPrefix

#include "PluginGreenfieldShared.hpp"

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <vector>

extern "C" {
#include "lvgl.h"
}

#include "native/core/img/png/lodepng.h"

extern "C" {
// Generated by tjsc (CMake retroplug-greenfield-ui-bundle, -p gfui_): the React UI as QuickJS bytecode.
extern const std::uint8_t  gfui_ui_bundle[];
extern const std::uint32_t gfui_ui_bundle_size;
}

START_NAMESPACE_DISTRHO

namespace {
bool hasGlobalFunction(JSContext* ctx, const char* name) {
    JSValue global = JS_GetGlobalObject(ctx);
    JSValue v      = JS_GetPropertyStr(ctx, global, name);
    const bool ok  = JS_IsFunction(ctx, v);
    JS_FreeValue(ctx, v);
    JS_FreeValue(ctx, global);
    return ok;
}
} // namespace

class PluginGreenfieldUI : public UI {
    // The display layer for this editor session, riding the plugin's shared host (useExternalHost).
    LvglJsEngine jsEngine;

    // Screenshot hook (RETROPLUG_SCREENSHOT_PATH, cadence RETROPLUG_SCREENSHOT_INTERVAL_MS): dump the
    // whole LVGL screen as PNG from the UI thread. Distinct from BackendFacade::screenshot (one core).
    std::string screenshotPath_;
    std::chrono::milliseconds screenshotInterval_{1000};
    std::chrono::steady_clock::time_point screenshotLast_{};
    bool windowTitleSet_ = false;

    void maybeWriteScreenshot() {
        if (screenshotPath_.empty()) return;
        const auto now = std::chrono::steady_clock::now();
        if (now - screenshotLast_ < screenshotInterval_) return;
        screenshotLast_ = now;

        lv_obj_t* screen = lv_screen_active();
        if (!screen) return;
        lv_draw_buf_t* snap = lv_snapshot_take(screen, LV_COLOR_FORMAT_ARGB8888);
        if (!snap) return;

        const uint32_t w = snap->header.w;
        const uint32_t h = snap->header.h;
        std::vector<unsigned char> rgb(static_cast<size_t>(w) * h * 3);
        const uint8_t* src = snap->data; // ARGB8888 = B,G,R,A on little-endian
        for (size_t i = 0, n = static_cast<size_t>(w) * h; i < n; ++i) {
            rgb[i * 3 + 0] = src[i * 4 + 2];
            rgb[i * 3 + 1] = src[i * 4 + 1];
            rgb[i * 3 + 2] = src[i * 4 + 0];
        }
        const unsigned err = lodepng_encode24_file(screenshotPath_.c_str(), rgb.data(), w, h);
        if (err) d_stderr("[greenfield-ui] screenshot lodepng error %u: %s", err, lodepng_error_text(err));
        lv_draw_buf_destroy(snap);
    }

public:
    PluginGreenfieldUI() : UI(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT) {
        setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT);

        if (const char* p = dpfjs::getenvWithPrefix("SCREENSHOT_PATH"); p && *p) {
            screenshotPath_ = p;
            if (const char* iv = dpfjs::getenvWithPrefix("SCREENSHOT_INTERVAL_MS"); iv && *iv)
                if (int ms = std::atoi(iv); ms > 0) screenshotInterval_ = std::chrono::milliseconds(ms);
            d_stdout("[greenfield-ui] screenshot hook: %s every %lld ms", screenshotPath_.c_str(),
                     static_cast<long long>(screenshotInterval_.count()));
        }

        // Reach the plugin's shared host (in-process) and attach this editor's LVGL layer to it BEFORE
        // init(), so the UI runs on the control-plane context where __rpcSend already lives.
        GreenfieldSharedDSP* shared = nullptr;
        if (void* dspPtr = getPluginInstancePointer()) shared = getGreenfieldSharedDSP(dspPtr);
        if (shared && shared->host)
            jsEngine.useExternalHost(*shared->host);
        else
            d_stderr("[greenfield-ui] no shared host — UI cannot reach the backend");

        if (!jsEngine.init()) {
            d_stderr("[greenfield-ui] LvglJsEngine init failed");
            return;
        }

        // Eval the UI bundle once per host: __rp_mountUI is registered by the bundle at module scope, so
        // its absence means the bundle hasn't run yet in this (shared, already-control-plane) context.
        JSContext* ctx = jsEngine.getContext();
        if (ctx && !hasGlobalFunction(ctx, "__rp_mountUI")) {
            if (jsEngine.evalModuleBytecode(gfui_ui_bundle, gfui_ui_bundle_size) != 0)
                d_stderr("[greenfield-ui] failed to eval UI bundle");
            else
                d_stdout("[greenfield-ui] React UI loaded (embedded)");
        }

        jsEngine.attachDisplay(); // → __rp_mountUI

        // Force the screen bg black so the default-light theme can't leak through any uncovered gap.
        if (lv_obj_t* screen = lv_screen_active()) {
            lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
            lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
        }
    }

    ~PluginGreenfieldUI() override {
        // Unmount (→ __rp_unmountUI) + flush the async widget deletes while the context is still alive,
        // leaving the shared host clean for the next editor session.
        jsEngine.detachDisplay();
        lv_timer_handler();
        if (lv_obj_t* screen = lv_screen_active()) lv_obj_clean(screen);
    }

protected:
    void parameterChanged(uint32_t, float) override {} // UI drives nothing via params

    void uiIdle() override {
        if (!windowTitleSet_) {
            windowTitleSet_ = true;
            if (getWindow().getApp().isStandalone()) getWindow().setTitle("RetroPlug Greenfield");
        }
        if (jsEngine.getContext()) jsEngine.emit("frame", 0, nullptr); // drives EmulatorTile's getFrame
        jsEngine.tick();                                               // pump the shared host's JS loop
        maybeWriteScreenshot();
    }

    bool onKeyboard(const KeyboardEvent& ev) override {
        UI::onKeyboard(ev); // base → LVGL keypad indev (menu arrow nav / Enter)
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[2] = {JS_NewUint32(ctx, ev.key), JS_NewBool(ctx, ev.press)};
            jsEngine.emit("key", 2, args); // the App's Esc handler + any key policy reads this
            JS_FreeValue(ctx, args[0]);
            JS_FreeValue(ctx, args[1]);
        }
        return true;
    }

    bool onMouse(const MouseEvent& ev) override {
        UI::onMouse(ev); // base → LVGL pointer indev (tile focus / onClick)
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[4] = {JS_NewUint32(ctx, ev.button), JS_NewBool(ctx, ev.press),
                               JS_NewFloat64(ctx, ev.pos.getX()), JS_NewFloat64(ctx, ev.pos.getY())};
            jsEngine.emit("mouse", 4, args);
            for (JSValue& v : args) JS_FreeValue(ctx, v);
        }
        return true;
    }

    // Desktop wheel → scroll the hit-tested scrollable ancestor (the menu). Swallow otherwise, so the
    // base's encoder path can't shuffle group focus across widgets. Ported from legacy PluginUI.
    bool onScroll(const ScrollEvent& ev) override {
        lv_obj_t* const scr = lv_screen_active();
        if (scr) {
            lv_point_t p = {static_cast<int32_t>(ev.pos.getX()), static_cast<int32_t>(ev.pos.getY())};
            lv_obj_t* hit = lv_indev_search_obj(scr, &p);
            const int32_t step = 24;
            const int32_t dy = static_cast<int32_t>(ev.delta.getY() * step);
            const int32_t dx = static_cast<int32_t>(ev.delta.getX() * step);
            for (lv_obj_t* it = hit; it; it = lv_obj_get_parent(it)) {
                if (!lv_obj_has_flag(it, LV_OBJ_FLAG_SCROLLABLE)) continue;
                const bool vScroll = (dy != 0) && (lv_obj_get_scroll_top(it) + lv_obj_get_scroll_bottom(it) > 0);
                const bool hScroll = (dx != 0) && (lv_obj_get_scroll_left(it) + lv_obj_get_scroll_right(it) > 0);
                if (vScroll || hScroll) {
                    lv_obj_scroll_by_bounded(it, hScroll ? -dx : 0, vScroll ? dy : 0, LV_ANIM_OFF);
                    return true;
                }
            }
        }
        return true;
    }

    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(PluginGreenfieldUI)
};

UI* createUI() { return new PluginGreenfieldUI(); }

END_NAMESPACE_DISTRHO
