// GENERATED by scripts/gen-risa-symbols.mjs — do not hand-edit. Internal-RAM addresses of risa's
// runtime-state variables (src/seq.h, src/ui_common.h), read per-block from the NES 2 KB RAM snapshot.
// Verified identical across the PAL and NTSC builds, so one table serves both regions.

export interface RisaSymbols {
  seq_mode: number;
  seq_active: number;
  seq_current_bpm: number;
  song_queue_active: number;
  bss_song_row: number;
  bss_song_last_row: number;
  bss_chain_idx: number;
  bss_chain_row: number;
  bss_phrase_idx: number;
  bss_phrase_last_row: number;
  zp_phrase_row: number;
  bss_table_idx: number;
  bss_last_inst: number;
  apu_current_note: number;
  kit_active_idx: number;
  ui_current_screen: number;
  ui_cursor_row: number;
  ui_cursor_col: number;
  ui_track: number;
}

export const RISA_SYMBOLS: Record<string, RisaSymbols> = {
  "2.2.1": {
    seq_mode: 0x6a,
    seq_active: 0x6b,
    seq_current_bpm: 0x37d,
    song_queue_active: 0x3af,
    bss_song_row: 0x382,
    bss_song_last_row: 0x387,
    bss_chain_idx: 0x3aa,
    bss_chain_row: 0x38c,
    bss_phrase_idx: 0x391,
    bss_phrase_last_row: 0x39b,
    zp_phrase_row: 0x76,
    bss_table_idx: 0x3bb,
    bss_last_inst: 0x3ca,
    apu_current_note: 0x378,
    kit_active_idx: 0x337,
    ui_current_screen: 0x678,
    ui_cursor_row: 0x670,
    ui_cursor_col: 0x671,
    ui_track: 0x672,
  },
};
