#include "UiTestHarness.hpp"

#include <cstdlib>
#include <cstring>
#include <fstream>
#include <stdexcept>

// LVGL is built in custom-global mode (LV_GLOBAL_CUSTOM): the application must
// provide lv_global_default(). In the plugin DPF's LVGLWidget supplies a
// per-instance one (deps/dpf-widgets/generic/LVGL.cpp); headless we need a
// single process-wide instance. Zero-initialized like DPF's calloc; lv_init()
// populates it. Leaked intentionally (process-lifetime singleton).
extern "C" lv_global_t* lv_global_default(void) {
    static lv_global_t* g = static_cast<lv_global_t*>(std::calloc(1, sizeof(lv_global_t)));
    return g;
}

#include "PluginJsBridge.hpp"
#include "system/RomFormat.hpp"
#include "system/SystemBase.hpp"
#include "system/SystemTypes.hpp"   // AudioBlockInfo
#include "system/sameboy/SameBoyConfig.hpp"
#include "system/sameboy/SameBoySystem.hpp"

extern "C" {
    #include <quickjs.h>
}

// lv_binding_js internals (global widget registry + root window + PNG encoder).
#include "native/core/basic/comp.hpp"          // comp_map, BasicComponent, ECOMP_TYPE
#include "native/components/component.hpp"      // GetWindowInstance()
#include "native/core/img/png/lodepng.h"

// The embedded React UI bundle (QuickJS bytecode), generated by ui-regenerate
// into build/ui/bundle_data.c and linked into this test binary.
extern "C" {
    extern const uint8_t  ui_bundle[];
    extern const uint32_t ui_bundle_size;
}

namespace rpui {

namespace {

// The active harness, for the static JS / LVGL trampolines (single runtime,
// single-threaded, one harness at a time — same recovery pattern as
// cli/TestHarness.cpp's g_activeImpl).
UiTestHarness* g_active = nullptr;

// Simulated millisecond clock. Advanced by pump() so LVGL timers fire
// deterministically without wall-clock dependence.
std::uint32_t g_tickMs = 0;
std::uint32_t tickCb() { return g_tickMs; }

// No-op flush: the draw buffer already holds the rendered pixels; there's no
// GL texture / window to push to. Just acknowledge so LVGL continues.
void flushCb(lv_display_t* disp, const lv_area_t*, uint8_t*) {
    lv_display_flush_ready(disp);
}

// Headless input devices read nothing (released). Present so the focus group +
// component creation (which calls lv_group_add_obj) work like in the plugin.
void keypadReadCb(lv_indev_t*, lv_indev_data_t* data) {
    data->state = LV_INDEV_STATE_RELEASED;
}

std::vector<std::uint8_t> slurpBytes(const std::string& path) {
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) throw std::runtime_error("cannot open " + path);
    const std::streamsize size = in.tellg();
    if (size <= 0) throw std::runtime_error("empty file: " + path);
    in.seekg(0, std::ios::beg);
    std::vector<std::uint8_t> buf(static_cast<std::size_t>(size));
    if (!in.read(reinterpret_cast<char*>(buf.data()), size))
        throw std::runtime_error("read failed: " + path);
    return buf;
}

// globalThis.__rp_tagTestId(uid, name): the UI calls this from a ref so we can
// map a stable name to the rendered lv_obj. uid is lv_binding_js's component id
// (a string); comp_map resolves it to the native instance. Inert in the real
// plugin (the function isn't installed there — the UI uses optional chaining).
JSValue jsTagTestId(JSContext* ctx, JSValueConst, int argc, JSValueConst* argv) {
    if (!g_active || argc < 2) return JS_UNDEFINED;
    const char* uid  = JS_ToCString(ctx, argv[0]);
    const char* name = JS_ToCString(ctx, argv[1]);
    if (uid && name) {
        auto it = comp_map.find(uid);
        if (it != comp_map.end() && it->second)
            g_active->recordTestId(name, it->second->instance);
    }
    if (uid)  JS_FreeCString(ctx, uid);
    if (name) JS_FreeCString(ctx, name);
    return JS_UNDEFINED;
}

} // namespace

bool Snapshot::isFlat() const {
    if (argb.size() < 8) return true;
    const std::uint32_t first = *reinterpret_cast<const std::uint32_t*>(argb.data());
    for (std::size_t i = 4; i + 4 <= argb.size(); i += 4)
        if (*reinterpret_cast<const std::uint32_t*>(argb.data() + i) != first)
            return false;
    return true;
}

UiTestHarness::UiTestHarness(std::uint32_t width, std::uint32_t height)
    : width_(width), height_(height) {}

UiTestHarness::~UiTestHarness() {
    // Mirror PluginUI's teardown ordering: drop the bridge, clean the widget
    // tree while the JS context is still alive (so delete events drain safely),
    // then shut the engine and tear down the LVGL display.
    bridge_.reset();
    if (lv_obj_t* scr = lv_screen_active()) lv_obj_clean(scr);
    engine_.shutdown();
    if (keypad_)  lv_indev_delete(keypad_);
    if (display_) lv_display_delete(display_);
    if (group_)   lv_group_delete(group_);
    if (g_active == this) g_active = nullptr;
}

bool UiTestHarness::boot() {
    if (booted_) return true;
    g_active = this;

    // --- LVGL: the cheap, non-GL subset of LVGLWidget::init ----------------
    lv_init(); // idempotent in v9
    lv_tick_set_cb(tickCb);

    display_ = lv_display_create(width_, height_);
    if (!display_) return false;

    const lv_color_format_t cf = lv_display_get_color_format(display_);
    const std::uint32_t stride = lv_draw_buf_width_to_stride(width_, cf);
    drawBuf_.assign(static_cast<std::size_t>(stride) * height_, 0);
    lv_display_set_buffers(display_, drawBuf_.data(), nullptr, drawBuf_.size(),
                           LV_DISPLAY_RENDER_MODE_DIRECT);
    lv_display_set_flush_cb(display_, flushCb);

    group_ = lv_group_create();
    lv_group_set_default(group_);
    keypad_ = lv_indev_create();
    lv_indev_set_type(keypad_, LV_INDEV_TYPE_KEYPAD);
    lv_indev_set_read_cb(keypad_, keypadReadCb);
    lv_indev_set_group(keypad_, group_);

    // --- JS engine + bridge + UI bundle ------------------------------------
    if (!engine_.init()) return false;

    // Match PluginUI: black screen background + root window tracks the display.
    if (lv_obj_t* scr = lv_screen_active()) {
        lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), 0);
        lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    }
    if (lv_obj_t* win = GetWindowInstance()) {
        lv_obj_set_style_width(win, lv_pct(100), 0);
        lv_obj_set_style_height(win, lv_pct(100), 0);
    }

    engine_.setParamWriteCallback([](uint32_t, float) {});
    engine_.registerParameter(0, "gain");

    installTestIdHook();

    bridge_ = std::make_unique<PluginJsBridge>(
        engine_, &project_, &commands_, &events_, &sampleRate_, &focusedSystemId_,
        /*userConfig*/ nullptr, /*recentFiles*/ nullptr);

    if (engine_.evalModuleBytecode(ui_bundle, ui_bundle_size) != 0) return false;

    booted_ = true;
    return true;
}

void UiTestHarness::installTestIdHook() {
    JSContext* ctx = engine_.getContext();
    if (!ctx) return;
    JSValue g = JS_GetGlobalObject(ctx);
    JS_SetPropertyStr(ctx, g, "__rp_tagTestId",
                      JS_NewCFunction(ctx, jsTagTestId, "__rp_tagTestId", 2));
    JS_FreeValue(ctx, g);
}

std::uint32_t UiTestHarness::loadRom(const std::string& path) {
    auto bytes = slurpBytes(path);
    if (detectRomFormat(bytes) != RomFormat::SameBoy)
        throw std::runtime_error("UiTestHarness::loadRom supports SameBoy ROMs only: " + path);

    SameBoyConfig cfg;
    cfg.romPath  = path;
    cfg.model    = SameBoyModel::CgbC;
    cfg.fastBoot = true;
    auto sys = std::make_unique<SameBoySystem>(
        project_.nextSystemId(), cfg, std::move(bytes));
    sys->onActivate(sampleRate_.load());
    const SystemId id = sys->id();
    project_.adoptSystem(sys.release());
    project_.rebuildLinkGroups();
    notifyConfigChanged(); // tell the UI to re-query listSystems
    return static_cast<std::uint32_t>(id);
}

void UiTestHarness::notifyConfigChanged() {
    if (engine_.getContext()) engine_.emit("config-changed", 0, nullptr);
}

void UiTestHarness::pump(int iterations) {
    constexpr std::uint32_t kFrames = 1024; // ~23ms at 44.1kHz
    if (scratchL_.size() < kFrames) { scratchL_.resize(kFrames); scratchR_.resize(kFrames); }
    float* outs[2] = { scratchL_.data(), scratchR_.data() };
    for (int i = 0; i < iterations; ++i) {
        // Advance the emulator so framebuffers publish (no DSP thread headless),
        // matching the per-tick emulator advance the plugin's audio thread does.
        std::fill_n(scratchL_.data(), kFrames, 0.0f);
        std::fill_n(scratchR_.data(), kFrames, 0.0f);
        AudioBlockInfo info{ kFrames, sampleRate_.load(), 120.0, 0.0, false };
        project_.onProcess(info, outs);

        g_tickMs += 23; // keep UI tick roughly in step with the audio block
        if (bridge_) {
            bridge_->pumpAsync();
            bridge_->pumpMemorySnapshots();
        }
        if (engine_.getContext()) engine_.emit("frame", 0, nullptr);
        engine_.tick();
        lv_timer_handler();
    }
}

Snapshot UiTestHarness::snapshot() {
    Snapshot out;
    lv_obj_t* scr = lv_screen_active();
    if (!scr) return out;
    lv_draw_buf_t* snap = lv_snapshot_take(scr, LV_COLOR_FORMAT_ARGB8888);
    if (!snap) return out;
    out.width  = snap->header.w;
    out.height = snap->header.h;
    const std::size_t bytes = static_cast<std::size_t>(out.width) * out.height * 4;
    out.argb.assign(snap->data, snap->data + bytes);
    lv_draw_buf_destroy(snap);
    return out;
}

bool UiTestHarness::snapshotPng(const std::string& path) {
    Snapshot s = snapshot();
    if (s.argb.empty()) return false;
    std::vector<unsigned char> rgb(static_cast<std::size_t>(s.width) * s.height * 3);
    for (std::size_t i = 0, n = static_cast<std::size_t>(s.width) * s.height; i < n; ++i) {
        rgb[i * 3 + 0] = s.argb[i * 4 + 2]; // B,G,R,A -> R,G,B
        rgb[i * 3 + 1] = s.argb[i * 4 + 1];
        rgb[i * 3 + 2] = s.argb[i * 4 + 0];
    }
    return lodepng_encode24_file(path.c_str(), rgb.data(), s.width, s.height) == 0;
}

std::size_t UiTestHarness::widgetCount() const { return comp_map.size(); }

std::size_t UiTestHarness::countByType(int compType) const {
    std::size_t n = 0;
    for (const auto& [uid, bc] : comp_map)
        if (bc && static_cast<int>(bc->type) == compType) ++n;
    return n;
}

lv_obj_t* UiTestHarness::findFirstByType(int compType) const {
    for (const auto& [uid, bc] : comp_map)
        if (bc && static_cast<int>(bc->type) == compType) return bc->instance;
    return nullptr;
}

lv_obj_t* UiTestHarness::findByText(const std::string& text) const {
    for (const auto& [uid, bc] : comp_map) {
        if (!bc || bc->type != COMP_TYPE_TEXT || !bc->instance) continue;
        const char* t = lv_label_get_text(bc->instance);
        if (t && text == t) return bc->instance;
    }
    return nullptr;
}

lv_obj_t* UiTestHarness::findByTestId(const std::string& name) const {
    auto it = testIds_.find(name);
    return it == testIds_.end() ? nullptr : it->second;
}

} // namespace rpui
