// GENERATED by scripts/gen-smsggdj-symbols.mjs - do not hand-edit. Work-RAM OFFSETS (not CPU
// addresses: work RAM is mapped at $C000 and readRam/writeRam index the region) of the smsggdj
// variables a host-side song load has to touch.
//
// Why this exists: SMDJ4 keeps a song's NAME and ECHO settings in the directory entry, not in the
// 6,912-byte block (src/rle.asm:34, "metadata, not in the block"), so poking only the block loads the
// right notes with the previous song's echo - which is audible. These offsets let a load be complete.
//
// One entry per smsggdj version. WLA assigns RAM addresses from RAMSECTION ordering, so adding a
// variable anywhere earlier shifts everything after it; addresses are never assumed to carry across
// versions without being checked. See VERSION_ALIASES in ./layout.ts for versions proven identical.

export interface SmsggdjSymbols {
  wave_ram: number;
  wave_ram_len: number;
  phrase_pool: number;
  phrase_pool_len: number;
  song_name: number;
  song_name_len: number;
  echo_mode: number;
  echo_mode_len: number;
  song_edited: number;
  song_edited_len: number;
  prj_slot: number;
  prj_slot_len: number;
  play_state: number;
  play_state_len: number;
  eng_len: number;
  eng_len_len: number;
  live_q: number;
  live_q_len: number;
  groove_sel: number;
  groove_sel_len: number;
  groove_pos: number;
  groove_pos_len: number;
  psg_vols: number;
  psg_vols_len: number;
  echo_len: number;
}

export const SMSGGDJ_SYMBOLS: Record<string, SmsggdjSymbols> = {
  "0.45": {
    wave_ram: 0x0,
    wave_ram_len: 0x100,
    phrase_pool: 0x100,
    phrase_pool_len: 0xd00,
    song_name: 0x1ea4,
    song_name_len: 0x8,
    echo_mode: 0x1b6d,
    echo_mode_len: 0x1,
    song_edited: 0x1dc0,
    song_edited_len: 0x1,
    prj_slot: 0x1d58,
    prj_slot_len: 0x1,
    play_state: 0x1b00,
    play_state_len: 0x1,
    eng_len: 0x1b0b,
    eng_len_len: 0x1,
    live_q: 0x1c7a,
    live_q_len: 0x4,
    groove_sel: 0x1b0c,
    groove_sel_len: 0x1,
    groove_pos: 0x1b08,
    groove_pos_len: 0x1,
    psg_vols: 0x1f4c,
    psg_vols_len: 0x4,
    echo_len: 0x8,
  },
};
