// GENERATED by tools/gen-lsdj-offsets (pnpm lsdj:gen-offsets) — do not edit by hand.
//
// Per-version byte SHIFT of LSDj's drifting WRAM block (tempo / CURRENT_SCREEN / cursors) relative to
// the LSDisJ 9.2.L reference layout (see REF_DRIFT in offsets.ts). The block moves as a unit between
// builds (e.g. 9.4.2 is 9.2.L shifted -1), so one integer per version derives every drifting offset.
// A version absent from this map has its drifting fields resolved to null → the reader reports screen
// "unknown" / cursor null / tempo null rather than reading a wrong address.
//
// Key = "major.minor.patchLabel" (letter patch levels kept verbatim, e.g. "9.2.L"). Regenerate over
// the ROM corpus with:  pnpm lsdj:gen-offsets
export const driftShifts: Record<string, number> = {
  "8.2.1": -11,
  "8.5.1": -4,
  "8.9.0": -3,
  "9.0.0": -2,
  "9.0.1": -3,
  "9.1.0": 2,
  "9.1.1": 2,
  "9.2.0": 0,
  "9.2.9": 0,
  "9.2.L": 0,
  "9.3.0": 0,
  "9.3.3": 0,
  "9.4.0": -1,
  "9.4.1": -1,
  "9.4.2": -1,
};
