// Build the test SDK and embed it in retroplug-cli as C arrays, so the BINARY owns it and a consumer
// repo never has to carry (or keep in sync) a copy.
//
//   node tools/embed-sdk.mjs <outDir> <out.c>
//
// The consumer-side copy used to be synced alongside the binary, which made a stale SDK against a newer
// binary a real failure mode - exactly the class of bug the sync script existed to avoid. Embedding it
// removes that: `retroplug-cli test` / `run` materialize the SDK next to the tests when it is missing or
// its stamp does not match rp_sdk_hash, so it can never lag the binary. See cli/sdkAssets.ts.
//
// Emits two symbols:
//   rp_sdk_dts[] + _size   the TypeScript declarations (what an editor and tsc read off disk)
//   rp_sdk_hash[]          a content stamp, so the staleness check is O(1)
//
// The authoring layer ITSELF is not here: it ships as module bytecode (rp_retroplug_cli, compiled by
// the CMake target next to this one) and is resolved from QuickJS's loaded-module table, so it never
// needs to exist as a file. Only the declarations do, because editors read them off disk.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const outDir = resolve(process.argv[2] ?? resolve(REPO, "build/cli-sdk"));
const outC = resolve(process.argv[3] ?? resolve(REPO, "build/native/sdk-assets_data.c"));

mkdirSync(dirname(outC), { recursive: true });

// Reuse the existing SDK builder rather than duplicating its esbuild config.
execFileSync(process.execPath, [resolve(HERE, "build-cli-sdk.mjs"), outDir], { stdio: "inherit" });

const js = readFileSync(resolve(outDir, "retroplug-cli.js"));
const dts = readFileSync(resolve(outDir, "retroplug-cli.d.ts"));
const hash = createHash("sha256").update(js).update(dts).digest("hex").slice(0, 16);

/** A byte array as C source. 16 per line keeps the generated file diffable-ish and the compiler happy. */
function carray(name, buf) {
  const parts = [`extern const unsigned char ${name}[];\nconst unsigned char ${name}[] = {\n`];
  for (let i = 0; i < buf.length; i += 16) {
    const row = [];
    for (let j = i; j < Math.min(i + 16, buf.length); j++) row.push("0x" + buf[j].toString(16).padStart(2, "0"));
    parts.push("  " + row.join(",") + ",\n");
  }
  parts.push("};\n");
  parts.push(`extern const unsigned int ${name}_size;\nconst unsigned int ${name}_size = ${buf.length}u;\n\n`);
  return parts.join("");
}

writeFileSync(
  outC,
  "// GENERATED by tools/embed-sdk.mjs - do not edit, do not commit.\n\n" +
      carray("rp_sdk_dts", dts) +
    `extern const char rp_sdk_hash[];\nconst char rp_sdk_hash[] = "${hash}";\n`,
);

console.log(`wrote ${outC} (js ${js.length}B, d.ts ${dts.length}B, hash ${hash})`);
