// Generate zod + TS types for the LSDj Sav model from its JSON Schema.
//
// Usage (called from CMake):
//   node tools/gen-sav-ts.js <sav-schema-dump-exe> <out-dir>
//
// 1. Spawns <sav-schema-dump-exe>, captures stdout (a JSON Schema barrel).
// 2. Bundles the rpcpp TS codegen and calls generateZod/generateTs on it.
// 3. Demangles reflect-cpp's `rp__lsdj__model__X__tagged` def names to `X`,
//    rewrites TaggedUnion z.union() into z.discriminatedUnion("type", ...) so
//    fixture errors point at the right variant, and writes:
//      <out-dir>/SavSchema.ts  (zod schemas + inferred types)
//      <out-dir>/SavTypes.ts   (plain TS interfaces)
// These are derived; never commit them (like build/ui/generated/PluginService.ts).

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const { execFileSync } = require('child_process');

const REPO_ROOT  = path.resolve(__dirname, '..');
const LV_DIR     = path.join(REPO_ROOT, 'deps/lv_binding_js');
const CODEGEN_TS = path.join(REPO_ROOT, 'deps/rpcpp/clients/typescript/codegen/src/index.ts');
const esbuild    = require(path.join(LV_DIR, 'node_modules/esbuild'));

const [, , exePath, outDirArg] = process.argv;
if (!exePath || !outDirArg) {
    process.stderr.write('usage: gen-sav-ts.js <sav-schema-dump-exe> <out-dir>\n');
    process.exit(2);
}
const outDir = path.resolve(outDirArg);

const schema = JSON.parse(execFileSync(exePath, [], { encoding: 'utf8' }));

fs.mkdirSync(outDir, { recursive: true });
const bundleOut = path.join(outDir, '.sav-codegen-bundle.mjs');
esbuild.buildSync({
    entryPoints: [CODEGEN_TS],
    bundle: true, format: 'esm', platform: 'node', target: 'node20',
    outfile: bundleOut, logLevel: 'silent',
});

// The codegen collapses reflect-cpp's `rp__lsdj__model__X__tagged` def names
// into PascalCase `RpLsdjModelXTagged`; strip the namespace prefix and the
// variant `Tagged` suffix to get clean TS names (Sav, Song, KitInstrument, …).
const demangle = (s) => s.replace(/[Rr]pLsdjModel/g, '').replace(/Tagged/g, '');

// Upgrade the instrument TaggedUnion from z.union([z.lazy(() => XSchema), ...])
// to z.discriminatedUnion("type", [XSchema, ...]) so a bad fixture reports
// "type=kit, field X invalid" instead of a union-of-everything error. The
// variant schemas are emitted before Song, so dropping z.lazy is safe; each
// has a leading `type: z.literal(...)` discriminator.
function discriminate(zod) {
    const LAZY_UNION = /z\.union\(\[((?:\s*z\.lazy\(\(\) => \w+Schema\),?)+)\s*\]\)/g;
    return zod.replace(LAZY_UNION, (whole, body) => {
        const names = [...body.matchAll(/z\.lazy\(\(\) => (\w+Schema)\)/g)].map((m) => m[1]);
        if (names.length > 1 && names.every((n) => /Instrument/.test(n)))
            return `z.discriminatedUnion("type", [${names.join(', ')}])`;
        return whole;
    });
}

function writeIfChanged(file, content) {
    let prior = null;
    try { prior = fs.readFileSync(file, 'utf8'); } catch (_) { /* missing */ }
    if (prior !== content) {
        fs.writeFileSync(file, content);
        console.log(`Generated ${path.relative(REPO_ROOT, file)}`);
    } else {
        console.log(`Up-to-date ${path.relative(REPO_ROOT, file)}`);
    }
}

(async () => {
    const codegen = await import(pathToFileURL(bundleOut).href);
    const header = '// GENERATED by tools/gen-sav-ts.js from the C++ Sav model. Do not edit / commit.\n';

    const zod = header + discriminate(demangle(codegen.generateZod(schema)));
    const ts  = header + demangle(codegen.generateTs(schema));

    writeIfChanged(path.join(outDir, 'SavSchema.ts'), zod);
    writeIfChanged(path.join(outDir, 'SavTypes.ts'), ts);
})().catch((e) => { console.error(e); process.exit(1); });
