/*
 * RetroPlug UI — thin shell.
 *
 * Responsibilities:
 *  - DPF lifecycle (constructor sizing, uiIdle, onResize, parameterChanged,
 *    uiFileBrowserSelected).
 *  - JS engine + bridge ownership.
 *  - Forward DPF keyboard events to LVGL focus AND to JS via the "key"
 *    event channel. Routing decisions live in TS.
 *  - Drain DSP→UI events (free released SystemBase pointers off the audio
 *    thread) and emit a per-tick "frame" event for React.
 *
 * This file deliberately knows nothing about menus, GB button mapping, or
 * framebuffer rendering. Those live in TS (ui/EmulatorTile.tsx,
 * runtime/lvgljs/input.ts, ui/PluginUI.tsx).
 */

#include "DistrhoUI.hpp"
#include "ResizeHandle.hpp"
#include "GamepadManager.hpp"
#include "LvglJsEngine.hpp"
#include "PluginJsBridge.hpp"
#include "PluginShared.hpp"
#include "config/UserConfig.hpp"

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <string>
#include <vector>

extern "C" {
    #include "lvgl.h"
}

#include "native/core/img/png/lodepng.h"

#include "transport/EventQueue.hpp"

extern "C" {
    // Generated by tjsc — see CMakeLists.txt UI bundle pipeline. Holds the
    // UI module compiled to QuickJS bytecode.
    extern const uint8_t  ui_bundle[];
    extern const uint32_t ui_bundle_size;
}

START_NAMESPACE_DISTRHO

// Fallback for plugin formats where DSP and UI live in separate binaries (LV2).
__attribute__((weak))
SharedDSPData* getSharedDSPData(void*) { return nullptr; }

// --------------------------------------------------------------------------------------------------------------------

class LVGLPluginUI : public UI
{
    float fGain = 0.0f;
    ResizeHandle fResizeHandle;
    LvglJsEngine jsEngine;
    std::unique_ptr<PluginJsBridge> bridge;
    retroplug::GamepadManager gamepad;
    SharedDSPData* shared = nullptr;
    // Declared AFTER bridge so it destructs FIRST: stops the efsw watcher
    // before bridge/jsEngine tear down, so a stray bg-thread file event
    // can't race into a half-destroyed JS context.
    UserConfig userConfig;

    // Track the last setSize request so we can detect a tiled-WM clamp.
    // Once `wmControlled_` flips true (compositor returned a different
    // size than we asked for) we leave it true — the WM owns geometry
    // for the rest of the session.
    uint requestedW_     = 0;
    uint requestedH_     = 0;
    bool wmControlled_   = false;

    // Screenshot hook (env-var triggered). When RETROPLUG_SCREENSHOT_PATH is
    // set, periodically dump the current LVGL screen as PNG. Cadence is
    // RETROPLUG_SCREENSHOT_INTERVAL_MS (default 1000). All work happens on
    // the UI thread inside uiIdle.
    std::string screenshotPath_;
    std::chrono::milliseconds screenshotInterval_{1000};
    std::chrono::steady_clock::time_point screenshotLast_{};

    void maybeWriteScreenshot()
    {
        if (screenshotPath_.empty()) return;

        const auto now = std::chrono::steady_clock::now();
        if (now - screenshotLast_ < screenshotInterval_) return;
        screenshotLast_ = now;

        lv_obj_t* screen = lv_screen_active();
        if (!screen) return;

        lv_draw_buf_t* snap = lv_snapshot_take(screen, LV_COLOR_FORMAT_ARGB8888);
        if (!snap) return;

        const uint32_t w = snap->header.w;
        const uint32_t h = snap->header.h;
        std::vector<unsigned char> rgb(static_cast<size_t>(w) * h * 3);
        // ARGB8888 in memory is B,G,R,A on little-endian; transcode to RGB.
        const uint8_t* src = snap->data;
        for (size_t i = 0, n = static_cast<size_t>(w) * h; i < n; ++i) {
            rgb[i * 3 + 0] = src[i * 4 + 2];
            rgb[i * 3 + 1] = src[i * 4 + 1];
            rgb[i * 3 + 2] = src[i * 4 + 0];
        }

        const unsigned err = lodepng_encode24_file(screenshotPath_.c_str(),
                                                   rgb.data(), w, h);
        if (err)
            d_stderr("Screenshot lodepng error %u: %s",
                     err, lodepng_error_text(err));

        lv_draw_buf_destroy(snap);
    }

    // Drain DSP→UI events:
    //  - SystemReleased: the DSP shipped a displaced SystemBase back so the
    //    UI thread can free it. Must run before anything else that could
    //    observe a stale system pointer.
    //  - ConfigChanged: project tree changed (setState reload, add/remove,
    //    swap). Re-emitted to JS as "config-changed" so React re-queries
    //    plugin.listSystems().
    void drainEvents()
    {
        if (!shared || !shared->events) return;
        bool configChanged = false;
        Event ev;
        while (shared->events->tryPop(ev)) {
            switch (ev.kind) {
                case Event::Kind::SystemReleased:
                    delete ev.payload.systemReleased.system;
                    break;
                case Event::Kind::ConfigChanged:
                    configChanged = true;
                    break;
                case Event::Kind::None:
                default:
                    break;
            }
        }
        if (configChanged && jsEngine.getContext())
            jsEngine.emit("config-changed", 0, nullptr);
    }

public:
    bool requestWindowSize(uint w, uint h)
    {
        if (w == 0 || h == 0) return wmControlled_;
        requestedW_ = w;
        requestedH_ = h;
        if (wmControlled_) return true; // don't fight the compositor
        setSize(w, h);
        return wmControlled_;
    }

    bool isWindowSizeControlled() const { return wmControlled_; }

    LVGLPluginUI()
        : UI(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT),
          fResizeHandle(this)
    {
        // Seed the requested-size baseline. The WM may already have decided
        // a different size by the time onResize fires (Hyprland tiles us
        // before the UI initializes); without this, the detection branch
        // would skip because the guard `requestedW_ != 0` was false.
        requestedW_ = DISTRHO_UI_DEFAULT_WIDTH;
        requestedH_ = DISTRHO_UI_DEFAULT_HEIGHT;

        const double scaleFactor = getScaleFactor();

        if (d_isNotEqual(scaleFactor, 1.0))
        {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
            setSize(DISTRHO_UI_DEFAULT_WIDTH * scaleFactor, DISTRHO_UI_DEFAULT_HEIGHT * scaleFactor);
        }
        else
        {
            setGeometryConstraints(DISTRHO_UI_DEFAULT_WIDTH, DISTRHO_UI_DEFAULT_HEIGHT);
        }

        if (isResizable())
            fResizeHandle.hide();

        if (const char* p = std::getenv("RETROPLUG_SCREENSHOT_PATH"); p && *p) {
            screenshotPath_ = p;
            if (const char* iv = std::getenv("RETROPLUG_SCREENSHOT_INTERVAL_MS"); iv && *iv) {
                if (int ms = std::atoi(iv); ms > 0)
                    screenshotInterval_ = std::chrono::milliseconds(ms);
            }
            d_stdout("Screenshot hook enabled: %s every %lld ms",
                     screenshotPath_.c_str(),
                     static_cast<long long>(screenshotInterval_.count()));
        }

        // In-process plugin formats: reach the DSP-owned Project via the shared
        // pointer. LV2-UI returns nullptr; the bridge degrades gracefully.
        if (void* dspPtr = getPluginInstancePointer())
            shared = getSharedDSPData(dspPtr);

        if (jsEngine.init())
        {
            // Force the LVGL screen background to black. Without this the
            // default-light theme leaks a light grey/white through any gap
            // not covered by the React tree (visible especially on tiled
            // WMs that pad the window beyond our requested size).
            if (lv_obj_t* screen = lv_screen_active()) {
                lv_obj_set_style_bg_color(screen, lv_color_hex(0x000000), 0);
                lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
            }

            // lv_binding_js's WindowInit() pins the React-tree root's
            // width/height to the LVGL display's CURRENT pixel size. That
            // captures the initial 480x432 and never updates when the
            // compositor resizes us, so React's "100%" stays bound to
            // 480x432 forever. Switch to lv_pct(100) so the root tracks
            // the active screen — which IS resized by lv_display_set_resolution.
            if (lv_obj_t* win = GetWindowInstance()) {
                lv_obj_set_style_width(win, lv_pct(100), 0);
                lv_obj_set_style_height(win, lv_pct(100), 0);
            }

            jsEngine.setParamWriteCallback(
                [this](uint32_t idx, float val) {
                    editParameter(idx, true);
                    setParameterValue(idx, val);
                    editParameter(idx, false);
                });
            for (uint32_t i = 0; i < kPluginParameterCount; ++i)
                jsEngine.registerParameter(i, kPluginParameters[i].symbol);

            // Spin up the per-user config + bindings watcher BEFORE the
            // bridge so the bridge can hand a non-null pointer to the RPC
            // service. The reload callback emits "user-config-changed" so
            // the JS side knows to refetch and rebuild its key map.
            userConfig.setOnReload([this]() {
                if (jsEngine.getContext())
                    jsEngine.emit("user-config-changed", 0, nullptr);
            });
            userConfig.start();

            // Plugin-specific JS bridge. Must exist before evalModule so
            // useEffect handlers can register before the bundle's first render.
            bridge = std::make_unique<PluginJsBridge>(
                jsEngine,
                shared ? shared->project         : nullptr,
                shared ? shared->commands        : nullptr,
                shared ? shared->events          : nullptr,
                shared ? shared->sampleRate      : nullptr,
                shared ? shared->focusedSystemId : nullptr,
                &userConfig);

            // The bridge invokes this for any file-browser action — Open ROM,
            // Add instance, Save project, Load project. The flags map to
            // DPF's FileBrowserOptions: `saving=true` flips the dialog into
            // save mode, `defaultName` pre-fills the filename field.
            bridge->setOpenFileBrowserCallback([this](const char* title,
                                                      bool saving,
                                                      const char* defaultName) {
                FileBrowserOptions opts;
                opts.title       = title ? title : "";
                opts.saving      = saving;
                opts.defaultName = defaultName ? defaultName : "";
                openFileBrowser(opts);
            });

            // Window-size plumbing: JS asks the UI to resize; the UI relays
            // to DPF. The query callback lets JS detect tiled-WM clamping.
            bridge->setWindowSizeCallback([this](uint w, uint h) {
                requestWindowSize(w, h);
            });
            bridge->setIsWindowSizeControlledQuery([this]() {
                return isWindowSizeControlled();
            });

            // Auto-load a project on startup. Useful for fast debug loops
            // and for headless agent verification of LoadProject (the
            // alternative is driving the native file dialog under Xvfb
            // which doesn't reliably work).
            if (const char* p = std::getenv("RETROPLUG_AUTOLOAD_PROJECT"); p && *p) {
                d_stdout("[PluginUI] auto-loading project: %s", p);
                bridge->loadProjectFromPath(p);
            }
            // Diagnostic shortcut for framebuffer verification: load a ROM
            // directly without going through the file dialog. Mirrors the
            // _PROJECT path above. Plain debug aid — not part of the public
            // env var surface.
            if (const char* p = std::getenv("RETROPLUG_AUTOLOAD_ROM"); p && *p) {
                d_stdout("[PluginUI] auto-loading ROM: %s", p);
                bridge->loadRomFromPath(p);
            }

            const char* devPath = std::getenv("LVGL_PLUGIN_BUNDLE_PATH");
            if (devPath && *devPath)
            {
                if (jsEngine.evalModule(devPath) != 0)
                    d_stderr("Failed to load %s", devPath);
                else
                    d_stdout("LvglJsEngine: React UI loaded from %s", devPath);
            }
            else
            {
                if (jsEngine.evalModuleBytecode(ui_bundle, ui_bundle_size) != 0)
                    d_stderr("Failed to load embedded UI bundle");
                else
                    d_stdout("LvglJsEngine: React UI loaded (embedded)");
            }
        }
        else
        {
            d_stderr("Failed to initialize LvglJsEngine");
        }
    }

    ~LVGLPluginUI() override
    {
        // Tear down the LVGL widget tree (React-managed views, canvases,
        // event handlers) WHILE the JS engine is still alive. Otherwise the
        // base UI destructor walks the widget tree after member destruction
        // — by which point jsEngine has freed the JSContext — and any event
        // that fires during deletion (DEFOCUSED on the focused menu item,
        // CHILD_DELETED bubbling up, etc.) hits lv_binding_js's FireEventToJS
        // which does `qrt->ctx` with no null check. Cleaning the screen here
        // drains all those events with a valid context. Renoise close-while-
        // probing reproduces this; carla and pluginval happen to close in a
        // different order and don't trip it.
        if (lv_obj_t* screen = lv_screen_active())
            lv_obj_clean(screen);
    }

protected:
    void parameterChanged(uint32_t index, float value) override
    {
        if (index == 0) fGain = value;
        jsEngine.pushParameter(index, value);
    }

    void uiIdle() override
    {
        drainEvents();

        // Drain the user-config watcher's dirty flag on the UI thread.
        // efsw fires on a bg thread but only flips an atomic; the parse +
        // RPC-event emit lives here.
        userConfig.pumpReloadsOnUiThread();

        // Walk live memory subscriptions, read tear-free snapshots from the
        // DSP-published triple-buffers, hash for dedup, push "memory"
        // notifications through the rpcpp transport for any region that
        // changed since the last tick. Cheap when no subscriptions are
        // active. Runs BEFORE pumpAsync so notifications added here drain
        // in the same uiIdle tick rather than landing on the next one.
        if (bridge) bridge->pumpMemorySnapshots();

        // Drain the rpcpp transport's outgoing queue — async resolver
        // responses AND notification frames (incl. memory snapshots) land
        // in `engine.emit("rpc-message", ...)` for the JS transport to
        // forward to its onFrame handler.
        if (bridge) bridge->pumpAsync();

        // Emit a per-tick "frame" event so React's <EmulatorTile> knows to
        // poll plugin.getFrame. One emit per UI idle ties cadence to LVGL's
        // redraw — host-throttled when the window isn't visible.
        if (JSContext* ctx = jsEngine.getContext()) {
            jsEngine.emit("frame", 0, nullptr);
            pumpGamepad(ctx);
        }

        jsEngine.tick();
        maybeWriteScreenshot();
    }

    // Poll SDL game controllers and forward press / release / axis / hot-
    // plug events to the JS bridge using per-event channels. Mirrors the
    // keyboard pattern at onKeyboard() below: C++ owns the device read,
    // TS owns the policy (key/button → GameboyButton, menu nav, etc.).
    void pumpGamepad(JSContext* ctx)
    {
        gamepad.update([this, ctx](const retroplug::GamepadEvent& ev) {
            switch (ev.kind) {
                case retroplug::GamepadEvent::Kind::Connected: {
                    JSValue args[2] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.name ? ev.name : ""),
                    };
                    jsEngine.emit("gamepad-connected", 2, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Disconnected: {
                    JSValue args[1] = { JS_NewInt32(ctx, ev.pad) };
                    jsEngine.emit("gamepad-disconnected", 1, args);
                    JS_FreeValue(ctx, args[0]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Button: {
                    JSValue args[3] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.button ? ev.button : ""),
                        JS_NewBool(ctx, ev.pressed),
                    };
                    jsEngine.emit("gamepad-button", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
                case retroplug::GamepadEvent::Kind::Axis: {
                    JSValue args[3] = {
                        JS_NewInt32(ctx, ev.pad),
                        JS_NewString(ctx, ev.axis ? ev.axis : ""),
                        JS_NewFloat64(ctx, ev.value),
                    };
                    jsEngine.emit("gamepad-axis", 3, args);
                    JS_FreeValue(ctx, args[0]);
                    JS_FreeValue(ctx, args[1]);
                    JS_FreeValue(ctx, args[2]);
                    break;
                }
            }
        });
    }

    void uiFileBrowserSelected(const char* filename) override
    {
        if (!filename || !*filename) return; // user cancelled
        if (!bridge) return;
        bridge->onFileBrowserSelected(filename);
    }

    void onResize(const ResizeEvent& ev) override
    {
        UI::onResize(ev);
        const uint w = ev.size.getWidth();
        const uint h = ev.size.getHeight();
        d_stderr("[PluginUI] onResize %ux%u (asked %ux%u, wmControlled=%d)",
                 w, h, requestedW_, requestedH_, wmControlled_ ? 1 : 0);
        if (!wmControlled_ && requestedW_ != 0 && requestedH_ != 0) {
            if (w != requestedW_ || h != requestedH_) {
                wmControlled_ = true;
                d_stderr("[PluginUI] window-size compositor-controlled (asked %ux%u, got %ux%u); "
                         "JS will center content from now on",
                         requestedW_, requestedH_, w, h);
            }
        }
    }

    bool onKeyboard(const KeyboardEvent& ev) override
    {
        // Always forward to LVGL focus routing first — the parent chain
        // (LVGLWidget<TopLevelWidget>::onKeyboard) translates the DPF key
        // and writes it into LVGL's keyBuffer for the focused widget.
        UI::onKeyboard(ev);

        // Then mirror the event to JS so TS-side routing (game input,
        // menu toggle, etc.) can react. JS is the single source of truth
        // for keyboard policy.
        if (JSContext* ctx = jsEngine.getContext()) {
            JSValue args[2] = {
                JS_NewUint32(ctx, ev.key),
                JS_NewBool(ctx, ev.press),
            };
            jsEngine.emit("key", 2, args);
            JS_FreeValue(ctx, args[0]);
            JS_FreeValue(ctx, args[1]);
        }
        return true;
    }

    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(LVGLPluginUI)
};

// --------------------------------------------------------------------------------------------------------------------

UI* createUI()
{
    return new LVGLPluginUI();
}

// --------------------------------------------------------------------------------------------------------------------

END_NAMESPACE_DISTRHO
